# aa-unconfined
# Autogenerated from man page /usr/share/man/man8/aa-unconfined.8.gz
complete -c aa-unconfined -l paranoid -d 'Displays all processes from /proc filesystem with tcp or udp ports that do no…'
complete -c aa-unconfined -l with-ss -d 'Use the ss\\|(8) command to find processes listening on network sockets (the d…'

