# acyclic
# Autogenerated from man page /usr/share/man/man1/acyclic.1.gz
complete -c acyclic -s n -d 'No output is produced, though the return value will indicate whether the grap…'
complete -c acyclic -s v -d 'Print information about whether the file is acyclic, has a cycle or is undire…'
complete -c acyclic -s o -d 'causes the output to be written to the specified file; by default, output is …'
complete -c acyclic -s '?' -d 'option causes the program to print usage information'

