# addftinfo
# Autogenerated from man page /usr/share/man/man1/addftinfo.1.gz
complete -c addftinfo -o x-height -d 'The height of lowercase letters without ascenders such as x'
complete -c addftinfo -o fig-height -d 'The height of figures (digits)'
complete -c addftinfo -o asc-height -d 'The height of characters with ascenders, such as b, d or l'
complete -c addftinfo -o body-height -d 'The height of characters such as parentheses'
complete -c addftinfo -o cap-height -d 'The height of uppercase letters such as A'
complete -c addftinfo -o comma-depth -d 'The depth of a comma'
complete -c addftinfo -o desc-depth -d 'The depth of characters with descenders, such as p, q, or y'
complete -c addftinfo -s v -d 'prints the version number'
complete -c addftinfo -o body-depth -d 'The depth of characters such as parentheses'

