# afmtodit
# Autogenerated from man page /usr/share/man/man1/afmtodit.1.gz
complete -c afmtodit -s a -d 'Use  n as the slant parameter in the font file; this is used by  groff in the…'
complete -c afmtodit -s c -d 'Include comments in the font file in order to identify the PostScript font'
complete -c afmtodit -s d -d 'The device description file is  desc-file rather than the default R DESC '
complete -c afmtodit -s e -d 'The PostScript font should be reencoded to use the encoding described in R en…'
complete -c afmtodit -s f -d 'The internal name of the  groff font is set to R name '
complete -c afmtodit -s i -d 'Generate an italic correction for each character so that the character\'s widt…'
complete -c afmtodit -s o -d 'The output file is  output-file instead of R font '
complete -c afmtodit -s k -d 'Omit any kerning data from the  groff font; use only for monospaced (constant…'
complete -c afmtodit -s m -d 'Prevent negative left italic correction values'
complete -c afmtodit -s n -d 'Don\'t output a  ligatures command for this font; use with monospaced (constan…'
complete -c afmtodit -s s -d 'The font is special'
complete -c afmtodit -s v -d 'Print version and exit'
complete -c afmtodit -o i50 -d 'for italic fonts'
complete -c afmtodit -o i0 -d 'to improve spacing with eqn (1)'
complete -c afmtodit -s x -d 'Don\'t use the built-in Adobe Glyph List.  FILES /usr/share/groff/1. 22'

