# appletviewer-openjdk8
# Autogenerated from man page /usr/share/man/man1/appletviewer-openjdk8.1.gz
complete -c appletviewer-openjdk8 -o debug -d 'br Starts the Applet Viewer in the Java debugger with the \\f3jdb command to d…'
complete -c appletviewer-openjdk8 -o encoding -d 'br Specifies the input HTML file encoding name'
complete -c appletviewer-openjdk8 -o Jjavaoption

