# bcomps
# Autogenerated from man page /usr/share/man/man1/bcomps.1.gz
complete -c bcomps -s s -d 'No output graph is printed.  Implies the  -v  flag'
complete -c bcomps -s t -d 'Print the underlying block-cutvertex tree'
complete -c bcomps -s x -d 'Each biconnected component is printed as a separate root graph'
complete -c bcomps -s v -d 'Prints number of blocks and cutvertices'
complete -c bcomps -s o -d 'If specified, each root graph will be written to a different file with the na…'

