# bluetooth-meshd
# Autogenerated from man page /usr/share/man/man8/bluetooth-meshd.8.gz
complete -c bluetooth-meshd -s h -l help -d 'Print bluetooth-meshd options and exit'
complete -c bluetooth-meshd -s n -l nodetach -d 'Enable logging in foreground'
complete -c bluetooth-meshd -s i -l io -d 'Specifies I/O interface type: '
complete -c bluetooth-meshd -s c -l config -d 'Specifies an explicit config file path instead of relying on the default path…'
complete -c bluetooth-meshd -s s -l storage -d 'Specifies an explicit storage directory path instead of the default path(/var…'
complete -c bluetooth-meshd -s d -l debug -d 'Enable debug output'
complete -c bluetooth-meshd -s b -l dbus-debug -d 'Enable D-Bus debug output'

