# btrfs-image
# Autogenerated from man page /usr/share/man/man8/btrfs-image.8.gz
complete -c btrfs-image -s r -d 'Restore metadump image'
complete -c btrfs-image -s c -d 'Compression level (0 ~ 9)'
complete -c btrfs-image -s t -d 'Number of threads (1 ~ 32) to be used to process the image dump or restore'
complete -c btrfs-image -s o -d 'Use the old restore method, this does not fixup the chunk tree so the restore…'
complete -c btrfs-image -s s -d 'Sanitize the file names when generating the image'
complete -c btrfs-image -s w -d 'Walk all the trees manually and copy any blocks that are referenced'
complete -c btrfs-image -s m -d 'Restore for multiple devices, more than 1 device should be provided'

