# btrfstune
# Autogenerated from man page /usr/share/man/man8/btrfstune.8.gz
complete -c btrfstune -s f -d 'Allow dangerous changes, e. g.  clear the seeding flag or change fsid'
complete -c btrfstune -s m -d '(since kernel: 5. 0) '
complete -c btrfstune -s M -d '(since kernel: 5. 0) '
complete -c btrfstune -s n -d '(since kernel: 3. 14) '
complete -c btrfstune -s r -d '(since kernel: 3. 7) '
complete -c btrfstune -s S -d 'Enable seeding on a given device'
complete -c btrfstune -s u -d 'Change fsid to a randomly generated UUID or continue previous fsid change ope…'
complete -c btrfstune -s U -d 'Change fsid to UUID in all metadata blocks'
complete -c btrfstune -s x -d '(since kernel: 3. 10) '

