# btrfs-qgroup
# Autogenerated from man page /usr/share/man/man8/btrfs-qgroup.8.gz
complete -c btrfs-qgroup -l rescan
complete -c btrfs-qgroup -l no-rescan
complete -c btrfs-qgroup -s c
complete -c btrfs-qgroup -s e
complete -c btrfs-qgroup -s p
complete -c btrfs-qgroup -s r
complete -c btrfs-qgroup -s F
complete -c btrfs-qgroup -s f
complete -c btrfs-qgroup -l raw
complete -c btrfs-qgroup -l human-readable
complete -c btrfs-qgroup -l iec
complete -c btrfs-qgroup -l si
complete -c btrfs-qgroup -l kbytes
complete -c btrfs-qgroup -l mbytes
complete -c btrfs-qgroup -l gbytes
complete -c btrfs-qgroup -l tbytes
complete -c btrfs-qgroup -l sort
complete -c btrfs-qgroup -l sync
complete -c btrfs-qgroup -l ------ -l -- -l -- -d '0/5          16. 00KiB     16. 00KiB 0/261        16. 00KiB     16'

