# btrfs-filesystem
# Autogenerated from man page /usr/share/man/man8/btrfs-filesystem.8.gz
complete -c btrfs-filesystem -s b -l raw
complete -c btrfs-filesystem -s h -l human-readable
complete -c btrfs-filesystem -s H
complete -c btrfs-filesystem -l iec
complete -c btrfs-filesystem -l si
complete -c btrfs-filesystem -s k -l kbytes
complete -c btrfs-filesystem -s m -l mbytes
complete -c btrfs-filesystem -s g -l gbytes
complete -c btrfs-filesystem -s t -l tbytes
complete -c btrfs-filesystem -s r -d 'is passed, files in dir will be defragmented recursively (not descending to s…'
complete -c btrfs-filesystem -s s -d and
complete -c btrfs-filesystem -s l -d 'options below.  Extents bigger than value given by'
complete -c btrfs-filesystem -s c
complete -c btrfs-filesystem -s f
complete -c btrfs-filesystem -s v
complete -c btrfs-filesystem -l summarize
complete -c btrfs-filesystem -l enqueue
complete -c btrfs-filesystem -l mounted
complete -c btrfs-filesystem -s d -l all-devices
complete -c btrfs-filesystem -s T

