# btrfs-map-logical
# Autogenerated from man page /usr/share/man/man8/btrfs-map-logical.8.gz
complete -c btrfs-map-logical -s l -l logical -d 'Logical extent to map'
complete -c btrfs-map-logical -s c -l copy -d 'Copy of the extent to read(usually 1 or 2)'
complete -c btrfs-map-logical -s o -l output -d 'Output file to hold the extent'
complete -c btrfs-map-logical -s b -l bytes -d 'Number of bytes to read'

