# btrfs-check
# Autogenerated from man page /usr/share/man/man8/btrfs-check.8.gz
complete -c btrfs-check -s b -l backup
complete -c btrfs-check -l super -d 'if some of the superblocks are damaged'
complete -c btrfs-check -l check-data-csum
complete -c btrfs-check -l chunk-root
complete -c btrfs-check -s E -l subvol-extents
complete -c btrfs-check -s p -l progress
complete -c btrfs-check -s Q -l qgroup-report
complete -c btrfs-check -s r -l tree-root
complete -c btrfs-check -l readonly
complete -c btrfs-check -s s
complete -c btrfs-check -l clear-space-cache
complete -c btrfs-check -l clear-ino-cache
complete -c btrfs-check -l repair
complete -c btrfs-check -l force -d 'to give users a chance to think twice before running repair, the warnings in …'
complete -c btrfs-check -l init-csum-tree
complete -c btrfs-check -l init-extent-tree
complete -c btrfs-check -l mode

