# btrfs-inspect-internal
# Autogenerated from man page /usr/share/man/man8/btrfs-inspect-internal.8.gz
complete -c btrfs-inspect-internal -s s -d 'has changed in version 4'
complete -c btrfs-inspect-internal -l bytenr -d 'instead.  The option'
complete -c btrfs-inspect-internal -s i -d 'has been deprecated.  Options'
complete -c btrfs-inspect-internal -s f -l full
complete -c btrfs-inspect-internal -s a -l all
complete -c btrfs-inspect-internal -l super
complete -c btrfs-inspect-internal -s F -l force
complete -c btrfs-inspect-internal -s e -l extents
complete -c btrfs-inspect-internal -s d -l device
complete -c btrfs-inspect-internal -s r -l roots
complete -c btrfs-inspect-internal -s R -l backups
complete -c btrfs-inspect-internal -s u -l uuid
complete -c btrfs-inspect-internal -s b
complete -c btrfs-inspect-internal -l follow
complete -c btrfs-inspect-internal -l dfs
complete -c btrfs-inspect-internal -l bfs
complete -c btrfs-inspect-internal -l hide-names
complete -c btrfs-inspect-internal -l csum-headers
complete -c btrfs-inspect-internal -l csum-items
complete -c btrfs-inspect-internal -l noscan
complete -c btrfs-inspect-internal -s t
complete -c btrfs-inspect-internal -s v
complete -c btrfs-inspect-internal -s P
complete -c btrfs-inspect-internal -s o
complete -c btrfs-inspect-internal -l id

