# btrfs-restore
# Autogenerated from man page /usr/share/man/man8/btrfs-restore.8.gz
complete -c btrfs-restore -s s -l snapshots -d 'get also snapshots that are skipped by default'
complete -c btrfs-restore -s x -l xattr -d 'get extended attributes'
complete -c btrfs-restore -s m -l metadata -d 'restore owner, mode and times for files and directories'
complete -c btrfs-restore -s S -l symlinks -d 'restore symbolic links as well as normal files'
complete -c btrfs-restore -s i -l ignore-errors -d 'ignore errors during restoration and continue'
complete -c btrfs-restore -s o -l overwrite -d 'overwrite directories/files in <path>, eg.  for repeated runs'
complete -c btrfs-restore -s t -d 'use <bytenr> to read the root tree'
complete -c btrfs-restore -s f -d 'only restore files that are under specified subvolume root pointed by <bytenr>'
complete -c btrfs-restore -s u -l super -d 'use given superblock mirror identified by <mirror>, it can be 0,1 or 2'
complete -c btrfs-restore -s r -l root -d 'only restore files that are under a specified subvolume whose objectid is <ro…'
complete -c btrfs-restore -s d -d 'find directory'
complete -c btrfs-restore -s l -l list-roots -d 'list subvolume tree roots, can be used as argument for -r'
complete -c btrfs-restore -s D -l dry-run -d 'dry run (only list files that would be recovered)'
complete -c btrfs-restore -l path-regex -d 'restore only filenames matching a regular expression (regex(7)) with a mandat…'
complete -c btrfs-restore -s c -d 'ignore case (--path-regex only)'
complete -c btrfs-restore -s v -l verbose -d '(deprecated) alias for global -v option'

