# btrfs-replace
# Autogenerated from man page /usr/share/man/man8/btrfs-replace.8.gz
complete -c btrfs-replace -s r
complete -c btrfs-replace -s f
complete -c btrfs-replace -s B
complete -c btrfs-replace -l enqueue
complete -c btrfs-replace -s K -l nodiscard
complete -c btrfs-replace -s 1

