# btrfs-subvolume
# Autogenerated from man page /usr/share/man/man8/btrfs-subvolume.8.gz
complete -c btrfs-subvolume -s i
complete -c btrfs-subvolume -l commit -d 'options to wait until the operation is safely stored on the device'
complete -c btrfs-subvolume -s c -l commit-after
complete -c btrfs-subvolume -s C -l commit-each
complete -c btrfs-subvolume -l subvolid
complete -c btrfs-subvolume -s v -l verbose
complete -c btrfs-subvolume -s o
complete -c btrfs-subvolume -s a
complete -c btrfs-subvolume -s p
complete -c btrfs-subvolume -s g
complete -c btrfs-subvolume -s u
complete -c btrfs-subvolume -s q
complete -c btrfs-subvolume -s R
complete -c btrfs-subvolume -s s
complete -c btrfs-subvolume -s r
complete -c btrfs-subvolume -s d
complete -c btrfs-subvolume -s t
complete -c btrfs-subvolume -s G -o ']<value>'
complete -c btrfs-subvolume -l sort
complete -c btrfs-subvolume -l rootid
complete -c btrfs-subvolume -l uuid

