# btrfs-receive
# Autogenerated from man page /usr/share/man/man8/btrfs-receive.8.gz
complete -c btrfs-receive -s f
complete -c btrfs-receive -s C -l chroot
complete -c btrfs-receive -s e
complete -c btrfs-receive -s E -l max-errors
complete -c btrfs-receive -s m
complete -c btrfs-receive -l dump
complete -c btrfs-receive -s q -l quiet
complete -c btrfs-receive -s v
complete -c btrfs-receive -l verbose

