# btrfs-balance
# Autogenerated from man page /usr/share/man/man8/btrfs-balance.8.gz
complete -c btrfs-balance -l full-balance -d 'option.  Please note that the filters must be written together with the'
complete -c btrfs-balance -s d
complete -c btrfs-balance -s m -d and
complete -c btrfs-balance -s s -d 'options, because they\'re optional and bare'
complete -c btrfs-balance -s f -d 'FILTERS section for details about filters'
complete -c btrfs-balance -l background -l bg
complete -c btrfs-balance -l enqueue
complete -c btrfs-balance -s v

