# btrfs-scrub
# Autogenerated from man page /usr/share/man/man8/btrfs-scrub.8.gz
complete -c btrfs-scrub -s c -d and
complete -c btrfs-scrub -s n -d 'options.  Note that not all IO schedulers honor the ionice settings'
complete -c btrfs-scrub -s B
complete -c btrfs-scrub -s d
complete -c btrfs-scrub -s r
complete -c btrfs-scrub -s R
complete -c btrfs-scrub -s f
complete -c btrfs-scrub -s q
complete -c btrfs-scrub -l raw
complete -c btrfs-scrub -l human-readable
complete -c btrfs-scrub -l iec
complete -c btrfs-scrub -l si
complete -c btrfs-scrub -l kbytes
complete -c btrfs-scrub -l mbytes
complete -c btrfs-scrub -l gbytes
complete -c btrfs-scrub -l tbytes

