# btrfs-find-root
# Autogenerated from man page /usr/share/man/man8/btrfs-find-root.8.gz
complete -c btrfs-find-root -s a -d 'Search through all metadata extents, even the root has been already found'
complete -c btrfs-find-root -s g -d 'Filter root tree by it\'s original transaction id, tree root\'s generation in d…'
complete -c btrfs-find-root -s o -d 'Filter root tree by it\'s objectid,tree root\'s objectid in default'
complete -c btrfs-find-root -s l -d 'Filter root tree by B-+ tree\'s level, level 0 in default'

