# btrfs-convert
# Autogenerated from man page /usr/share/man/man8/btrfs-convert.8.gz
complete -c btrfs-convert -l csum -l checksum -d 'Specify the checksum algorithm.  Default is crc32c'
complete -c btrfs-convert -s d -l no-datasum -d 'disable data checksum calculations and set the NODATASUM file flag, this can …'
complete -c btrfs-convert -s i -l no-xattr -d 'ignore xattrs and ACLs of files'
complete -c btrfs-convert -s n -l no-inline -d 'disable inlining of small files to metadata blocks, this will decrease the me…'
complete -c btrfs-convert -s N -l nodesize -d 'set filesystem nodesize, the tree block size in which btrfs stores its metada…'
complete -c btrfs-convert -s r -l rollback -d 'rollback to the original ext2/3/4 filesystem if possible'
complete -c btrfs-convert -s l -l label -d 'set filesystem label during conversion'
complete -c btrfs-convert -s L -l copy-label -d 'use label from the converted filesystem'
complete -c btrfs-convert -s O -l features -d 'A list of filesystem features enabled the at time of conversion'
complete -c btrfs-convert -s p -l progress -d 'show progress of conversion (a heartbeat indicator and number of inodes proce…'
complete -c btrfs-convert -l no-progress -d 'disable progress and show only the main phases of conversion'
complete -c btrfs-convert -l uuid -d 'set the FSID of the new filesystem based on SPEC: . sp'

