# caca-config
# Autogenerated from man page /usr/share/man/man1/caca-config.1.gz
complete -c caca-config -l cflags -d 'Print the compiler flags that are necessary to compile a program or library t…'
complete -c caca-config -l exec-prefix -d 'If specified, use  DIR instead of the installation exec prefix that libcaca w…'
complete -c caca-config -l libs -d 'Print the linker flags that are necessary to link a program or library that u…'
complete -c caca-config -l prefix -d 'If specified, use PREFIX instead of the installation prefix that libcaca was …'
complete -c caca-config -l version -d 'Prints the currently installed version of libcaca on standard output'

