# cache_check
# Autogenerated from man page /usr/share/man/man8/cache_check.8.gz
complete -c cache_check -s h -l help -d 'Print help and exit'
complete -c cache_check -s V -l version -d 'Output version information and exit'
complete -c cache_check -s q -l quiet -d 'Suppress output messages, return only exit code'
complete -c cache_check -l super-block-only -d 'Only check the superblock'
complete -c cache_check -l skip-hints -d 'Skip checking of the policy hint values metadata'
complete -c cache_check -l skip-discards -d 'Skip checking of the discard bits in the metadata'
complete -c cache_check -l clear-needs-check-flag -d 'Clears the \'needs_check\' flag in the superblock'

