# cache_metadata_size
# Autogenerated from man page /usr/share/man/man8/cache_metadata_size.8.gz
complete -c cache_metadata_size -l nr-blocks -d 'Specify the number of cache blocks'
complete -c cache_metadata_size -l block-size -d 'Specify the size of each cache block in 512 byte sectors'
complete -c cache_metadata_size -l device-size -d 'Specify total size of the fast device used in the cache'
complete -c cache_metadata_size -l max-hint-width -d 'Specify hint width'

