# cache_dump
# Autogenerated from man page /usr/share/man/man8/cache_dump.8.gz
complete -c cache_dump -s h -l help -d 'Print help and exit'
complete -c cache_dump -s V -l version -d 'Print version information and exit'
complete -c cache_dump -s r -l repair -d 'Repair the metadata whilst dumping it'
complete -c cache_dump -s o -d 'Specify an output file for the xml, rather than printing to stdout'

