# cameratopam
# Autogenerated from man page /usr/share/man/man1/cameratopam.1.gz
complete -c cameratopam -o identify_only -d 'Report to Standard Error the format of the input image but don\'t generate an …'
complete -c cameratopam -o verbose -d 'Report to Standard Error details of the processing'
complete -c cameratopam -o quick_interpolate -d 'Use simple bilinear interpolation for quick results'
complete -c cameratopam -o half_size -d 'Half-size the output image'
complete -c cameratopam -o four_color_rgb -d 'Interpolate RGB as four colors'
complete -c cameratopam -o document_mode -d 'Show the raw data as a grayscale image with no interpolation'
complete -c cameratopam -o balance_auto -d 'Automatic color balance'
complete -c cameratopam -o balance_camera -d 'Use the color balance specified by the camera'
complete -c cameratopam -o blue_scalefloat -d 'Further adjust the color balance by multiplying the red and blue channels by …'
complete -c cameratopam -o brightness -d 'Change the output brightness.   Default is 1. 0'
complete -c cameratopam -o no_clip_color -d 'By default, cameratoapm clips all colors to prevent pink hues in the highligh…'
complete -c cameratopam -o rgb -d 'Write raw camera colors to the output file'
complete -c cameratopam -o secondary -d 'For cameras based on the Fuji Super CCD SR, this option causes cameratopam to…'
complete -c cameratopam -o linear -d 'This option causes cameratopam to generate a variation on PAM that has \'linea…'
complete -c cameratopam -o red_scale

