# cargo-build
# Autogenerated from man page /usr/share/man/man1/cargo-build.1.gz
complete -c cargo-build -l manifest-path -d 'the workspaces default members are selected, otherwise only the package defin…'
complete -c cargo-build -l workspace
complete -c cargo-build -s p
complete -c cargo-build -l package
complete -c cargo-build -l all
complete -c cargo-build -l exclude
complete -c cargo-build -l lib
complete -c cargo-build -l bin
complete -c cargo-build -l bins
complete -c cargo-build -l example
complete -c cargo-build -l examples
complete -c cargo-build -l test
complete -c cargo-build -l tests
complete -c cargo-build -l bench
complete -c cargo-build -l benches
complete -c cargo-build -l all-targets
complete -c cargo-build -l features
complete -c cargo-build -l all-features
complete -c cargo-build -l no-default-features
complete -c cargo-build -l target
complete -c cargo-build -s r
complete -c cargo-build -l release
complete -c cargo-build -l profile
complete -c cargo-build -l ignore-rust-version
complete -c cargo-build -l target-dir
complete -c cargo-build -l out-dir
complete -c cargo-build -s v
complete -c cargo-build -l verbose
complete -c cargo-build -s q
complete -c cargo-build -l quiet
complete -c cargo-build -l color
complete -c cargo-build -l message-format
complete -c cargo-build -l build-plan
complete -c cargo-build -l frozen
complete -c cargo-build -l locked
complete -c cargo-build -l offline
complete -c cargo-build -s h
complete -c cargo-build -l help
complete -c cargo-build -s Z
complete -c cargo-build -s j
complete -c cargo-build -l jobs
complete -c cargo-build -l future-incompat-report

