# cargo-tree
# Autogenerated from man page /usr/share/man/man1/cargo-tree.1.gz
complete -c cargo-tree -s i
complete -c cargo-tree -l invert
complete -c cargo-tree -l prune
complete -c cargo-tree -l depth
complete -c cargo-tree -l no-dedupe
complete -c cargo-tree -s d
complete -c cargo-tree -l duplicates
complete -c cargo-tree -s e
complete -c cargo-tree -l edges
complete -c cargo-tree -l target
complete -c cargo-tree -l charset
complete -c cargo-tree -s f
complete -c cargo-tree -l format
complete -c cargo-tree -l prefix
complete -c cargo-tree -l manifest-path -d 'the workspaces default members are selected, otherwise only the package defin…'
complete -c cargo-tree -l workspace
complete -c cargo-tree -s p
complete -c cargo-tree -l package
complete -c cargo-tree -l exclude
complete -c cargo-tree -l frozen
complete -c cargo-tree -l locked
complete -c cargo-tree -l offline
complete -c cargo-tree -l features
complete -c cargo-tree -l all-features
complete -c cargo-tree -l no-default-features
complete -c cargo-tree -s v
complete -c cargo-tree -l verbose
complete -c cargo-tree -s q
complete -c cargo-tree -l quiet
complete -c cargo-tree -l color
complete -c cargo-tree -s h
complete -c cargo-tree -l help
complete -c cargo-tree -s Z

