# cargo-fetch
# Autogenerated from man page /usr/share/man/man1/cargo-fetch.1.gz
complete -c cargo-fetch -l target
complete -c cargo-fetch -s v
complete -c cargo-fetch -l verbose
complete -c cargo-fetch -s q
complete -c cargo-fetch -l quiet
complete -c cargo-fetch -l color
complete -c cargo-fetch -l manifest-path
complete -c cargo-fetch -l frozen
complete -c cargo-fetch -l locked
complete -c cargo-fetch -l offline
complete -c cargo-fetch -s h
complete -c cargo-fetch -l help
complete -c cargo-fetch -s Z

