# cargo-fix
# Autogenerated from man page /usr/share/man/man1/cargo-fix.1.gz
complete -c cargo-fix -l broken-code
complete -c cargo-fix -l edition
complete -c cargo-fix -l edition-idioms
complete -c cargo-fix -l allow-no-vcs
complete -c cargo-fix -l allow-dirty
complete -c cargo-fix -l allow-staged
complete -c cargo-fix -l manifest-path -d 'the workspaces default members are selected, otherwise only the package defin…'
complete -c cargo-fix -l workspace
complete -c cargo-fix -s p
complete -c cargo-fix -l package
complete -c cargo-fix -l all
complete -c cargo-fix -l exclude
complete -c cargo-fix -l lib
complete -c cargo-fix -l bin
complete -c cargo-fix -l bins
complete -c cargo-fix -l example
complete -c cargo-fix -l examples
complete -c cargo-fix -l test
complete -c cargo-fix -l tests
complete -c cargo-fix -l bench
complete -c cargo-fix -l benches
complete -c cargo-fix -l all-targets
complete -c cargo-fix -l features
complete -c cargo-fix -l all-features
complete -c cargo-fix -l no-default-features
complete -c cargo-fix -l target
complete -c cargo-fix -s r
complete -c cargo-fix -l release
complete -c cargo-fix -l profile
complete -c cargo-fix -l ignore-rust-version
complete -c cargo-fix -l target-dir
complete -c cargo-fix -s v
complete -c cargo-fix -l verbose
complete -c cargo-fix -s q
complete -c cargo-fix -l quiet
complete -c cargo-fix -l color
complete -c cargo-fix -l message-format
complete -c cargo-fix -l frozen
complete -c cargo-fix -l locked
complete -c cargo-fix -l offline
complete -c cargo-fix -s h
complete -c cargo-fix -l help
complete -c cargo-fix -s Z
complete -c cargo-fix -s j
complete -c cargo-fix -l jobs

