# cargo-check
# Autogenerated from man page /usr/share/man/man1/cargo-check.1.gz
complete -c cargo-check -l manifest-path -d 'the workspaces default members are selected, otherwise only the package defin…'
complete -c cargo-check -l workspace
complete -c cargo-check -s p
complete -c cargo-check -l package
complete -c cargo-check -l all
complete -c cargo-check -l exclude
complete -c cargo-check -l lib
complete -c cargo-check -l bin
complete -c cargo-check -l bins
complete -c cargo-check -l example
complete -c cargo-check -l examples
complete -c cargo-check -l test
complete -c cargo-check -l tests
complete -c cargo-check -l bench
complete -c cargo-check -l benches
complete -c cargo-check -l all-targets
complete -c cargo-check -l features
complete -c cargo-check -l all-features
complete -c cargo-check -l no-default-features
complete -c cargo-check -l target
complete -c cargo-check -s r
complete -c cargo-check -l release
complete -c cargo-check -l profile
complete -c cargo-check -l ignore-rust-version
complete -c cargo-check -l target-dir
complete -c cargo-check -s v
complete -c cargo-check -l verbose
complete -c cargo-check -s q
complete -c cargo-check -l quiet
complete -c cargo-check -l color
complete -c cargo-check -l message-format
complete -c cargo-check -l frozen
complete -c cargo-check -l locked
complete -c cargo-check -l offline
complete -c cargo-check -s h
complete -c cargo-check -l help
complete -c cargo-check -s Z
complete -c cargo-check -s j
complete -c cargo-check -l jobs
complete -c cargo-check -l future-incompat-report

