# cargo-vendor
# Autogenerated from man page /usr/share/man/man1/cargo-vendor.1.gz
complete -c cargo-vendor -s s
complete -c cargo-vendor -l sync
complete -c cargo-vendor -l no-delete
complete -c cargo-vendor -l respect-source-config
complete -c cargo-vendor -l versioned-dirs
complete -c cargo-vendor -l manifest-path
complete -c cargo-vendor -l frozen
complete -c cargo-vendor -l locked
complete -c cargo-vendor -l offline
complete -c cargo-vendor -s v
complete -c cargo-vendor -l verbose
complete -c cargo-vendor -s q
complete -c cargo-vendor -l quiet
complete -c cargo-vendor -l color
complete -c cargo-vendor -s h
complete -c cargo-vendor -l help
complete -c cargo-vendor -s Z

