# cargo-new
# Autogenerated from man page /usr/share/man/man1/cargo-new.1.gz
complete -c cargo-new -l bin
complete -c cargo-new -l lib
complete -c cargo-new -l edition
complete -c cargo-new -l name
complete -c cargo-new -l vcs
complete -c cargo-new -l registry
complete -c cargo-new -s v
complete -c cargo-new -l verbose
complete -c cargo-new -s q
complete -c cargo-new -l quiet
complete -c cargo-new -l color
complete -c cargo-new -s h
complete -c cargo-new -l help
complete -c cargo-new -s Z

