# cargo-verify-project
# Autogenerated from man page /usr/share/man/man1/cargo-verify-project.1.gz
complete -c cargo-verify-project -s v
complete -c cargo-verify-project -l verbose
complete -c cargo-verify-project -s q
complete -c cargo-verify-project -l quiet
complete -c cargo-verify-project -l color
complete -c cargo-verify-project -l manifest-path
complete -c cargo-verify-project -l frozen
complete -c cargo-verify-project -l locked
complete -c cargo-verify-project -l offline
complete -c cargo-verify-project -s h
complete -c cargo-verify-project -l help
complete -c cargo-verify-project -s Z

