# cargo-clean
# Autogenerated from man page /usr/share/man/man1/cargo-clean.1.gz
complete -c cargo-clean -s p
complete -c cargo-clean -l package
complete -c cargo-clean -l doc
complete -c cargo-clean -l release
complete -c cargo-clean -l profile
complete -c cargo-clean -l target-dir
complete -c cargo-clean -l target
complete -c cargo-clean -s v
complete -c cargo-clean -l verbose
complete -c cargo-clean -s q
complete -c cargo-clean -l quiet
complete -c cargo-clean -l color
complete -c cargo-clean -l manifest-path
complete -c cargo-clean -l frozen
complete -c cargo-clean -l locked
complete -c cargo-clean -l offline
complete -c cargo-clean -s h
complete -c cargo-clean -l help
complete -c cargo-clean -s Z

