# cargo
# Autogenerated from man page /usr/share/man/man1/cargo.1.gz
complete -c cargo -s V
complete -c cargo -l version
complete -c cargo -l list
complete -c cargo -l explain
complete -c cargo -s v
complete -c cargo -l verbose
complete -c cargo -s q
complete -c cargo -l quiet
complete -c cargo -l color
complete -c cargo -l frozen
complete -c cargo -l locked
complete -c cargo -l offline
complete -c cargo -s h
complete -c cargo -l help
complete -c cargo -s Z

