# cargo-pkgid
# Autogenerated from man page /usr/share/man/man1/cargo-pkgid.1.gz
complete -c cargo-pkgid -s p
complete -c cargo-pkgid -l package
complete -c cargo-pkgid -s v
complete -c cargo-pkgid -l verbose
complete -c cargo-pkgid -s q
complete -c cargo-pkgid -l quiet
complete -c cargo-pkgid -l color
complete -c cargo-pkgid -l manifest-path
complete -c cargo-pkgid -l frozen
complete -c cargo-pkgid -l locked
complete -c cargo-pkgid -l offline
complete -c cargo-pkgid -s h
complete -c cargo-pkgid -l help
complete -c cargo-pkgid -s Z

