# cargo-package
# Autogenerated from man page /usr/share/man/man1/cargo-package.1.gz
complete -c cargo-package -l allow-dirty -d ' 3. Extract the . crate file and build it to verify it can build'
complete -c cargo-package -s l
complete -c cargo-package -l list
complete -c cargo-package -l no-verify
complete -c cargo-package -l no-metadata
complete -c cargo-package -l manifest-path -d 'the workspaces default members are selected, otherwise only the package defin…'
complete -c cargo-package -l workspace
complete -c cargo-package -s p
complete -c cargo-package -l package
complete -c cargo-package -l exclude
complete -c cargo-package -l target
complete -c cargo-package -l target-dir
complete -c cargo-package -l features
complete -c cargo-package -l all-features
complete -c cargo-package -l no-default-features
complete -c cargo-package -l frozen
complete -c cargo-package -l locked
complete -c cargo-package -l offline
complete -c cargo-package -s j
complete -c cargo-package -l jobs
complete -c cargo-package -s v
complete -c cargo-package -l verbose
complete -c cargo-package -s q
complete -c cargo-package -l quiet
complete -c cargo-package -l color
complete -c cargo-package -s h
complete -c cargo-package -l help
complete -c cargo-package -s Z

