# cargo-publish
# Autogenerated from man page /usr/share/man/man1/cargo-publish.1.gz
complete -c cargo-publish -l dry-run
complete -c cargo-publish -l token
complete -c cargo-publish -l no-verify
complete -c cargo-publish -l allow-dirty
complete -c cargo-publish -l index
complete -c cargo-publish -l registry
complete -c cargo-publish -s p
complete -c cargo-publish -l package
complete -c cargo-publish -l target
complete -c cargo-publish -l target-dir
complete -c cargo-publish -l features
complete -c cargo-publish -l all-features
complete -c cargo-publish -l no-default-features
complete -c cargo-publish -l manifest-path
complete -c cargo-publish -l frozen
complete -c cargo-publish -l locked
complete -c cargo-publish -l offline
complete -c cargo-publish -s j
complete -c cargo-publish -l jobs
complete -c cargo-publish -s v
complete -c cargo-publish -l verbose
complete -c cargo-publish -s q
complete -c cargo-publish -l quiet
complete -c cargo-publish -l color
complete -c cargo-publish -s h
complete -c cargo-publish -l help
complete -c cargo-publish -s Z

