# cargo-init
# Autogenerated from man page /usr/share/man/man1/cargo-init.1.gz
complete -c cargo-init -l bin
complete -c cargo-init -l lib
complete -c cargo-init -l edition
complete -c cargo-init -l name
complete -c cargo-init -l vcs
complete -c cargo-init -l registry
complete -c cargo-init -s v
complete -c cargo-init -l verbose
complete -c cargo-init -s q
complete -c cargo-init -l quiet
complete -c cargo-init -l color
complete -c cargo-init -s h
complete -c cargo-init -l help
complete -c cargo-init -s Z

