# cargo-owner
# Autogenerated from man page /usr/share/man/man1/cargo-owner.1.gz
complete -c cargo-owner -s a
complete -c cargo-owner -l add
complete -c cargo-owner -s r
complete -c cargo-owner -l remove
complete -c cargo-owner -s l
complete -c cargo-owner -l list
complete -c cargo-owner -l token
complete -c cargo-owner -l index
complete -c cargo-owner -l registry
complete -c cargo-owner -s v
complete -c cargo-owner -l verbose
complete -c cargo-owner -s q
complete -c cargo-owner -l quiet
complete -c cargo-owner -l color
complete -c cargo-owner -s h
complete -c cargo-owner -l help
complete -c cargo-owner -s Z

