# cargo-metadata
# Autogenerated from man page /usr/share/man/man1/cargo-metadata.1.gz
complete -c cargo-metadata -l no-deps
complete -c cargo-metadata -l format-version
complete -c cargo-metadata -l filter-platform
complete -c cargo-metadata -l features
complete -c cargo-metadata -l all-features
complete -c cargo-metadata -l no-default-features
complete -c cargo-metadata -s v
complete -c cargo-metadata -l verbose
complete -c cargo-metadata -s q
complete -c cargo-metadata -l quiet
complete -c cargo-metadata -l color
complete -c cargo-metadata -l manifest-path
complete -c cargo-metadata -l frozen
complete -c cargo-metadata -l locked
complete -c cargo-metadata -l offline
complete -c cargo-metadata -s h
complete -c cargo-metadata -l help
complete -c cargo-metadata -s Z

