# cargo-doc
# Autogenerated from man page /usr/share/man/man1/cargo-doc.1.gz
complete -c cargo-doc -l open
complete -c cargo-doc -l no-deps
complete -c cargo-doc -l document-private-items
complete -c cargo-doc -l manifest-path -d 'the workspaces default members are selected, otherwise only the package defin…'
complete -c cargo-doc -l workspace
complete -c cargo-doc -s p
complete -c cargo-doc -l package
complete -c cargo-doc -l all
complete -c cargo-doc -l exclude
complete -c cargo-doc -l lib
complete -c cargo-doc -l bin
complete -c cargo-doc -l bins
complete -c cargo-doc -l example
complete -c cargo-doc -l examples
complete -c cargo-doc -l features
complete -c cargo-doc -l all-features
complete -c cargo-doc -l no-default-features
complete -c cargo-doc -l target
complete -c cargo-doc -s r
complete -c cargo-doc -l release
complete -c cargo-doc -l profile
complete -c cargo-doc -l ignore-rust-version
complete -c cargo-doc -l target-dir
complete -c cargo-doc -s v
complete -c cargo-doc -l verbose
complete -c cargo-doc -s q
complete -c cargo-doc -l quiet
complete -c cargo-doc -l color
complete -c cargo-doc -l message-format
complete -c cargo-doc -l frozen
complete -c cargo-doc -l locked
complete -c cargo-doc -l offline
complete -c cargo-doc -s h
complete -c cargo-doc -l help
complete -c cargo-doc -s Z
complete -c cargo-doc -s j
complete -c cargo-doc -l jobs

