# cargo-uninstall
# Autogenerated from man page /usr/share/man/man1/cargo-uninstall.1.gz
complete -c cargo-uninstall -l example
complete -c cargo-uninstall -s p
complete -c cargo-uninstall -l package
complete -c cargo-uninstall -l bin
complete -c cargo-uninstall -l root
complete -c cargo-uninstall -s v
complete -c cargo-uninstall -l verbose
complete -c cargo-uninstall -s q
complete -c cargo-uninstall -l quiet
complete -c cargo-uninstall -l color
complete -c cargo-uninstall -s h
complete -c cargo-uninstall -l help
complete -c cargo-uninstall -s Z

