# cargo-search
# Autogenerated from man page /usr/share/man/man1/cargo-search.1.gz
complete -c cargo-search -l limit
complete -c cargo-search -l index
complete -c cargo-search -l registry
complete -c cargo-search -s v
complete -c cargo-search -l verbose
complete -c cargo-search -s q
complete -c cargo-search -l quiet
complete -c cargo-search -l color
complete -c cargo-search -s h
complete -c cargo-search -l help
complete -c cargo-search -s Z

