# cargo-test
# Autogenerated from man page /usr/share/man/man1/cargo-test.1.gz
complete -c cargo-test -l no-run
complete -c cargo-test -l no-fail-fast
complete -c cargo-test -l manifest-path -d 'the workspaces default members are selected, otherwise only the package defin…'
complete -c cargo-test -l workspace
complete -c cargo-test -s p
complete -c cargo-test -l package
complete -c cargo-test -l all
complete -c cargo-test -l exclude
complete -c cargo-test -l lib
complete -c cargo-test -l bin
complete -c cargo-test -l bins
complete -c cargo-test -l example
complete -c cargo-test -l examples
complete -c cargo-test -l test
complete -c cargo-test -l tests
complete -c cargo-test -l bench
complete -c cargo-test -l benches
complete -c cargo-test -l all-targets
complete -c cargo-test -l doc
complete -c cargo-test -l features
complete -c cargo-test -l all-features
complete -c cargo-test -l no-default-features
complete -c cargo-test -l target
complete -c cargo-test -s r
complete -c cargo-test -l release
complete -c cargo-test -l profile
complete -c cargo-test -l ignore-rust-version
complete -c cargo-test -l target-dir
complete -c cargo-test -l nocapture -d 'cargo test -- --nocapture'
complete -c cargo-test -s v
complete -c cargo-test -l verbose
complete -c cargo-test -s q
complete -c cargo-test -l quiet
complete -c cargo-test -l color
complete -c cargo-test -l message-format
complete -c cargo-test -l frozen
complete -c cargo-test -l locked
complete -c cargo-test -l offline
complete -c cargo-test -s h
complete -c cargo-test -l help
complete -c cargo-test -s Z
complete -c cargo-test -s j
complete -c cargo-test -l jobs
complete -c cargo-test -l future-incompat-report

