# cargo-generate-lockfile
# Autogenerated from man page /usr/share/man/man1/cargo-generate-lockfile.1.gz
complete -c cargo-generate-lockfile -s v
complete -c cargo-generate-lockfile -l verbose
complete -c cargo-generate-lockfile -s q
complete -c cargo-generate-lockfile -l quiet
complete -c cargo-generate-lockfile -l color
complete -c cargo-generate-lockfile -l manifest-path
complete -c cargo-generate-lockfile -l frozen
complete -c cargo-generate-lockfile -l locked
complete -c cargo-generate-lockfile -l offline
complete -c cargo-generate-lockfile -s h
complete -c cargo-generate-lockfile -l help
complete -c cargo-generate-lockfile -s Z

