# cargo-run
# Autogenerated from man page /usr/share/man/man1/cargo-run.1.gz
complete -c cargo-run -s p
complete -c cargo-run -l package
complete -c cargo-run -l bin
complete -c cargo-run -l example
complete -c cargo-run -l features
complete -c cargo-run -l all-features
complete -c cargo-run -l no-default-features
complete -c cargo-run -l target
complete -c cargo-run -s r
complete -c cargo-run -l release
complete -c cargo-run -l profile
complete -c cargo-run -l ignore-rust-version
complete -c cargo-run -l target-dir
complete -c cargo-run -s v
complete -c cargo-run -l verbose
complete -c cargo-run -s q
complete -c cargo-run -l quiet
complete -c cargo-run -l color
complete -c cargo-run -l message-format
complete -c cargo-run -l manifest-path
complete -c cargo-run -l frozen
complete -c cargo-run -l locked
complete -c cargo-run -l offline
complete -c cargo-run -s h
complete -c cargo-run -l help
complete -c cargo-run -s Z
complete -c cargo-run -s j
complete -c cargo-run -l jobs

