# cargo-update
# Autogenerated from man page /usr/share/man/man1/cargo-update.1.gz
complete -c cargo-update -s p
complete -c cargo-update -l package
complete -c cargo-update -l aggressive
complete -c cargo-update -l precise
complete -c cargo-update -s w
complete -c cargo-update -l workspace
complete -c cargo-update -l dry-run
complete -c cargo-update -s v
complete -c cargo-update -l verbose
complete -c cargo-update -s q
complete -c cargo-update -l quiet
complete -c cargo-update -l color
complete -c cargo-update -l manifest-path
complete -c cargo-update -l frozen
complete -c cargo-update -l locked
complete -c cargo-update -l offline
complete -c cargo-update -s h
complete -c cargo-update -l help
complete -c cargo-update -s Z

