# ccomps
# Autogenerated from man page /usr/share/man/man1/ccomps.1.gz
complete -c ccomps -s e -d 'Do not induce edges in the connected components'
complete -c ccomps -s s -d 'No output graph is printed'
complete -c ccomps -s x -d 'Only the connected components are printed, as separate graphs'
complete -c ccomps -s v -d 'Counts of nodes, edges and connected components are printed'
complete -c ccomps -s z -d 'Sort components by size, with the largest first'
complete -c ccomps -s C -d 'Use clusters in computing components in addition to normal edge connectivity'
complete -c ccomps -s n -d 'Do not project subgraph structure'
complete -c ccomps -s X -d 'Prints only the component containing the node node_name, if any'
complete -c ccomps -o 'X#' -d 'Prints only components in the given range of indices'
complete -c ccomps -o 'X%' -d 'Prints only components in the given range of sizes'
complete -c ccomps -s o -d 'If specified, each graph will be written to a different file with the names d…'

