# checkupdates
# Autogenerated from man page /usr/share/man/man8/checkupdates.8.gz
complete -c checkupdates -s d -l download -d 'Download any pending updates to the pacman cache'
complete -c checkupdates -s h -l help -d 'Display syntax and command line options'

