# chem
# Autogenerated from man page /usr/share/man/man1/chem.1.gz
complete -c chem -s h -d and
complete -c chem -l help -d 'display a usage message, whereas'
complete -c chem -s v -d and
complete -c chem -l version -d 'display version information; all exit'
complete -c chem -s p -d 'for the activation of pic : chem [file ] | groff -p  THE LANGUAGE The chem in…'

