# circo
# Autogenerated from man page /usr/share/man/man1/circo.1.gz
complete -c circo -o Tdot
complete -c circo -o Txdot
complete -c circo -o Tps
complete -c circo -o Tpdf
complete -c circo -o Tsvg -o Tsvgz
complete -c circo -o Tfig
complete -c circo -o Tpng
complete -c circo -o Tgif
complete -c circo -o Tjpg -o Tjpeg
complete -c circo -o Tjson
complete -c circo -o Timap -d 'that has a non-null href attribute. ),'
complete -c circo -o Tcmapx
complete -c circo -s G
complete -c circo -s N
complete -c circo -s E -d 'Example: -Gsize="7,8" -Nshape=box -Efontsize=8'
complete -c circo -o lfile -d 'Usually these define custom shapes or styles'
complete -c circo -o Tlang
complete -c circo -o 'n[1' -d 'If set, neato assumes nodes have already been positioned and all nodes have a…'
complete -c circo -o Klayout
complete -c circo -s O -s T
complete -c circo -s P
complete -c circo -s v
complete -c circo -s c
complete -c circo -o qlevel
complete -c circo -o sfscale
complete -c circo -s y
complete -c circo -o ofile
complete -c circo -s x
complete -c circo -o Lg
complete -c circo -o LO
complete -c circo -o Lni
complete -c circo -o LUi
complete -c circo -o LCv
complete -c circo -o LTv
complete -c circo -s V
complete -c circo -s '?'

