# crl2pkcs7
# Autogenerated from man page /usr/share/man/man1/crl2pkcs7.1ssl.gz
complete -c crl2pkcs7 -o help -d 'Print out a usage message'
complete -c crl2pkcs7 -o inform -d 'This specifies the \\s-1CRL\\s0 input format'
complete -c crl2pkcs7 -o outform -d 'This specifies the PKCS#7 structure output format'
complete -c crl2pkcs7 -o in -d 'This specifies the input filename to read a \\s-1CRL\\s0 from or standard input…'
complete -c crl2pkcs7 -o out -d 'Specifies the output filename to write the PKCS#7 structure to or standard ou…'
complete -c crl2pkcs7 -o certfile -d 'Specifies a filename containing one or more certificates in \\s-1PEM\\s0 format'

