# cxl-list
# Autogenerated from man page /usr/share/man/man1/cxl-list.1.gz
complete -c cxl-list -s m -l memdev
complete -c cxl-list -s M -l memdevs
complete -c cxl-list -s i -l idle
complete -c cxl-list -s H -l health
complete -c cxl-list -s u -l human
complete -c cxl-list -s v -l verbose

