# cxl-zero-labels
# Autogenerated from man page /usr/share/man/man1/cxl-zero-labels.1.gz
complete -c cxl-zero-labels -s s -l size
complete -c cxl-zero-labels -s O -l offset
complete -c cxl-zero-labels -s v

