# cxl-read-labels
# Autogenerated from man page /usr/share/man/man1/cxl-read-labels.1.gz
complete -c cxl-read-labels -s s -l size
complete -c cxl-read-labels -s O -l offset
complete -c cxl-read-labels -s v
complete -c cxl-read-labels -s o -l output

