# daxctl-offline-memory
# Autogenerated from man page /usr/share/man/man1/daxctl-offline-memory.1.gz
complete -c daxctl-offline-memory -s r -l region
complete -c daxctl-offline-memory -s u -l human
complete -c daxctl-offline-memory -s v -l verbose

