# daxctl-disable-device
# Autogenerated from man page /usr/share/man/man1/daxctl-disable-device.1.gz
complete -c daxctl-disable-device -s r -l region
complete -c daxctl-disable-device -s u -l human
complete -c daxctl-disable-device -s v -l verbose

