# daxctl-destroy-device
# Autogenerated from man page /usr/share/man/man1/daxctl-destroy-device.1.gz
complete -c daxctl-destroy-device -s r -l region
complete -c daxctl-destroy-device -s u -l human
complete -c daxctl-destroy-device -s v -l verbose

