# daxctl-enable-device
# Autogenerated from man page /usr/share/man/man1/daxctl-enable-device.1.gz
complete -c daxctl-enable-device -s r -l region
complete -c daxctl-enable-device -s u -l human
complete -c daxctl-enable-device -s v -l verbose

