# daxctl-list
# Autogenerated from man page /usr/share/man/man1/daxctl-list.1.gz
complete -c daxctl-list -s r -l region
complete -c daxctl-list -s d -l dev
complete -c daxctl-list -s D -l devices
complete -c daxctl-list -s M -l mappings
complete -c daxctl-list -s R -l regions
complete -c daxctl-list -s i -l idle
complete -c daxctl-list -s u -l human

