# daxctl-create-device
# Autogenerated from man page /usr/share/man/man1/daxctl-create-device.1.gz
complete -c daxctl-create-device -s r -l region
complete -c daxctl-create-device -s s -l size
complete -c daxctl-create-device -s a -l align
complete -c daxctl-create-device -l input
complete -c daxctl-create-device -s u -l human
complete -c daxctl-create-device -s v -l verbose

