# daxctl-reconfigure-device
# Autogenerated from man page /usr/share/man/man1/daxctl-reconfigure-device.1.gz
complete -c daxctl-reconfigure-device -s r -l region
complete -c daxctl-reconfigure-device -s s -l size
complete -c daxctl-reconfigure-device -s a -l align
complete -c daxctl-reconfigure-device -s m -l mode
complete -c daxctl-reconfigure-device -s N -l no-online
complete -c daxctl-reconfigure-device -s C -l check-config
complete -c daxctl-reconfigure-device -l no-movable
complete -c daxctl-reconfigure-device -l movable -d 'memory such that it is not movable'
complete -c daxctl-reconfigure-device -s f -l force -d 'oc When converting from "system-ram" mode to "devdax", it is expected that al…'
complete -c daxctl-reconfigure-device -s u -l human
complete -c daxctl-reconfigure-device -s v -l verbose

