# daxctl-online-memory
# Autogenerated from man page /usr/share/man/man1/daxctl-online-memory.1.gz
complete -c daxctl-online-memory -s r -l region
complete -c daxctl-online-memory -l no-movable
complete -c daxctl-online-memory -l movable -d 'memory such that it is not movable'
complete -c daxctl-online-memory -s u -l human
complete -c daxctl-online-memory -s v -l verbose

