# dconf-editor
# Autogenerated from man page /usr/share/man/man1/dconf-editor.1.gz
complete -c dconf-editor -s h -l help -d 'Prints the command-line options and exits'
complete -c dconf-editor -s v -l version -d 'Prints the release version and exits'
complete -c dconf-editor -l list-relocatable-schemas -d 'Prints the list of relocatable schemas and exits'

