# delaunay
# Autogenerated from man page /usr/share/man/man1/delaunay.1.gz
complete -c delaunay -s b -l hull -d 'Do not keep convex hull'
complete -c delaunay -s e -l noconst -d 'Do not add constrained edges'
complete -c delaunay -s S -l split -d 'Split constraints (experimental)'
complete -c delaunay -s H -l holes -d 'Remove holes from the triangulation'
complete -c delaunay -s d -l duplicates -d 'Remove duplicate vertices'
complete -c delaunay -s r -l randomize -d 'Shuffle input vertex list'
complete -c delaunay -s c -l check -d 'Check Delaunay property'
complete -c delaunay -s f -l files -d 'Generate evolution files'
complete -c delaunay -s o -l conform -d 'Generate conforming triangulation'
complete -c delaunay -s s -l steiner -d 'Maximum number of Steiner points for conforming triangulation (default is no …'
complete -c delaunay -s q -l quality -d 'Set the minimum acceptable face quality'
complete -c delaunay -s a -l area -d 'Set the maximum acceptable face area'
complete -c delaunay -s v -l verbose -d 'Print statistics about the triangulation'
complete -c delaunay -s h -l help -d 'Display the help and exit'

