# dhcp_release6
# Autogenerated from man page /usr/share/man/man1/dhcp_release6.1.gz
complete -c dhcp_release6 -s a -l ip -d 'IPv6 address to release'
complete -c dhcp_release6 -s c -l client-id -d 'Colon-separated hex string representing DHCPv6 client id'
complete -c dhcp_release6 -s d -l dry-run -d 'Print hexadecimal representation of generated DHCPv6 release packet to standa…'
complete -c dhcp_release6 -s h -l help -d 'print usage information to standard output and exit'
complete -c dhcp_release6 -s i -l iaid -d 'Decimal representation of DHCPv6 IAID'
complete -c dhcp_release6 -s n -l iface -d 'Network interface to send a DHCPv6 release packet from'
complete -c dhcp_release6 -s s -l server-id -d 'Colon-separated hex string representing DHCPv6 server id'

