# dmevent_tool
# Autogenerated from man page /usr/share/man/man8/dmevent_tool.8.gz
complete -c dmevent_tool -s V
complete -c dmevent_tool -o 'm[r' -d '        and their current status with dmeventd         for registered (-r)/un…'
complete -c dmevent_tool -o 'a[r' -s m -d '            Syntax: dmevent_tool -a[u|r]'
complete -c dmevent_tool -s r -d '            Syntax: dmevent_tool -r <device name> <path to DSO library>      …'
complete -c dmevent_tool -s u -d '            Syntax: dmevent_tool -u <device name> [<path to DSO library>]    …'

