# dot
# Autogenerated from man page /usr/share/man/man1/dot.1.gz
complete -c dot -o Tdot
complete -c dot -o Txdot
complete -c dot -o Tps
complete -c dot -o Tpdf
complete -c dot -o Tsvg -o Tsvgz
complete -c dot -o Tfig
complete -c dot -o Tpng
complete -c dot -o Tgif
complete -c dot -o Tjpg -o Tjpeg
complete -c dot -o Tjson
complete -c dot -o Timap -d 'that has a non-null href attribute. ),'
complete -c dot -o Tcmapx
complete -c dot -s G
complete -c dot -s N
complete -c dot -s E -d 'Example: -Gsize="7,8" -Nshape=box -Efontsize=8'
complete -c dot -o lfile -d 'Usually these define custom shapes or styles'
complete -c dot -o Tlang
complete -c dot -o 'n[1' -d 'If set, neato assumes nodes have already been positioned and all nodes have a…'
complete -c dot -o Klayout
complete -c dot -s O -s T
complete -c dot -s P
complete -c dot -s v
complete -c dot -s c
complete -c dot -o qlevel
complete -c dot -o sfscale
complete -c dot -s y
complete -c dot -o ofile
complete -c dot -s x
complete -c dot -o Lg
complete -c dot -o LO
complete -c dot -o Lni
complete -c dot -o LUi
complete -c dot -o LCv
complete -c dot -o LTv
complete -c dot -s V
complete -c dot -s '?'

