# dsa
# Autogenerated from man page /usr/share/man/man1/dsa.1ssl.gz
complete -c dsa -o help -d 'Print out a usage message'
complete -c dsa -o inform -d 'This specifies the input format'
complete -c dsa -o outform -d 'This specifies the output format, the options have the same meaning and defau…'
complete -c dsa -o in -d 'This specifies the input filename to read a key from or standard input if thi…'
complete -c dsa -o passin -d 'The input file password source'
complete -c dsa -o out -d 'This specifies the output filename to write a key to or standard output by is…'
complete -c dsa -o passout -d 'The output file password source'
complete -c dsa -o aes128 -o aes192 -o aes256 -o aria128 -o aria192 -o aria256 -o camellia128 -o camellia192 -o camellia256 -o des -o des3 -o idea -d 'These options encrypt the private key with the specified cipher before output…'
complete -c dsa -o text -d 'Prints out the public, private key components and parameters'
complete -c dsa -o noout -d 'This option prevents output of the encoded version of the key'
complete -c dsa -o modulus -d 'This option prints out the value of the public key component of the key'
complete -c dsa -o pubin -d 'By default, a private key is read from the input file'
complete -c dsa -o pubout -d 'By default, a private key is output'

