# dvconnect
# Autogenerated from man page /usr/share/man/man1/dvconnect.1.gz
complete -c dvconnect -l version -d 'show dvconnect version number'
complete -c dvconnect -s s -l send -d 'send data instead of capturing'
complete -c dvconnect -s v -l verbose -d 'show status information while receiving / sending'
complete -c dvconnect -s c -l channel -d 'channel to send / receive on (range: 0 - 63, default = 63)'
complete -c dvconnect -s k -l kbuffers -d 'number of kernel video1394 frame buffers to use.  default = 8'
complete -c dvconnect -l start-frame -d 'start at count frame (defaults to 0)'
complete -c dvconnect -s e -l end-frame -d 'end at count frame (defaults to unlimited)'
complete -c dvconnect -l cip-n-ntsc -d 'cip n ntsc timing counter (default: 2436)'
complete -c dvconnect -l cip-d-ntsc -d 'cip d ntsc timing counter (default: 38400)'
complete -c dvconnect -l syt-offset -d 'syt offset (default: 10000 range: 10000-26000)'
complete -c dvconnect -s b -l buffers -d 'max number of file io thread buffers to use.  default = 250'
complete -c dvconnect -s u -l underrun-data -d 'file with the frame to send in case of underruns'
complete -c dvconnect -s d -l device -d 'Specify the video1394 device (default /dev/video1394/0). PP Help Options'
complete -c dvconnect -s '?' -l help -d 'Show help message'
complete -c dvconnect -l usage -d 'Display brief usage message.  SEE ALSO playdv (1), dubdv (1), encodedv (1)'

