# ec
# Autogenerated from man page /usr/share/man/man1/ec.1ssl.gz
complete -c ec -o help -d 'Print out a usage message'
complete -c ec -o inform -d 'This specifies the input format'
complete -c ec -o outform -d 'This specifies the output format, the options have the same meaning and defau…'
complete -c ec -o in -d 'This specifies the input filename to read a key from or standard input if thi…'
complete -c ec -o passin -d 'The input file password source'
complete -c ec -o out -d 'This specifies the output filename to write a key to or standard output by is…'
complete -c ec -o passout -d 'The output file password source'
complete -c ec -o des -o des3 -o idea -d 'These options encrypt the private key with the \\s-1DES,\\s0 triple \\s-1DES, ID…'
complete -c ec -o text -d 'Prints out the public, private key components and parameters'
complete -c ec -o noout -d 'This option prevents output of the encoded version of the key'
complete -c ec -o pubin -d 'By default, a private key is read from the input file'
complete -c ec -o pubout -d 'By default a private key is output'
complete -c ec -o conv_form -d 'This specifies how the points on the elliptic curve are converted into octet …'
complete -c ec -o param_enc -d 'This specifies how the elliptic curve parameters are encoded'
complete -c ec -o no_public -d 'This option omits the public key components from the private key output'
complete -c ec -o check -d 'This option checks the consistency of an \\s-1EC\\s0 private or public key'

