# edgepaint
# Autogenerated from man page /usr/share/man/man1/edgepaint.1.gz
complete -c edgepaint -l accuracy -d 'Accuracy with which to find the maximally different coloring for each node wi…'
complete -c edgepaint -l angle -d 'Color two edges differently if their incidence angle is less than a degrees'
complete -c edgepaint -l random_seed -d 'Random seed to use.  s must be an integer'
complete -c edgepaint -l lightness -d 'Only applies for the "lab" color scheme: l1 and l2 must integers, with 0 <= l…'
complete -c edgepaint -l share_endpoint -d 'If this option is specified, edges that share a node are not considered in co…'
complete -c edgepaint -s o -d 'Write output to file f (default: stdout)'
complete -c edgepaint -l color_scheme -d 'Specifies the color scheme'
complete -c edgepaint -s v -d 'Turns on verbose mode'
complete -c edgepaint -s '?' -d 'Print usage and exit'

