# eqn2graph
# Autogenerated from man page /usr/share/man/man1/eqn2graph.1.gz
complete -c eqn2graph -o format -d 'Write the image in R output-format , which must be understood by R \\%convert …'
complete -c eqn2graph -l help -d 'Display a usage message and exit'
complete -c eqn2graph -o trim -d 'option to the smallest possible bounding box that contains all the black pixe…'
complete -c eqn2graph -s v
complete -c eqn2graph -l version -d 'Display version information and exit.  ENVIRONMENT %GROFF_TMPDIR'

