# era_invalidate
# Autogenerated from man page /usr/share/man/man8/era_invalidate.8.gz
complete -c era_invalidate -s h -l help -d 'Print help and exit'
complete -c era_invalidate -s V -l version -d 'Print version information and exit'
complete -c era_invalidate -s o -d 'Write output to a file rather than stdout'
complete -c era_invalidate -l metadata-snapshot -d 'Use the metadata snapshot rather than the current superblock'
complete -c era_invalidate -l written-since -d 'Blocks written since the given era will be listed'

