# era_dump
# Autogenerated from man page /usr/share/man/man8/era_dump.8.gz
complete -c era_dump -s h -l help -d 'Print help and exit'
complete -c era_dump -s V -l version -d 'Print version information and exit'
complete -c era_dump -l repair -d 'Repair the metadata whilst dumping it'
complete -c era_dump -l logical -d 'Fold any unprocessed write sets into the final era array'
complete -c era_dump -s o -d 'EXAMPLES Dumps era metadata on logical volume /dev/vg/metadata to standard ou…'

