# extcheck-openjdk8
# Autogenerated from man page /usr/share/man/man1/extcheck-openjdk8.1.gz
complete -c extcheck-openjdk8 -o verbose -d 'br Lists JAR files in the extension directory as they are checked'
complete -c extcheck-openjdk8 -o Joption

