# fdp
# Autogenerated from man page /usr/share/man/man1/fdp.1.gz
complete -c fdp -o Tdot
complete -c fdp -o Txdot
complete -c fdp -o Tps
complete -c fdp -o Tpdf
complete -c fdp -o Tsvg -o Tsvgz
complete -c fdp -o Tfig
complete -c fdp -o Tpng
complete -c fdp -o Tgif
complete -c fdp -o Tjpg -o Tjpeg
complete -c fdp -o Tjson
complete -c fdp -o Timap -d 'that has a non-null href attribute. ),'
complete -c fdp -o Tcmapx
complete -c fdp -s G
complete -c fdp -s N
complete -c fdp -s E -d 'Example: -Gsize="7,8" -Nshape=box -Efontsize=8'
complete -c fdp -o lfile -d 'Usually these define custom shapes or styles'
complete -c fdp -o Tlang
complete -c fdp -o 'n[1' -d 'If set, neato assumes nodes have already been positioned and all nodes have a…'
complete -c fdp -o Klayout
complete -c fdp -s O -s T
complete -c fdp -s P
complete -c fdp -s v
complete -c fdp -s c
complete -c fdp -o qlevel
complete -c fdp -o sfscale
complete -c fdp -s y
complete -c fdp -o ofile
complete -c fdp -s x
complete -c fdp -o Lg
complete -c fdp -o LO
complete -c fdp -o Lni
complete -c fdp -o LUi
complete -c fdp -o LCv
complete -c fdp -o LTv
complete -c fdp -s V
complete -c fdp -s '?'

