# fiascotopnm
# Autogenerated from man page /usr/share/man/man1/fiascotopnm.1.gz
complete -c fiascotopnm -s o -l output -d 'Write decompressed image to the file name. ppm (if PPM) or name. pgm (if PGM)'
complete -c fiascotopnm -s z -l fast -d 'Decompress images in the 4:2:0 format; i. e'
complete -c fiascotopnm -s d -l double -d 'Double the size of the X11 window both in width and height; no pixel interpol…'
complete -c fiascotopnm -s p -l panel -d 'Show a panel with play, stop, pause, record and exit buttons to control the d…'
complete -c fiascotopnm -s m -l magnify -d 'Set magnification of the decompressed image'
complete -c fiascotopnm -s s -l smoothing -d 'Smooth decompressed image(s) along the partitioning borders by the given amou…'
complete -c fiascotopnm -s F -l fps -d 'Set number of frames per second to N'
complete -c fiascotopnm -l verbose -d 'Set verbose of fiascotopnm to N'
complete -c fiascotopnm -s v -l version -d 'Print fiascotopnm version number, then exit'
complete -c fiascotopnm -s f -l config -d 'Load parameter file name to initialize the options of fiascotopnm'
complete -c fiascotopnm -s h -l info -d 'Print brief help, then exit'
complete -c fiascotopnm -s H -l help -d 'Print detailed help, then exit'

