# firewalld
# Autogenerated from man page /usr/share/man/man1/firewalld.1.gz
complete -c firewalld -s h -l help -d 'Prints a short help text and exists'
complete -c firewalld -l default-config -d 'Path to firewalld default configuration'
complete -c firewalld -l debug -d 'Set the debug level for firewalld to level'
complete -c firewalld -l debug-gc -d 'Print garbage collector leak information'
complete -c firewalld -l nofork -d 'Turn off daemon forking'
complete -c firewalld -l nopid -d 'Disable writing pid file.  By default the program will write a pid file'
complete -c firewalld -l system-config -d 'Path to firewalld system (user) configuration'

