# fitstopnm
# Autogenerated from man page /usr/share/man/man1/fitstopnm.1.gz
complete -c fitstopnm -o image -d 'This is for FITS files with three axes'
complete -c fitstopnm -o max -d 'sp You can use these options to override the min and max values as read from …'
complete -c fitstopnm -o scanmax -d 'Use this option to force the program to scan the data even when the header ha…'
complete -c fitstopnm -o printmax -d 'With this option, the program just prints the min and max values and quits wi…'
complete -c fitstopnm -o omaxval
complete -c fitstopnm -o min
complete -c fitstopnm -o topbottom

