# flatpak-mask
# Autogenerated from man page /usr/share/man/man1/flatpak-mask.1.gz
complete -c flatpak-mask -s h -l help -d 'Show help options and exit'
complete -c flatpak-mask -l remove -d 'Instead of adding the patterns, remove matching patterns'
complete -c flatpak-mask -l user -d 'Mask refs in a per-user installation'
complete -c flatpak-mask -l system -d 'Mask refs in the default system-wide installation'
complete -c flatpak-mask -l installation -d 'Mask refs in a system-wide installation specified by NAME among those defined…'
complete -c flatpak-mask -s v -l verbose -d 'Print debug information during command processing'

