# flatpak-search
# Autogenerated from man page /usr/share/man/man1/flatpak-search.1.gz
complete -c flatpak-search -l user -d 'Only search through remotes in the per-user installation'
complete -c flatpak-search -l system -d 'Only search through remotes in the default system-wide installation'
complete -c flatpak-search -l installation -d 'Show a system-wide installation by NAME among those defined in /etc/flatpak/i…'
complete -c flatpak-search -s h -l help -d 'Show help options and exit'
complete -c flatpak-search -s v -l verbose -d 'Print debug information during command processing'
complete -c flatpak-search -l ostree-verbose -d 'Print OSTree debug information during command processing'
complete -c flatpak-search -l columns -d 'Specify what information to show about each result'

