# flatpak-build-import-bundle
# Autogenerated from man page /usr/share/man/man1/flatpak-build-import-bundle.1.gz
complete -c flatpak-build-import-bundle -s h -l help -d 'Show help options and exit'
complete -c flatpak-build-import-bundle -s v -l verbose -d 'Print debug information during command processing'
complete -c flatpak-build-import-bundle -l ostree-verbose -d 'Print OSTree debug information during command processing'
complete -c flatpak-build-import-bundle -l ref -d 'Override the ref specified in the bundle'
complete -c flatpak-build-import-bundle -l oci -d 'Import an OCI image instead of a Flatpak bundle'
complete -c flatpak-build-import-bundle -l update-appstream -d 'Update the appstream branch after the build'
complete -c flatpak-build-import-bundle -l no-update-summary -d 'Don\\*(Aqt update the summary file after the new commit is added'
complete -c flatpak-build-import-bundle -l gpg-sign -d 'Sign the commit with this GPG key.  This option can be used multiple times'
complete -c flatpak-build-import-bundle -l gpg-homedir -d 'GPG Homedir to use when looking for keyrings'

