# flatpak-build-sign
# Autogenerated from man page /usr/share/man/man1/flatpak-build-sign.1.gz
complete -c flatpak-build-sign -s h -l help -d 'Show help options and exit'
complete -c flatpak-build-sign -l gpg-sign -d 'Sign the commit with this GPG key.  This option can be used multiple times'
complete -c flatpak-build-sign -l gpg-homedir -d 'GPG Homedir to use when looking for keyrings'
complete -c flatpak-build-sign -l runtime -d 'Sign a runtime instead of an app'
complete -c flatpak-build-sign -l arch -d 'The architecture to use'
complete -c flatpak-build-sign -s v -l verbose -d 'Print debug information during command processing'
complete -c flatpak-build-sign -l ostree-verbose -d 'Print OSTree debug information during command processing'

