# flatpak-remote-delete
# Autogenerated from man page /usr/share/man/man1/flatpak-remote-delete.1.gz
complete -c flatpak-remote-delete -s h -l help -d 'Show help options and exit'
complete -c flatpak-remote-delete -l user -d 'Modify the per-user configuration'
complete -c flatpak-remote-delete -l system -d 'Modify the default system-wide configuration'
complete -c flatpak-remote-delete -l installation -d 'Modify a system-wide installation specified by NAME among those defined in /e…'
complete -c flatpak-remote-delete -l force -d 'Remove remote even if its in use by installed apps or runtimes'
complete -c flatpak-remote-delete -s v -l verbose -d 'Print debug information during command processing'
complete -c flatpak-remote-delete -l ostree-verbose -d 'Print OSTree debug information during command processing'

