# flatpak
# Autogenerated from man page /usr/share/man/man1/flatpak.1.gz
complete -c flatpak -s h -l help -d 'Show help options and exit'
complete -c flatpak -s v -l verbose -d 'Show debug information during command processing.  Use -vv for more detail'
complete -c flatpak -l ostree-verbose -d 'Show OSTree debug information during command processing'
complete -c flatpak -l version -d 'Print version information and exit'
complete -c flatpak -l default-arch -d 'Print the default arch and exit'
complete -c flatpak -l supported-arches -d 'Print the supported arches in priority order and exit'
complete -c flatpak -l gl-drivers -d 'Print the list of active gl drivers and exit'
complete -c flatpak -l installations -d 'Print paths of system installations and exit'
complete -c flatpak -l print-system-only -d 'When the flatpak --print-updated-env command is run, only print the environme…'
complete -c flatpak -l print-updated-env -d 'Print the set of environment variables needed to use flatpaks, amending the c…'

