# flatpak-document-unexport
# Autogenerated from man page /usr/share/man/man1/flatpak-document-unexport.1.gz
complete -c flatpak-document-unexport -s h -l help -d 'Show help options and exit'
complete -c flatpak-document-unexport -s v -l verbose -d 'Print debug information during command processing'
complete -c flatpak-document-unexport -l ostree-verbose -d 'Print OSTree debug information during command processing'

