# flatpak-ps
# Autogenerated from man page /usr/share/man/man1/flatpak-ps.1.gz
complete -c flatpak-ps -s h -l help -d 'Show help options and exit'
complete -c flatpak-ps -s v -l verbose -d 'Print debug information during command processing'
complete -c flatpak-ps -l ostree-verbose -d 'Print OSTree debug information during command processing'
complete -c flatpak-ps -l columns -d 'Specify what information to show about each instance'

