# flatpak-create-usb
# Autogenerated from man page /usr/share/man/man1/flatpak-create-usb.1.gz
complete -c flatpak-create-usb -s h -l help -d 'Show help options and exit'
complete -c flatpak-create-usb -l user -d 'Copy refs from the per-user installation'
complete -c flatpak-create-usb -l system -d 'Copy refs from the default system-wide installation'
complete -c flatpak-create-usb -l installation -d 'Copy refs from a system-wide installation specified by NAME among those defin…'
complete -c flatpak-create-usb -l app -d 'Assume that all REFs are apps if not explicitly specified'
complete -c flatpak-create-usb -l runtime -d 'Assume that all REFs are runtimes if not explicitly specified'
complete -c flatpak-create-usb -l destination-repo -d 'Create the repository in DEST under MOUNT-PATH, rather than the default locat…'
complete -c flatpak-create-usb -l allow-partial -d 'Don\\*(Aqt print a warning when exporting partially installed commits, for exa…'
complete -c flatpak-create-usb -s v -l verbose -d 'Print debug information during command processing'
complete -c flatpak-create-usb -l ostree-verbose -d 'Print OSTree debug information during command processing'
complete -c flatpak-create-usb -l sideload-repo -d 'option with flatpak install'

