# flatpak-list
# Autogenerated from man page /usr/share/man/man1/flatpak-list.1.gz
complete -c flatpak-list -s h -l help -d 'Show help options and exit'
complete -c flatpak-list -l user -d 'List per-user installations'
complete -c flatpak-list -l system -d 'List the default system-wide installations'
complete -c flatpak-list -l installation -d 'List a system-wide installation specified by NAME among those defined in /etc…'
complete -c flatpak-list -l arch -d 'List apps/runtimes for this architecture'
complete -c flatpak-list -s d -l show-details -d 'Show origin, sizes and other extra information.  Equivalent to --columns=all'
complete -c flatpak-list -l app -d 'List applications'
complete -c flatpak-list -l runtime -d 'List runtimes'
complete -c flatpak-list -l all -s a -d 'List all installed runtimes, including locale and debug extensions'
complete -c flatpak-list -l app-runtime -d 'List applications that use the given runtime'
complete -c flatpak-list -s v -l verbose -d 'Print debug information during command processing'
complete -c flatpak-list -l ostree-verbose -d 'Print OSTree debug information during command processing'
complete -c flatpak-list -l columns -d 'Specify what information to show about each ref'

