# flatpak-document-export
# Autogenerated from man page /usr/share/man/man1/flatpak-document-export.1.gz
complete -c flatpak-document-export -s h -l help -d 'Show help options and exit'
complete -c flatpak-document-export -s u -l unique -d 'Don\\*(Aqt reuse an existing document id for the file'
complete -c flatpak-document-export -s t -l transient -d 'The document will only exist for the length of the session'
complete -c flatpak-document-export -s n -l noexist -d 'Don\\*(Aqt require the file to exist already'
complete -c flatpak-document-export -s a -l app -d 'Grant read access to the specified application'
complete -c flatpak-document-export -s r -l allow-read -d 'Grant read access to the applications specified with --app'
complete -c flatpak-document-export -l forbid-read -d 'Revoke read access for the applications specified with --app'
complete -c flatpak-document-export -s w -l allow-write -d 'Grant write access to the applications specified with --app'
complete -c flatpak-document-export -l forbid-write -d 'Revoke write access for the applications specified with --app'
complete -c flatpak-document-export -s d -l allow-delete -d 'Grant the ability to remove the document from the document portal to the appl…'
complete -c flatpak-document-export -l forbid-delete -d 'Revoke the ability to remove the document from the document portal from the a…'
complete -c flatpak-document-export -s g -l allow-grant-permission -d 'Grant the ability to grant further permissions to the applications specified …'
complete -c flatpak-document-export -l forbid-grant-permission -d 'Revoke the ability to grant further permissions for the applications specifie…'
complete -c flatpak-document-export -s v -l verbose -d 'Print debug information during command processing'
complete -c flatpak-document-export -l ostree-verbose -d 'Print OSTree debug information during command processing'
complete -c flatpak-document-export -l allow -d and
complete -c flatpak-document-export -l forbid -d 'options can be used to grant or remove additional privileges'

