# flatpak-kill
# Autogenerated from man page /usr/share/man/man1/flatpak-kill.1.gz
complete -c flatpak-kill -s h -l help -d 'Show help options and exit'
complete -c flatpak-kill -s v -l verbose -d 'Print debug information during command processing'
complete -c flatpak-kill -l ostree-verbose -d 'Print OSTree debug information during command processing'

