# flatpak-remotes
# Autogenerated from man page /usr/share/man/man1/flatpak-remotes.1.gz
complete -c flatpak-remotes -s h -l help -d 'Show help options and exit'
complete -c flatpak-remotes -l user -d 'Show the per-user configuration'
complete -c flatpak-remotes -l system -d 'Show the default system-wide configuration'
complete -c flatpak-remotes -l installation -d 'Show a system-wide installation by NAME among those defined in /etc/flatpak/i…'
complete -c flatpak-remotes -s d -l show-details -d 'Show more information for each repository in addition to the name'
complete -c flatpak-remotes -l show-disabled -d 'Show disabled repos'
complete -c flatpak-remotes -s v -l verbose -d 'Print debug information during command processing'
complete -c flatpak-remotes -l ostree-verbose -d 'Print OSTree debug information during command processing'
complete -c flatpak-remotes -l columns -d 'Specify what information to show about each ref'

