# flatpak-document-info
# Autogenerated from man page /usr/share/man/man1/flatpak-document-info.1.gz
complete -c flatpak-document-info -s h -l help -d 'Show help options and exit'
complete -c flatpak-document-info -s v -l verbose -d 'Print debug information during command processing'
complete -c flatpak-document-info -l ostree-verbose -d 'Print OSTree debug information during command processing'

