# flatpak-permission-remove
# Autogenerated from man page /usr/share/man/man1/flatpak-permission-remove.1.gz
complete -c flatpak-permission-remove -s h -l help -d 'Show help options and exit'
complete -c flatpak-permission-remove -s v -l verbose -d 'Print debug information during command processing'
complete -c flatpak-permission-remove -l ostree-verbose -d 'Print OSTree debug information during command processing'

