# flatpak-make-current
# Autogenerated from man page /usr/share/man/man1/flatpak-make-current.1.gz
complete -c flatpak-make-current -s h -l help -d 'Show help options and exit'
complete -c flatpak-make-current -l user -d 'Update a per-user installation'
complete -c flatpak-make-current -l system -d 'Update the default system-wide installation'
complete -c flatpak-make-current -l installation -d 'Updates a system-wide installation specified by NAME among those defined in /…'
complete -c flatpak-make-current -l arch -d 'The architecture to make current for'
complete -c flatpak-make-current -s v -l verbose -d 'Print debug information during command processing'
complete -c flatpak-make-current -l ostree-verbose -d 'Print OSTree debug information during command processing'

