# flatpak-spawn
# Autogenerated from man page /usr/share/man/man1/flatpak-spawn.1.gz
complete -c flatpak-spawn -s h -l help -d 'Show help options and exit'
complete -c flatpak-spawn -s v -l verbose -d 'Print debug information'
complete -c flatpak-spawn -l forward-fd -d 'Forward a file descriptor'
complete -c flatpak-spawn -l clear-env -d 'Run with a clean environment'
complete -c flatpak-spawn -l watch-bus -d 'Make the spawned command exit if we do'
complete -c flatpak-spawn -l env -d 'Set an environment variable'
complete -c flatpak-spawn -l latest-version -d 'Use the latest version of the refs that are used to set up the sandbox'
complete -c flatpak-spawn -l no-network -d 'Run without network access'
complete -c flatpak-spawn -l sandbox -d 'Run fully sandboxed'
complete -c flatpak-spawn -l sandbox-expose -d 'Expose read-write access to a file in the sandbox'
complete -c flatpak-spawn -l sandbox-expose-ro -d 'Expose readonly access to a file in the sandbox'
complete -c flatpak-spawn -l host -d 'Run the command unsandboxed on the host.  This requires access to the org'
complete -c flatpak-spawn -l directory -d 'The working directory in which to run the command'

