# flatpak-pin
# Autogenerated from man page /usr/share/man/man1/flatpak-pin.1.gz
complete -c flatpak-pin -s h -l help -d 'Show help options and exit'
complete -c flatpak-pin -l remove -d 'Instead of adding the patterns, remove matching patterns'
complete -c flatpak-pin -l user -d 'Pin refs in a per-user installation'
complete -c flatpak-pin -l system -d 'Pin refs in the default system-wide installation'
complete -c flatpak-pin -l installation -d 'Pin refs in a system-wide installation specified by NAME among those defined …'
complete -c flatpak-pin -s v -l verbose -d 'Print debug information during command processing'

