# flatpak-enter
# Autogenerated from man page /usr/share/man/man1/flatpak-enter.1.gz
complete -c flatpak-enter -s h -l help -d 'Show help options and exit'
complete -c flatpak-enter -s v -l verbose -d 'Print debug information during command processing'
complete -c flatpak-enter -l ostree-verbose -d 'Print OSTree debug information during command processing'

