# flatpak-repo
# Autogenerated from man page /usr/share/man/man1/flatpak-repo.1.gz
complete -c flatpak-repo -s h -l help -d 'Show help options and exit'
complete -c flatpak-repo -l info -d 'Print general information about a local repository'
complete -c flatpak-repo -l branches -d 'List the branches in a local repository'
complete -c flatpak-repo -l metadata -d 'Print metadata for a branch in the repository'
complete -c flatpak-repo -l commits -d 'Show commits and deltas for a branch in the repository'
complete -c flatpak-repo -s v -l verbose -d 'Print debug information during command processing'
complete -c flatpak-repo -l ostree-verbose -d 'Print OSTree debug information during command processing'

