# flatpak-info
# Autogenerated from man page /usr/share/man/man1/flatpak-info.1.gz
complete -c flatpak-info -s h -l help -d 'Show help options and exit'
complete -c flatpak-info -l user -d 'Query per-user installations'
complete -c flatpak-info -l system -d 'Query the default system-wide installation'
complete -c flatpak-info -l installation -d 'Query a system-wide installation by NAME among those defined in /etc/flatpak/…'
complete -c flatpak-info -l arch -d 'Query for this architecture'
complete -c flatpak-info -s r -l show-ref -d 'Show the installed ref'
complete -c flatpak-info -s o -l show-origin -d 'Show the remote the ref is installed from'
complete -c flatpak-info -s c -l show-commit -d 'Show the installed commit id'
complete -c flatpak-info -s s -l show-size -d 'Show the installed size'
complete -c flatpak-info -s m -l show-metadata -d 'Show the metadata'
complete -c flatpak-info -l show-runtime -d 'Show the runtime'
complete -c flatpak-info -l show-sdk -d 'Show the SDK'
complete -c flatpak-info -s M -l show-permissions -d 'Show the permissions'
complete -c flatpak-info -l file-access -d 'Show the level of access to the given path'
complete -c flatpak-info -s e -l show-extensions -d 'Show the matching extensions'
complete -c flatpak-info -s l -l show-location -d 'Show the on-disk location of the app or runtime.  See the examples below'
complete -c flatpak-info -s v -l verbose -d 'Print debug information during command processing'
complete -c flatpak-info -l ostree-verbose -d 'Print OSTree debug information during command processing'
complete -c flatpak-info -l show- -d or

