# fsadm
# Autogenerated from man page /usr/share/man/man8/fsadm.8.gz
complete -c fsadm -s e -l ext-offline -d 'Unmount ext2/ext3/ext4 filesystem before doing resize'
complete -c fsadm -s f -l force -d 'Bypass some sanity checks'
complete -c fsadm -s h -l help -d 'Display the help text'
complete -c fsadm -s l -l lvresize -d 'Resize also given lvm2 logical volume'
complete -c fsadm -s n -l dry-run -d 'Print commands without running them'
complete -c fsadm -s v -l verbose -d 'Be more verbose'
complete -c fsadm -s y -l yes -d 'Answer "yes" at any prompts'
complete -c fsadm -s c -l cryptresize -d 'Resize dm-crypt mapping together with filesystem detected on the device'
complete -c fsadm -s r -l resizefs

