# g3topbm
# Autogenerated from man page /usr/share/man/man1/g3topbm.1.gz
complete -c g3topbm -o kludge -d 'Tells g3topbm to ignore the first few lines of the file; sometimes fax files …'
complete -c g3topbm -o reversebits -d 'Tells g3topbm to interpret bits least-significant first, instead of the defau…'
complete -c g3topbm -o stretch -d 'This option tells g3topbm to stretch the image vertically by duplicating each…'
complete -c g3topbm -o width -d 'This option tells g3topbm that the image is supposed to be pixels pixels wide'
complete -c g3topbm -o paper_size -d 'This option tells g3topbm for what size paper this image is supposed to be fo…'
complete -c g3topbm -o stop_error -d 'This option tells g3topbm to fail when it finds a problem in the input'
complete -c g3topbm -o stoperror -d 'file, it will not tell you of your mistake'

