# gawk
# Autogenerated from man page /usr/share/man/man1/gawk.1.gz
complete -c gawk -l include -d 'options), and values to be made available in the ARGC and ARGV pre-defined AW…'
complete -c gawk -l profile -d 'option, it starts gathering profiling statistics from the execution of the pr…'
complete -c gawk -l debug -d 'option to the command line'
complete -c gawk -s f -d and
complete -c gawk -l file -d 'Read the AWKprogram-file , instead of from the first command line argument'
complete -c gawk -s F
complete -c gawk -l field-separator -d 'Use fs for the input field separator (the value of the FS predefined variable)'
complete -c gawk -s v
complete -c gawk -l assign -d 'Assign the value val to the variable var , before execution of the program be…'
complete -c gawk -s b
complete -c gawk -l characters-as-bytes -d 'Treat all input data as single-byte characters'
complete -c gawk -l posix -d 'option overrides this one'
complete -c gawk -s c
complete -c gawk -l traditional -d 'Run in compatibility mode'
complete -c gawk -s C
complete -c gawk -l copyright -d 'Print the short version of the GNUthe standard output and exit successfully'
complete -c gawk -s d
complete -c gawk -l dump-variables -d 'Print a sorted list of global variables, their types and final values to file '
complete -c gawk -s D
complete -c gawk -s e
complete -c gawk -l source -d 'Use program-text as AWKThis option allows the easy intermixing of library fun…'
complete -c gawk -s E
complete -c gawk -l exec -d 'Similar to'
complete -c gawk -s g
complete -c gawk -l gen-pot -d 'Scan and parse the AWK'
complete -c gawk -s h
complete -c gawk -l help -d 'Print a relatively short summary of the available options on the standard out…'
complete -c gawk -s i
complete -c gawk -s I
complete -c gawk -l trace -d 'Print the internal byte code names as they are executed when running the prog…'
complete -c gawk -s l
complete -c gawk -l load -d 'Load a gawk extension from the shared library lib '
complete -c gawk -s L
complete -c gawk -l lint -d 'Provide warnings about constructs that are dubious or non-portable to other A…'
complete -c gawk -s M
complete -c gawk -l bignum -d 'Force arbitrary precision arithmetic on numbers'
complete -c gawk -s n
complete -c gawk -l non-decimal-data -d 'Recognize octal and hexadecimal values in input data'
complete -c gawk -s N
complete -c gawk -l use-lc-numeric -d 'Force gawk to use the locale\'s decimal point character when parsing input data'
complete -c gawk -s W
complete -c gawk -l nostalgia -d 'Provide a moment of nostalgia for long time awk users'
complete -c gawk -s o
complete -c gawk -l pretty-print -d 'Output a pretty printed version of the program to file '
complete -c gawk -l no-optimize
complete -c gawk -s O
complete -c gawk -l optimize -d 'Enable gawk \'s default optimizations upon the internal representation of the …'
complete -c gawk -s p
complete -c gawk -s P
complete -c gawk -s r
complete -c gawk -l re-interval -d 'Enable the use of interval expressions in regular expression matching (see Re…'
complete -c gawk -s s
complete -c gawk -s S
complete -c gawk -l sandbox -d 'Run gawk in sandbox mode, disabling the system() function, input redirection …'
complete -c gawk -s t
complete -c gawk -l lint-old -d 'Provide warnings about constructs that are not portable to the original versi…'
complete -c gawk -s V
complete -c gawk -l version -d 'Print version information for this particular copy of gawk on the standard ou…'
complete -c gawk -s 1
complete -c gawk -s Y
complete -c gawk -l parsedebug -d 'Turn on yacc (1) or bison (1) debugging output during program parsing'

