# gc
# Autogenerated from man page /usr/share/man/man1/gc.1.gz
complete -c gc -s n -d 'Count nodes'
complete -c gc -s e -d 'Count edges'
complete -c gc -s c -d 'Count connected components'
complete -c gc -s C -d 'Count clusters'
complete -c gc -s a -d 'Count all.  Equivalent to  -encC'
complete -c gc -s r -d 'Recursively analyze subgraphs'
complete -c gc -s s -d 'Print no output.  Only exit value is important'
complete -c gc -s D -d 'Only analyze directed graphs'
complete -c gc -s U -d 'Only analyze undirected graphs'
complete -c gc -s v -d 'Verbose output'
complete -c gc -o encC
complete -c gc -s '?' -d 'Print usage information'
complete -c gc -s E -d 'option was used, and a graph of the wrong type was encountered'

