# gcab
# Autogenerated from man page /usr/share/man/man1/gcab.1.gz
complete -c gcab -s c -l create -d 'create a new cabinet archive'
complete -c gcab -s x -l extract -d 'extract files from a cabinet archive'
complete -c gcab -s t -l list -d 'list files of a cabinet archive'
complete -c gcab -s n -l nopath -d 'create files without pathnames'
complete -c gcab -s C -l directory -d 'change or extract to directory DIR'
complete -c gcab -s v -l verbose -d 'verbosely list files processed'
complete -c gcab -s z -l zip -d 'use zip compression AUTHOR Written by Marc-AndrÃ© Lureau <marcandre'

