# gdiffmk
# Autogenerated from man page /usr/share/man/man1/gdiffmk.1.gz
complete -c gdiffmk -s a -d 'Use the  addmark for source lines not in  file1 but present in R file2 '
complete -c gdiffmk -s B -d 'By default, the deleted texts marked by the  -D option end with an added trof…'
complete -c gdiffmk -s c -d 'Use the  changemark for changed source lines.  Default:  | '
complete -c gdiffmk -s d -d 'Use the  deletemark for deleted source lines.  Default:  * '
complete -c gdiffmk -s D -d 'Show the deleted portions from changed and deleted text'
complete -c gdiffmk -s M -d 'Change the delimiting marks for the  -D option'
complete -c gdiffmk -s x -d 'Use the  diffcmd command to perform the comparison of  file1 and R file2 '
complete -c gdiffmk -l help -d 'Print a usage message on standard error output and exit'
complete -c gdiffmk -l version -d 'Print version information on the standard output and exit'

