# git-sparse-checkout
# Autogenerated from man page /usr/share/man/man1/git-sparse-checkout.1.gz
complete -c git-sparse-checkout -l stdin -d 'option is provided, the patterns are read from standard in as a newline-delim…'
complete -c git-sparse-checkout -l cone -d 'is passed or core'
complete -c git-sparse-checkout -l sparse-index -d 'option to use a sparse index (the default is to not use it)'

