# git-bundle
# Autogenerated from man page /usr/share/man/man1/git-bundle.1.gz
complete -c git-bundle -l progress -d 'Progress status is reported on the standard error stream by default when it i…'
complete -c git-bundle -l all-progress -d 'When --stdout is specified then progress report is displayed during the objec…'
complete -c git-bundle -l all-progress-implied -d 'This is used to imply --all-progress whenever progress display is activated'
complete -c git-bundle -l version -d 'Specify the bundle version'
complete -c git-bundle -s q -l quiet -d 'This flag makes the command not to report its progress on the standard error …'

