# glilypond
# Autogenerated from man page /usr/share/man/man1/glilypond.1.gz
complete -c glilypond -o Tps
complete -c glilypond -o Tdvi
complete -c glilypond -o Thtml -d and
complete -c glilypond -o Txhtml -d 'I\'m not sure about the ldp and lj4 devices'
complete -c glilypond -l ps
complete -c glilypond -l div
complete -c glilypond -l html -d or
complete -c glilypond -l xhtml -d 'Unfortunately, the groff option'
complete -c glilypond -o Tpdf -d 'does not work and the groffer default PDF works neither'
complete -c glilypond -s '?' -s h -l help -l usage -d 'Print help or usage information, then leave the program'
complete -c glilypond -l version -d 'Print version information'
complete -c glilypond -s l -l license -d 'Print license information'
complete -c glilypond -s e -l eps_dir -d 'Normally all EPS files are sent to the temporary directory'
complete -c glilypond -s p -l prefix -d 'Normally all temporary files get names that start with the ly  prefix'
complete -c glilypond -s k -l keep_all -d 'Normally all temporary files without the eps files are deleted'
complete -c glilypond -s t -l temp_dir -d 'With this option, you call a directory that is the base for the temporary dir…'
complete -c glilypond -s o -l output -d 'Normally all groff output of this program is sent to STDOUT '
complete -c glilypond -s v -s V -l verbose -d 'A lot more of information is sent to STDERR'
complete -c glilypond -o kVe -d 'is a collection of the short options'
complete -c glilypond -l keep_al -d 'up to'
complete -c glilypond -l k -d 'because the program does not have another long option whose name starts with …'
complete -c glilypond -l vers -d 'because there is also the long option'
complete -c glilypond -l verb -d 'An option argument can also be appended to an abbreviation'
complete -c glilypond -l e -d 'the same as'
complete -c glilypond -l Keep_All -d 'or even as an abbreviation like'
complete -c glilypond -l KeE -d 'FILESPEC ARGUMENTS An argument that is not an option or an option argument is…'
complete -c glilypond -l pdf2eps -d 'In this mode, the '
complete -c glilypond -l ly2eps -d 'In this mode, the '

