# gml2gv
# Autogenerated from man page /usr/share/man/man1/gml2gv.1.gz
complete -c gml2gv -s v -d 'Turns on verbose mode'
complete -c gml2gv -s '?' -d 'Prints usage information and exits'
complete -c gml2gv -s g -d 'The string gname is used as the name of the generated graph'
complete -c gml2gv -s o -d 'Prints output to the file outfile.  If not given, gml2gv uses stdout'

