# gpgrt-config
# Autogenerated from man page /usr/share/man/man1/gpgrt-config.1.gz
complete -c gpgrt-config -l mt -d 'Provide output appropriate for multithreaded programs'
complete -c gpgrt-config -l version -d 'Print the currently installed version of Libgpg-error on the standard output'
complete -c gpgrt-config -l libs -d 'Print the linker flags that are necessary to link a program using Libgpg-error'
complete -c gpgrt-config -l cflags -d 'Print the compiler flags that are necessary to compile a program using Libgpg…'
complete -c gpgrt-config -l prefix -d 'If specified, use prefix instead of the installation prefix that Libgpg-error…'
complete -c gpgrt-config -l exec-prefix -d 'If specified, use prefix instead of the installation exec prefix that Libgpg-…'

