# gpinyin
# Autogenerated from man page /usr/share/man/man1/gpinyin.1.gz
complete -c gpinyin -s h -d 'TQ  --help Print usage information and exit'
complete -c gpinyin -l help -d 'Print usage information and exit'
complete -c gpinyin -s v
complete -c gpinyin -l version -d 'Print version information and exit.  AUTHORS gpinyin was written by'

