# grn
# Autogenerated from man page /usr/share/man/man1/grn.1.gz
complete -c grn -s T -d 'Prepare output for printer R dev .  The default device is  ps '
complete -c grn -s M -d 'Prepend  dir to the default search path for  gremlin files'
complete -c grn -s F -d 'Search  dir for subdirectories R dev name '
complete -c grn -s C -d 'Recognize  . GS and  . GE (and  '
complete -c grn -s s -d '\\"This switch causes the picture to be traversed twice: '
complete -c grn -s v -d 'Print the version number.  GRN COMMANDS Each input line between . GS and '
complete -c grn -o 1@@-1 -d 'Table 1'
complete -c grn -o '1.0' -d '( AED version) or a single asterisk, [lq]*[rq] ( SUN / X11 version)'

