# grodvi
# Autogenerated from man page /usr/share/man/man1/grodvi.1.gz
complete -c grodvi -s d -d 'Do not use tpic specials to implement drawing commands'
complete -c grodvi -s F -d 'Prepend directory '
complete -c grodvi -s l -d 'Specify landscape orientation'
complete -c grodvi -s p -d 'Specify paper dimensions'
complete -c grodvi -s v -d 'Print the version number'
complete -c grodvi -o Tdvi -d 'loads pspic. tmac automatically, providing the PSPIC macro'
complete -c grodvi -s w -d 'Set the default line thickness to n thousandths of an em'
complete -c grodvi -o mec -d '(which loads the file ec. tmac ) provides the EC and TC fonts'

