# grolbp
# Autogenerated from man page /usr/share/man/man1/grolbp.1.gz
complete -c grolbp -s c -d 'TQ  --copies= num-copies Print  num-copies copies of each page'
complete -c grolbp -s F -d 'TQ  --fontdir= font-directory Prepend directory '
complete -c grolbp -s h -d 'TQ  --help Print a short help text'
complete -c grolbp -s l -d 'TQ  --landscape Print the document with a landscape orientation'
complete -c grolbp -s o -d 'TQ  --orientation= orientation Print the document with  orientation orientati…'
complete -c grolbp -s p -d 'TQ  --papersize= paper-size Set the paper size to R paper-size , which must b…'
complete -c grolbp -s v -d 'TQ  --version Print the version number'
complete -c grolbp -l copies -d 'Print num-copies copies of each page'
complete -c grolbp -l fontdir -d 'Prepend directory font-directory /dev name to the search path for font and de…'
complete -c grolbp -l help -d 'Print a short help text'
complete -c grolbp -l landscape -d 'Print the document with a landscape orientation'
complete -c grolbp -l orientation -d 'Print the document with orientation orientation, which must be `portrait\' or …'
complete -c grolbp -l papersize -d 'Set the paper size to paper-size , which must be a valid paper size descripti…'
complete -c grolbp -l version -d 'Print the version number'
complete -c grolbp -s w
complete -c grolbp -l linewidth -d 'Set the default line thickness to width thousandths of an em'

