# gropdf
# Autogenerated from man page /usr/share/man/man1/gropdf.1.gz
complete -c gropdf -s d -d 'Include debug information as comments within the PDF'
complete -c gropdf -s e -d 'Forces  gropdf to embed  all fonts (even the 14 base PDF fonts)'
complete -c gropdf -s F -d 'Prepend directory R dir /dev name to the search path for font, and device des…'
complete -c gropdf -s I -d 'This option may be used to add a directory to the search path for files named…'
complete -c gropdf -s l -d 'Orient the document in landscape format'
complete -c gropdf -s p -d 'Set physical dimension of output medium'
complete -c gropdf -s s -d 'Append a comment line to end of PDF showing statistics, i. e'
complete -c gropdf -o 'u\\c' -d 'RI " [" cmapfile ]  Gropdf normally includes a ToUnicode CMap with any font c…'
complete -c gropdf -s v -d 'TQ  --version Print the version number and exit. \\"'
complete -c gropdf -s w -d '\\" Lines should be drawn using a thickness of . \\" R n \\~\\c '
complete -c gropdf -o Tpdf -d option
complete -c gropdf -s P -d option
complete -c gropdf -o uc -d ' [ cmapfile ] Gropdf normally includes a ToUnicode CMap with any font created…'
complete -c gropdf -l version -d 'Print the version number and exit'
complete -c gropdf -s y -d 'Set the foundry to use for selecting fonts of the same name'
complete -c gropdf -s m -d or
complete -c gropdf -s L -d 'the drawing is left aligned'
complete -c gropdf -s C -d or
complete -c gropdf -s R -d 'a linelength greater than the width of the drawing is required as well'
complete -c gropdf -o 'u\'\\c' -d 'Convert your font to something groff understands'

