# gst-launch-1
# Autogenerated from man page /usr/share/man/man1/gst-launch-1.0.1.gz
complete -c gst-launch-1 -l help -d 'Print help synopsis and available FLAGS'
complete -c gst-launch-1 -s v -l verbose -d 'Output status information and property notifications'
complete -c gst-launch-1 -s q -l quiet -d 'Do not print any progress information'
complete -c gst-launch-1 -s m -l messages -d 'Output messages posted on the pipeline\'s bus'
complete -c gst-launch-1 -s t -l tags -d 'Output tags (also known as metadata)'
complete -c gst-launch-1 -s e -l eos-on-shutdown -d 'Force an EOS event on sources before shutting the pipeline down'
complete -c gst-launch-1 -s i -l index -d 'Gather and print index statistics'
complete -c gst-launch-1 -s f -l no-fault -d 'Do not install a fault handler'
complete -c gst-launch-1 -s T -l trace -d 'Print memory allocation traces'
complete -c gst-launch-1 -l no-position -d 'Do not print current position of pipeline'
complete -c gst-launch-1 -l force-position -d 'Allow printing current position of pipeline even if stdout is not a TTY'

