# gts-config
# Autogenerated from man page /usr/share/man/man1/gts-config.1.gz
complete -c gts-config -l prefix
complete -c gts-config -l exec-prefix
complete -c gts-config -l version
complete -c gts-config -l libs
complete -c gts-config -l cflags
complete -c gts-config -l check

