# gts2stl
# Autogenerated from man page /usr/share/man/man1/gts2stl.1.gz
complete -c gts2stl -s r -l revert -d 'Revert face normals'
complete -c gts2stl -s v -l verbose -d 'Display surface statistics'
complete -c gts2stl -s h -l help -d 'Display the help and exit'

