# gtscheck
# Autogenerated from man page /usr/share/man/man1/gtscheck.1.gz
complete -c gtscheck -s v -l verbose -d 'Print statistics about the surface'
complete -c gtscheck -s h -l help -d 'Display the help and exit'

