# gtscompare
# Autogenerated from man page /usr/share/man/man1/gtscompare.1.gz
complete -c gtscompare -s s -l symmetric -d 'Symmetric statistics'
complete -c gtscompare -s i -l image -d 'Output visualisation mesh'
complete -c gtscompare -s c -l cmap -d 'Load  FILE as colormap'
complete -c gtscompare -s m -l min -d 'Use  VAL as minimum scaling value'
complete -c gtscompare -s M -l max -d 'Use  VAL as maximum scaling value'
complete -c gtscompare -s r -l reverse -d 'Reverse colormap'
complete -c gtscompare -s l -l log -d 'Use log scale'
complete -c gtscompare -s h -l help -d 'Display the help and exit'

