# gvpack
# Autogenerated from man page /usr/share/man/man1/gvpack.1.gz
complete -c gvpack -s g -d 'Combines the graphs at the graph level'
complete -c gvpack -o array -d 'Combines the graphs at the graph level, placing them in an array'
complete -c gvpack -s G -d 'Specifies attributes to be added to the resulting union graph'
complete -c gvpack -s m -d 'Packs the graphs allowing a margin of output points around the parts'
complete -c gvpack -s n -d 'Combines the graphs at the node level.  Clusters are ignored in the packing'
complete -c gvpack -s o -d 'Prints output to the file output.  If not given, gvpack uses stdout'
complete -c gvpack -s s -d 'Use graph_name as the name of the root graph.  By default, "root" is used'
complete -c gvpack -s u -d 'Don\'t pack the graphs.  Just combine them into a single graph'
complete -c gvpack -s v -d 'Verbose mode'
complete -c gvpack -s '?' -d 'Prints usage information and exit'

