# gvpr
# Autogenerated from man page /usr/share/man/man1/gvpr.1.gz
complete -c gvpr -s a -d 'The string args is split into whitespace\\(hyseparated tokens,  with the indiv…'
complete -c gvpr -s c -d 'Use the source graph as the output graph'
complete -c gvpr -s i -d 'Derive the node\\(hyinduced subgraph extension of the output graph in the cont…'
complete -c gvpr -s o -d 'Causes the output stream to be written to the specified file; by default, out…'
complete -c gvpr -s f -d 'Use the contents of the specified file as the program to execute on the input'
complete -c gvpr -s q -d 'Turns off warning messages'
complete -c gvpr -s n -d 'Turns off graph read-ahead'
complete -c gvpr -s V -d 'Causes the program to print version information and exit'
complete -c gvpr -s '?' -d 'Causes the program to print usage information and exit'

