# gxl2gv
# Autogenerated from man page /usr/share/man/man1/gxl2gv.1.gz
complete -c gxl2gv -s g -d 'The command name and input file extensions are ignored, the input is taken as…'
complete -c gxl2gv -s d -d 'The command name and input file extensions are ignored, the input is taken as…'
complete -c gxl2gv -s '?' -d 'Prints usage information and exits'
complete -c gxl2gv -s o -d 'If specified, the output will be written into the file outfile'

