# happrox
# Autogenerated from man page /usr/share/man/man1/happrox.1.gz
complete -c happrox -s n -l number -d 'Stop the refinement process if the number of vertices is larger than N'
complete -c happrox -s c -l cost -d 'Stop the refinement process if the cost of insertion of a vertex is smaller t…'
complete -c happrox -s f -l flat -d 'Input is a flat file with three x,y,z columns (default is PGM file)'
complete -c happrox -s r -l relative -d 'Use relative height cost for all heights larger than Z'
complete -c happrox -s k -l keep -d 'Keep enclosing triangle'
complete -c happrox -s C -l closed -d 'Close the surface'
complete -c happrox -s l -l log -d 'Log evolution of cost'
complete -c happrox -s v -l verbose -d 'Display surface statistics'
complete -c happrox -s h -l help -d 'Display the help and exit'

