# hpftodit
# Autogenerated from man page /usr/share/man/man1/hpftodit.1.gz
complete -c hpftodit -s a -d 'Include characters in the TFM file that are not included in R map-file '
complete -c hpftodit -s d -d 'Dump information about the TFM file to the standard output; this option can b…'
complete -c hpftodit -s q -d 'Suppress warnings about characters in the map file that were not found in the…'
complete -c hpftodit -s v -d 'Print the  hpftodit version number and exit'
complete -c hpftodit -s s -d 'The font is special'
complete -c hpftodit -s i -d 'Generate an italic correction for each character so that the character\'s widt…'

