# ijs-config
# Autogenerated from man page /usr/share/man/man1/ijs-config.1.gz
complete -c ijs-config -l help -d 'Show summary of options'
complete -c ijs-config -l version -d 'Show installed libijs version'
complete -c ijs-config -l libs -d 'Print the linker flags that are necessary to link an IJS program'
complete -c ijs-config -l cflags -d 'Print the compiler flags that are necessary to compile an IJS program'
complete -c ijs-config -l prefix -d 'If specified, use PREFIX instead of the installation prefix that IJS was buil…'
complete -c ijs-config -l exec-prefix -d 'If specified, use PREFIX instead of the installation exec prefix that IJS was…'

