# img2txt
# Autogenerated from man page /usr/share/man/man1/img2txt.1.gz
complete -c img2txt -s W -l width -d 'Change output column count.  If not given, the default is set to 60'
complete -c img2txt -s H -l height -d 'Change output line count'
complete -c img2txt -s x -l font-width -d 'Change output font width.  If not given, the default is set to 6'
complete -c img2txt -s y -l font-height -d 'Change output font height.  If not given, the default is set to 10'
complete -c img2txt -s b -l brightness -d 'Change image brightness.  Default to 1. 0'
complete -c img2txt -s c -l contrast -d 'Change image contrast.  Default to 1. 0'
complete -c img2txt -s g -l gamma -d 'Change image gamma.  Default to 1. 0'
complete -c img2txt -s d -l dither -d 'Change dithering algorithm'
complete -c img2txt -s f -l format -d 'Change output format'
complete -c img2txt -s h -l help -d 'Display help message and exit'
complete -c img2txt -s v -l version -d 'Display version of the program and exit'

