# indxbib
# Autogenerated from man page /usr/share/man/man1/indxbib.1.gz
complete -c indxbib -s v -d 'Print the version number'
complete -c indxbib -s w -d 'Index whole files.  Each file is a separate record'
complete -c indxbib -s c -d 'Read the list of common words from  file instead of R /usr/\\:share/\\:groff/\\:1'
complete -c indxbib -s d -d 'Use  dir as the pathname of the current working directory to store in the ind…'
complete -c indxbib -s f -d 'Read the files to be indexed from R file '
complete -c indxbib -s i -d 'Don\'t index the contents of fields whose names are in R string '
complete -c indxbib -s h -d 'Use the first prime greater than or equal to  n for the size of the hash table'
complete -c indxbib -s k -d 'Use at most  n keys per input record.  Initially  n is 100'
complete -c indxbib -s l -d 'Discard keys that are shorter than R n .  Initially  n is 3'
complete -c indxbib -s n -d 'Discard the  n most common words.  Initially  n is 100'
complete -c indxbib -s o -d 'The index should be named . RI basename . i '
complete -c indxbib -s t -d 'options are stored in the index; when the index is searched, keys will be dis…'

