# infotopam
# Autogenerated from man page /usr/share/man/man1/infotopam.1.gz
complete -c infotopam -o forcecolor -d 'sp Forces infotopam to convert 1 bit-plane icons to color PAM   images instea…'
complete -c infotopam -o numcolors -d 'sp Tells infotopam how many colors to override.   Pixels in the   Amiga '
complete -c infotopam -o selected -d 'Tells infotopam to convert the selected (second) icon instead of   the normal…'

