# intltool-extract
# Autogenerated from man page /usr/share/man/man8/intltool-extract.8.gz
complete -c intltool-extract -l local -d 'PD Creates a subdirectory under current working directory (named "tmp/") and …'
complete -c intltool-extract -l update -d 'PD Writes header file into the same directory the source file is in'
complete -c intltool-extract -l type -d 'PD Specify the type of source file.  Currently supported types are: '
complete -c intltool-extract -l version -d 'PD Show version information'
complete -c intltool-extract -l help -d 'PD Show usage and basic help information'
complete -c intltool-extract -s l
complete -c intltool-extract -s v
complete -c intltool-extract -s h
complete -c intltool-extract -s q
complete -c intltool-extract -l quiet

