# intltool-prepare
# Autogenerated from man page /usr/share/man/man8/intltool-prepare.8.gz
complete -c intltool-prepare -l verbose -d 'PD Be verbose to give user additional feedback'
complete -c intltool-prepare -l version -d 'Show version information'
complete -c intltool-prepare -s x
complete -c intltool-prepare -s v
complete -c intltool-prepare -s h
complete -c intltool-prepare -l help -d 'Show usage and basic help information'

