# intltoolize
# Autogenerated from man page /usr/share/man/man8/intltoolize.8.gz
complete -c intltoolize -l automake -d 'Work silently and assume that automake is being used in software'
complete -c intltoolize -l copy -d 'PD Copy files rather than creating symbolic links to them'
complete -c intltoolize -l debug -d 'Enable verbose shell tracing'
complete -c intltoolize -l dry-run -d 'PD Print commands only, instead of executing them'
complete -c intltoolize -l force -d 'PD Replace existing files if they exist'
complete -c intltoolize -l help -d 'Show usage and basic help information'
complete -c intltoolize -s c
complete -c intltoolize -s n
complete -c intltoolize -s f
complete -c intltoolize -l version -d 'Show version information.  REPORTING BUGS Report bugs to http://bugs'

