# intltool-merge
# Autogenerated from man page /usr/share/man/man8/intltool-merge.8.gz
complete -c intltool-merge -l ba-style -d 'PD Merge files in bonobo-activation style, which is used for bonobo servers'
complete -c intltool-merge -l desktop-style -d 'PD Merge files in desktop style, which is similar to the Windows '
complete -c intltool-merge -l keys-style -d 'PD Merge files in keys style, which is used for metadata'
complete -c intltool-merge -l oaf-style -d 'PD (OBSOLETE) Same as  -b / --ba-style ". "'
complete -c intltool-merge -l rfc822deb-style -d 'PD Merge files in RFC 822 style, which is usually used in Debian configuratio…'
complete -c intltool-merge -l quoted-style -d 'PD Merge files in quoted string style, which just translates any strings with…'
complete -c intltool-merge -l xml-style -d 'PD Merge files in standard XML style, both as attributes and as raw pcdata'
complete -c intltool-merge -l utf8 -d 'PD Convert all strings to UTF-8 before merging'
complete -c intltool-merge -l pass-through -d 'PD Use strings as is in '
complete -c intltool-merge -l cache -d 'PD (TBD)'
complete -c intltool-merge -l quiet -d 'PD Be quiet while running'
complete -c intltool-merge -l version -d 'PD Show version information'
complete -c intltool-merge -s b
complete -c intltool-merge -s d
complete -c intltool-merge -s k
complete -c intltool-merge -s o
complete -c intltool-merge -s r
complete -c intltool-merge -s x
complete -c intltool-merge -s u
complete -c intltool-merge -s p
complete -c intltool-merge -s c
complete -c intltool-merge -s q
complete -c intltool-merge -s v
complete -c intltool-merge -s h
complete -c intltool-merge -l help

