# intltool-update
# Autogenerated from man page /usr/share/man/man8/intltool-update.8.gz
complete -c intltool-update -l pot -d 'PD Generate po template (. pot) only'
complete -c intltool-update -l headers -d 'PD Executes intltool-extract(8) to extract strings inside XML/INI style files…'
complete -c intltool-update -l maintain -d 'PD Search for left out files, which should have been listed in  POTFILES'
complete -c intltool-update -l report -d 'PD Display a status report for all translations in the software'
complete -c intltool-update -l dist -d 'PD Merge  LANGCODE . po with existing PO template'
complete -c intltool-update -l gettext-package -d 'PD Manually specify PO template file name, instead of determining the name au…'
complete -c intltool-update -l output-file -d 'PD Manually specify output FILENAME after merging old translation with PO tem…'
complete -c intltool-update -l verbose -d 'PD Display lots of feedback'
complete -c intltool-update -l version -d 'Show version information'
complete -c intltool-update -s p
complete -c intltool-update -s s
complete -c intltool-update -s m
complete -c intltool-update -s r
complete -c intltool-update -s d
complete -c intltool-update -s g
complete -c intltool-update -s o
complete -c intltool-update -s x
complete -c intltool-update -l help -d 'Show usage and basic help information'

