# jar-openjdk8
# Autogenerated from man page /usr/share/man/man1/jar-openjdk8.1.gz
complete -c jar-openjdk8 -s C -d 'br When creating (\\f3c) or updating (\\f3u) a JAR file, this option temporaril…'
complete -c jar-openjdk8 -o Joption -d 'Sets the specified JVM option to be used when the JRE runs the JAR file'

