# javap-openjdk8
# Autogenerated from man page /usr/share/man/man1/javap-openjdk8.1.gz
complete -c javap-openjdk8 -o 'help
.br
--help
.br
-?' -d 'Prints a help message for the javap command'
complete -c javap-openjdk8 -o version -d 'Prints release information'
complete -c javap-openjdk8 -s l -d 'Prints line and local variable tables'
complete -c javap-openjdk8 -o public -d 'Shows only public classes and members'
complete -c javap-openjdk8 -o protected -d 'Shows only protected and public classes and members'
complete -c javap-openjdk8 -o 'private
.br
-p' -d 'Shows all classes and members'
complete -c javap-openjdk8 -o Joption -d 'Passes the specified option to the JVM.  For example: . sp . if n \\{\\'
complete -c javap-openjdk8 -s s -d 'Prints internal type signatures'
complete -c javap-openjdk8 -o sysinfo -d 'Shows system information (path, size, date, MD5 hash) of the class being proc…'
complete -c javap-openjdk8 -o constants -d 'Shows static final constants'
complete -c javap-openjdk8 -s c -d 'Prints disassembled code, for example, the instructions that comprise the Jav…'
complete -c javap-openjdk8 -o verbose -d 'Prints stack size, number of locals and arguments for methods'
complete -c javap-openjdk8 -o classpath -d 'Specifies the path the javap command uses to look up classes'
complete -c javap-openjdk8 -o bootclasspath -d 'Specifies the path from which to load bootstrap classes'
complete -c javap-openjdk8 -o extdir -d 'Overrides the location at which installed extensions are searched for'
complete -c javap-openjdk8 -o help
complete -c javap-openjdk8 -l help
complete -c javap-openjdk8 -s '?'
complete -c javap-openjdk8 -o private
complete -c javap-openjdk8 -s p

