# javah-openjdk8
# Autogenerated from man page /usr/share/man/man1/javah-openjdk8.1.gz
complete -c javah-openjdk8 -s o -d 'br Concatenates the resulting header or source files for all the classes list…'
complete -c javah-openjdk8 -s d -d 'br Sets the directory where the \\f3javah command saves the header files or th…'
complete -c javah-openjdk8 -o stubs -d 'br Causes the \\f3javah command to generate C declarations from the Java objec…'
complete -c javah-openjdk8 -o verbose -d 'br Indicates verbose output and causes the \\f3javah command to print a messag…'
complete -c javah-openjdk8 -o help -d 'br Prints a help message for \\f3javah usage'
complete -c javah-openjdk8 -o version -d 'br Prints \\f3javah command release information'
complete -c javah-openjdk8 -o jni -d 'br Causes the \\f3javah command to create an output file containing JNI-style …'
complete -c javah-openjdk8 -o classpath -d 'br Specifies the path the \\f3javah command uses to look up classes'
complete -c javah-openjdk8 -o bootclasspath -d 'br Specifies the path from which to load bootstrap classes'
complete -c javah-openjdk8 -o old -d 'br Specifies that old JDK 1. 0-style header files should be generated'
complete -c javah-openjdk8 -o force -d 'br Specifies that output files should always be written'
complete -c javah-openjdk8 -o Joption

