# jbig2dec
# Autogenerated from man page /usr/share/man/man1/jbig2dec.1.gz
complete -c jbig2dec -s e -l embedded -d 'Expect embedded bit stream without file header'
complete -c jbig2dec -s o -l output -d 'Store the decoded output in R file '
complete -c jbig2dec -s t -l format -d 'Force a particular output file format.  Supported are png and pbm'
complete -c jbig2dec -s d -l dump -d 'Print the structure of the JBIG2 file rather than explicitly decoding it'
complete -c jbig2dec -s m -l hash -d 'Print a hash of the decoded document'
complete -c jbig2dec -s q -l quiet -d 'Suppress warnings and other diagnostic output'
complete -c jbig2dec -s v -l verbose -d 'Report additional information about the decoding process'
complete -c jbig2dec -s V -l version -d 'Show program version information'
complete -c jbig2dec -s h -l help -d 'Show usage summary'

