# jbigtopnm
# Autogenerated from man page /usr/share/man/man1/jbigtopnm.1.gz
complete -c jbigtopnm -s x -d 'Decode only up to the largest resolution layer which is still not more than n…'
complete -c jbigtopnm -s y -d 'Decode only up to the largest resolution layer which is still not more than n…'
complete -c jbigtopnm -s b -d 'Use binary values instead of Gray code words in order to decode pixel values …'
complete -c jbigtopnm -s d -d 'Diagnose a BIE'
complete -c jbigtopnm -s p -d 'If the input contains multiple bitplanes, then extract only the specified sin…'

