# jhat-openjdk8
# Autogenerated from man page /usr/share/man/man1/jhat-openjdk8.1.gz
complete -c jhat-openjdk8 -o stack -d 'br Turns off tracking object allocation call stack'
complete -c jhat-openjdk8 -o refs -d 'br Turns off tracking of references to objects.  Default is \\f3true'
complete -c jhat-openjdk8 -o port -d 'br Sets the port for the \\f3jhat HTTP server.  Default is 7000'
complete -c jhat-openjdk8 -o exclude -d 'br Specifies a file that lists data members that should be excluded from the …'
complete -c jhat-openjdk8 -o baseline -d 'br Specifies a baseline heap dump'
complete -c jhat-openjdk8 -o debug -d 'br Sets the debug level for this tool.  A level of 0 means no debug output'
complete -c jhat-openjdk8 -o version -d 'br Reports the release number and exits'
complete -c jhat-openjdk8 -s h -d 'br Dsiplays a help message and exits'
complete -c jhat-openjdk8 -o help -d 'br Displays a help message and exits'
complete -c jhat-openjdk8 -o Jflag

