# jpegtopnm
# Autogenerated from man page /usr/share/man/man1/jpegtopnm.1.gz
complete -c jpegtopnm -o dct -d 'Use integer DCT method (default)'
complete -c jpegtopnm -o nosmooth -d 'Use a faster, lower-quality upsampling routine'
complete -c jpegtopnm -o maxmemory -d 'Set limit on the amount of memory jpegtopnm uses in processing large images'
complete -c jpegtopnm -o notadobe -d 'There are two variations on the CMYK (and likewise YCCK) color space that may…'
complete -c jpegtopnm -o dumpexif -d 'Print the interpreted contents of any Exif header in the input file to the St…'
complete -c jpegtopnm -o exif -d 'Extract the contents of the EXIF header from the input image and write it to …'
complete -c jpegtopnm -o multiple -d 'Read multiple JFIF images sequentially from the input stream.  See  '
complete -c jpegtopnm -o repair -d 'If the JFIF input is invalid, try to salvage whatever information is there an…'
complete -c jpegtopnm -o comments -d 'Print any comments in the input file to the Standard Error file'
complete -c jpegtopnm -o verbose -d 'Print details about the conversion to the Standard Error file'
complete -c jpegtopnm -o tracelevel -d 'Turn on the JPEG library\'s trace messages to the Standard Error file'
complete -c jpegtopnm -o adobe

