# jrunscript-openjdk8
# Autogenerated from man page /usr/share/man/man1/jrunscript-openjdk8.1.gz
complete -c jrunscript-openjdk8 -o classpath -d 'br Indicate where any class files are that the script needs to access'
complete -c jrunscript-openjdk8 -o cp -d 'br Same as \\f3-classpath\\f3path'
complete -c jrunscript-openjdk8 -o Dname -d 'br Sets a Java system property'
complete -c jrunscript-openjdk8 -o Jflag -d 'br Passes \\f3flag directly to the Java Virtual Machine where the \\f3jrunscrip…'
complete -c jrunscript-openjdk8 -s I -d 'br Uses the specified scripting language.  By default, JavaScript is used'
complete -c jrunscript-openjdk8 -s e -d 'br Evaluates the specified script'
complete -c jrunscript-openjdk8 -o encoding -d 'br Specifies the character encoding used to read script files'
complete -c jrunscript-openjdk8 -s f -d 'br Evaluates the specified script file (batch mode)'
complete -c jrunscript-openjdk8 -o help -d 'br Displays a help message and exits'
complete -c jrunscript-openjdk8 -s '?' -d 'br Displays a help message and exits'
complete -c jrunscript-openjdk8 -s q

