# ldns-dpa
# Autogenerated from man page /usr/share/man/man1/ldns-dpa.1.gz
complete -c ldns-dpa -s c -d 'Count occurrences of matching expressions'
complete -c ldns-dpa -s f -d 'Filter: only process packets that match the expression'
complete -c ldns-dpa -s h -d 'Show usage'
complete -c ldns-dpa -s p -d 'Show the total number of correct DNS packets, and percentage of -u and -c val…'
complete -c ldns-dpa -o of -d 'Write all packets that match the -f flag to file, as pcap data'
complete -c ldns-dpa -o ofh -d 'Write all packets that match the -f flag to file, in hexadecimal format, read…'
complete -c ldns-dpa -s s -d 'Show possible match names'
complete -c ldns-dpa -o sf -d 'Only evaluate packets (in representation format) that match the -f filter'
complete -c ldns-dpa -s u -d 'Count every occurrence of every value of the matchname (for instance, count a…'
complete -c ldns-dpa -o ua -d 'For every matchname in -u, show the average value of all matches'
complete -c ldns-dpa -o uac -d 'For every matchname in -u, show the average number of times this value was en…'
complete -c ldns-dpa -o um -d 'Only show the results from -u for values that occurred more than <number> tim…'
complete -c ldns-dpa -s v -d 'Set verbosity to level (1-5, 5 being the highest).  Mostly used for debugging'
complete -c ldns-dpa -o notip -d 'Write packets that were not recognized as IP packets to file (as pcap data)'
complete -c ldns-dpa -o baddns -d 'Write dns packets that were too mangled to parse to file (as pcap data)'
complete -c ldns-dpa -o version -d 'Show version and exit'

