# ldns-test-edns
# Autogenerated from man page /usr/share/man/man1/ldns-test-edns.1.gz
complete -c ldns-test-edns -s i -d 'after another, with no other explanations, and if none work or no IP addresse…'

