# ldns-gen-zone
# Autogenerated from man page /usr/share/man/man1/ldns-gen-zone.1.gz
complete -c ldns-gen-zone -s a -d 'Adds NUM extra artificial NS RRSets to the output'
complete -c ldns-gen-zone -s p -d 'Add NUM% of DS RRSets to the NS RRSets (anywhere between 1-4 DS records per R…'
complete -c ldns-gen-zone -s o -d 'Sets an $ORIGIN, which can be handy if the one in the zonefile is set to \'@\' …'
complete -c ldns-gen-zone -s s -d 'This is the recommended way of processing large zones that are already sorted…'
complete -c ldns-gen-zone -s h -d 'Show usage and exit'
complete -c ldns-gen-zone -s v -d 'Show version and exit'

