# ldns-config
# Autogenerated from man page /usr/share/man/man1/ldns-config.1.gz
complete -c ldns-config -l cflags -d 'Show the C compiler flags needed to compile with ldns'
complete -c ldns-config -l libs -d 'Show the flags to be used to link with ldns'
complete -c ldns-config -l version -d 'Shows the ldns version of the installed ldns library'
complete -c ldns-config -l libversion -d 'Shows version of the binary api of the installed ldns library'
complete -c ldns-config -l help -d 'Show ldns-config usage description'

