# ldns-zcat
# Autogenerated from man page /usr/share/man/man1/ldns-zcat.1.gz
complete -c ldns-zcat -s o -d 'use ORIGIN when reading in the zone'
complete -c ldns-zcat -s v -d 'show the version number and exit'

