# ldns-compare-zones
# Autogenerated from man page /usr/share/man/man1/ldns-compare-zones.1.gz
complete -c ldns-compare-zones -s c -d 'Print resource records whose owner names are in both zone files, but with dif…'
complete -c ldns-compare-zones -s U -d 'From resource records whose owner names are in both zone files, but with diff…'
complete -c ldns-compare-zones -s u -d 'Print resource records whose owner names are in both zone files, and which re…'
complete -c ldns-compare-zones -s i -d 'Print resource records whose owner names are present only in ZONEFILE2 (a. k'
complete -c ldns-compare-zones -s d -d 'Print resource records whose owner names are present only in ZONEFILE1 (a. k'
complete -c ldns-compare-zones -s a -d 'Print all changes (except unchanged)'
complete -c ldns-compare-zones -s z -d 'Suppress zone sorting; this option is not recommended; it can cause records t…'
complete -c ldns-compare-zones -s s -d 'Do not exclude the SOA record from the comparison'
complete -c ldns-compare-zones -s e -d 'Exit with status code 2 when zones differ'
complete -c ldns-compare-zones -s h -d 'Show usage and exit'
complete -c ldns-compare-zones -s v -d 'Show the version and exit AUTHOR Written by OndÅej SurÃ½ <ondrej@sury'

