# ldns-keygen
# Autogenerated from man page /usr/share/man/man1/ldns-keygen.1.gz
complete -c ldns-keygen -s a -d 'Create a key with this algorithm'
complete -c ldns-keygen -s b -d 'Use this many bits for the key length'
complete -c ldns-keygen -s k -d 'When given, generate a key signing key'
complete -c ldns-keygen -s r -d 'Make ldns-keygen use this file to seed the random generator with'
complete -c ldns-keygen -s s -d 'ldns-keygen will create symbolic links named '
complete -c ldns-keygen -s f -d 'force symlinks to be overwritten if they exist'
complete -c ldns-keygen -s v -d 'Show the version and exit'

