# ldns-read-zone
# Autogenerated from man page /usr/share/man/man1/ldns-read-zone.1.gz
complete -c ldns-read-zone -s 0 -d 'Print a (null) for the RRSIG inception, expiry and key data'
complete -c ldns-read-zone -s b -d 'Include Bubble Babble encoding of DS\'s'
complete -c ldns-read-zone -s c -d 'Canonicalize all resource records in the zone before printing'
complete -c ldns-read-zone -s d -d 'Only print DNSSEC data from the zone'
complete -c ldns-read-zone -s e -d 'Do not print RRs of the given rr type'
complete -c ldns-read-zone -s E -d 'Print only RRs of the given rr type.  This option may be given multiple times'
complete -c ldns-read-zone -s h -d 'Show usage and exit'
complete -c ldns-read-zone -s n -d 'Do not print the SOA record'
complete -c ldns-read-zone -s p -d 'Pad the SOA serial number with spaces so the number and the spaces together t…'
complete -c ldns-read-zone -s s -d 'Strip DNSSEC data from the zone'
complete -c ldns-read-zone -s S -d 'Set serial number to the given number, or when preceded by a sign, offset the…'
complete -c ldns-read-zone -s u -d 'Mark RR type for printing in unknown type format'
complete -c ldns-read-zone -s U -d 'Mark RR type for not printing in unknown type format'
complete -c ldns-read-zone -s v -d 'Show the version and exit'
complete -c ldns-read-zone -s z -d 'Sort the zone before printing (this implies -c) AUTHOR Written by the ldns te…'

