# ldns-notify
# Autogenerated from man page /usr/share/man/man1/ldns-notify.1.gz
complete -c ldns-notify -s z -d 'The zone that is updated'
complete -c ldns-notify -s I -d 'Source IP to send query from'
complete -c ldns-notify -s h -d 'Show usage and exit'
complete -c ldns-notify -s v -d 'Show the version and exit'
complete -c ldns-notify -s s -d 'Append a SOA record indicating the serial number of the updated zone'
complete -c ldns-notify -s p -d 'Use port as destination port (default the DNS port 53) for the UDP packets'
complete -c ldns-notify -s y -d 'Use the given TSIG key and base64-data, and optionally an algorithm to sign t…'
complete -c ldns-notify -s d -d 'Print verbose debug information'
complete -c ldns-notify -s r -d 'Specify the maximum number of retries before notify gives up trying to send t…'

