# ldns-walk
# Autogenerated from man page /usr/share/man/man1/ldns-walk.1.gz
complete -c ldns-walk -s 4 -d 'Use only IPv4'
complete -c ldns-walk -s 6 -d 'Use only IPv6'
complete -c ldns-walk -s f -d 'Do a \'full\' zone walk; by default, ldns-walk will only show the names, and ty…'
complete -c ldns-walk -s s -d 'Start the walk with this owner name'
complete -c ldns-walk -s v -d 'Verbosity level [1-5]'

