# ldns-signzone
# Autogenerated from man page /usr/share/man/man1/ldns-signzone.1.gz
complete -c ldns-signzone -s b -d 'Augments the zone and the RR\'s with extra comment texts for a more readable l…'
complete -c ldns-signzone -s d -d 'Normally, if the DNSKEY RR for a key that is used to sign the zone is not fou…'
complete -c ldns-signzone -s e -d 'Set expiration date of the signatures to this date, the format can be YYYYMMD…'
complete -c ldns-signzone -s f -d 'Use this file to store the signed zone in (default <originalfile>. signed)'
complete -c ldns-signzone -s i -d 'Set inception date of the signatures to this date, the format can be YYYYMMDD…'
complete -c ldns-signzone -s o -d 'Use this as the origin of the zone'
complete -c ldns-signzone -s u -d 'set SOA serial to the number of seconds since 1-1-1970'
complete -c ldns-signzone -s v -d 'Print the version and exit'
complete -c ldns-signzone -s z -d 'Calculate the zone\'s digest and add those as ZONEMD RRs'
complete -c ldns-signzone -s Z -d 'Allow ZONEMDs to be added without signing'
complete -c ldns-signzone -s A -d 'Sign the DNSKEY record with all keys'
complete -c ldns-signzone -s E -d 'Use the EVP cryptographic engine with the given name for signing'
complete -c ldns-signzone -s K -d 'Use the key `key-id\' as the signing key for algorithm `algorithm-id\' as a Key…'
complete -c ldns-signzone -s k -d 'Use the key `key-id\' as the signing key for algorithm `algorithm-id\' as a Zon…'
complete -c ldns-signzone -s n -d 'Use NSEC3 instead of NSEC'
complete -c ldns-signzone -s a -d 'Algorithm used to create the hashed NSEC3 owner names'
complete -c ldns-signzone -s p -d 'Opt-out.  All NSEC3 records in the zone will have the Opt-out flag set'
complete -c ldns-signzone -s s -d Salt
complete -c ldns-signzone -s t -d 'Number of hash iterations'

