# lefty
# Autogenerated from man page /usr/share/man/man1/lefty.1.gz
complete -c lefty -s x -d 'Instructs the editor to exit after processing  file '
complete -c lefty -s e -d '<expression> is parsed and executed'
complete -c lefty -o el -d 'Set error reporting level.  The default value is  0 '
complete -c lefty -o sd -d 'Specifies how much of the stack to show, when an error message is to be print…'
complete -c lefty -o sb -d 'Specifies how much of each function in the stack to show, when an error messa…'
complete -c lefty -o df -d 'Sets the default font'
complete -c lefty -o ps -d 'Specifies a default file name for postscript files'
complete -c lefty -s V -d 'Prints the version'
complete -c lefty -s '?' -d 'Prints the usage and exits.  SEE ALSO lefty user guide'

