# lkbib
# Autogenerated from man page /usr/share/man/man1/lkbib.1.gz
complete -c lkbib -l help -d 'Display a usage message and exit'
complete -c lkbib -s i -d 'When searching files for which no index exists, ignore the contents of fields…'
complete -c lkbib -s p -d 'Search R filename .  Multiple  -p options can be used'
complete -c lkbib -s t -d 'Only require the first  n characters of keys to be given.  Initially  n is\\~6'
complete -c lkbib -s v
complete -c lkbib -l version -d 'Display version information and exit.  ENVIRONMENT REFER Default database'

