# lookbib
# Autogenerated from man page /usr/share/man/man1/lookbib.1.gz
complete -c lookbib -l help -d 'Display a usage message and exit'
complete -c lookbib -s i -d 'When searching files for which no index exists, ignore the contents of fields…'
complete -c lookbib -s t -d 'Only require the first  n characters of keys to be given.  Initially  n is\\~6'
complete -c lookbib -s v
complete -c lookbib -l version -d 'Display version information and exit.  FILES filename . i Index files'

