# lv2apply
# Autogenerated from man page /usr/share/man/man1/lv2apply.1.gz
complete -c lv2apply -s i -d 'Input file'
complete -c lv2apply -s o -d 'Output file'
complete -c lv2apply -s c -d 'Set control port SYM to VAL'
complete -c lv2apply -l help -d 'Display help and exit'
complete -c lv2apply -l version -d 'Display version information and exit'

