# lv2info
# Autogenerated from man page /usr/share/man/man1/lv2info.1.gz
complete -c lv2info -s p -d 'Write Turtle description of plugin to FILE'
complete -c lv2info -s m -d 'Add record of plugin to manifest FILE'
complete -c lv2info -l help -d 'Display help and exit'
complete -c lv2info -l version -d 'Display version information and exit'

