# lv2ls
# Autogenerated from man page /usr/share/man/man1/lv2ls.1.gz
complete -c lv2ls -s n -l names -d 'Show names instead of URIs'
complete -c lv2ls -l help -d 'Display help and exit'
complete -c lv2ls -l version -d 'Display version information and exit'

