# lvchange
# Autogenerated from man page /usr/share/man/man8/lvchange.8.gz
complete -c lvchange -s a -l activate
complete -c lvchange -l activationmode
complete -c lvchange -l addtag
complete -c lvchange -l alloc
complete -c lvchange -s A -l autobackup
complete -c lvchange -l cachemode
complete -c lvchange -l cachepolicy
complete -c lvchange -l cachesettings
complete -c lvchange -l commandprofile
complete -c lvchange -l compression
complete -c lvchange -l config
complete -c lvchange -s C -l contiguous
complete -c lvchange -s d -l debug
complete -c lvchange -l deduplication
complete -c lvchange -l deltag
complete -c lvchange -l detachprofile
complete -c lvchange -l devices
complete -c lvchange -l devicesfile
complete -c lvchange -l discards
complete -c lvchange -l driverloaded
complete -c lvchange -l errorwhenfull
complete -c lvchange -s f -l force
complete -c lvchange -s h -l help
complete -c lvchange -s K -l ignoreactivationskip
complete -c lvchange -l ignorelockingfailure
complete -c lvchange -l ignoremonitoring
complete -c lvchange -l journal
complete -c lvchange -l lockopt
complete -c lvchange -l longhelp
complete -c lvchange -s j -l major
complete -c lvchange -l maxrecoveryrate
complete -c lvchange -l metadataprofile
complete -c lvchange -l minor
complete -c lvchange -l minrecoveryrate
complete -c lvchange -l monitor
complete -c lvchange -l nohints
complete -c lvchange -l nolocking
complete -c lvchange -l noudevsync
complete -c lvchange -s P -l partial
complete -c lvchange -s p -l permission
complete -c lvchange -s M -l persistent
complete -c lvchange -l poll
complete -c lvchange -l profile
complete -c lvchange -s q -l quiet
complete -c lvchange -s r -l readahead
complete -c lvchange -l readonly
complete -c lvchange -l rebuild
complete -c lvchange -l refresh
complete -c lvchange -l reportformat
complete -c lvchange -l resync
complete -c lvchange -s S -l select
complete -c lvchange -s k -l setactivationskip
complete -c lvchange -l setautoactivation
complete -c lvchange -l syncaction
complete -c lvchange -l sysinit
complete -c lvchange -s t -l test
complete -c lvchange -s v -l verbose
complete -c lvchange -l version
complete -c lvchange -l writebehind
complete -c lvchange -l writemostly
complete -c lvchange -s y -l yes
complete -c lvchange -s Z -l zero

