# lvconvert
# Autogenerated from man page /usr/share/man/man8/lvconvert.8.gz
complete -c lvconvert -l alloc
complete -c lvconvert -s b -l background
complete -c lvconvert -s H -l cache
complete -c lvconvert -l cachedevice
complete -c lvconvert -l cachemetadataformat
complete -c lvconvert -l cachemode
complete -c lvconvert -l cachepolicy
complete -c lvconvert -l cachepool
complete -c lvconvert -l cachesettings
complete -c lvconvert -l cachesize
complete -c lvconvert -l cachevol
complete -c lvconvert -s c -l chunksize
complete -c lvconvert -l commandprofile
complete -c lvconvert -l compression
complete -c lvconvert -l config
complete -c lvconvert -s d -l debug
complete -c lvconvert -l deduplication
complete -c lvconvert -l devices
complete -c lvconvert -l devicesfile
complete -c lvconvert -l discards
complete -c lvconvert -l driverloaded
complete -c lvconvert -l errorwhenfull
complete -c lvconvert -s f -l force
complete -c lvconvert -s h -l help
complete -c lvconvert -s i -l interval
complete -c lvconvert -l journal
complete -c lvconvert -l lockopt
complete -c lvconvert -l longhelp
complete -c lvconvert -l merge
complete -c lvconvert -l mergemirrors
complete -c lvconvert -l mergesnapshot
complete -c lvconvert -l mergethin
complete -c lvconvert -l metadataprofile
complete -c lvconvert -l mirrorlog
complete -c lvconvert -s m -l mirrors -o ']Number'
complete -c lvconvert -s n -l name
complete -c lvconvert -l nohints
complete -c lvconvert -l nolocking
complete -c lvconvert -l noudevsync
complete -c lvconvert -l originname
complete -c lvconvert -l poolmetadata
complete -c lvconvert -l poolmetadatasize
complete -c lvconvert -l poolmetadataspare
complete -c lvconvert -l profile
complete -c lvconvert -s q -l quiet
complete -c lvconvert -l raidintegrity
complete -c lvconvert -l raidintegrityblocksize
complete -c lvconvert -l raidintegritymode
complete -c lvconvert -s r -l readahead
complete -c lvconvert -s R -l regionsize
complete -c lvconvert -l repair
complete -c lvconvert -l replace
complete -c lvconvert -s s -l snapshot
complete -c lvconvert -l splitcache
complete -c lvconvert -l splitmirrors
complete -c lvconvert -l splitsnapshot
complete -c lvconvert -l startpoll
complete -c lvconvert -l stripes
complete -c lvconvert -s I -l stripesize
complete -c lvconvert -l swapmetadata
complete -c lvconvert -s t -l test
complete -c lvconvert -s T -l thin
complete -c lvconvert -l thinpool
complete -c lvconvert -l trackchanges
complete -c lvconvert -l type
complete -c lvconvert -l uncache
complete -c lvconvert -l usepolicies
complete -c lvconvert -l vdopool
complete -c lvconvert -s v -l verbose
complete -c lvconvert -l version
complete -c lvconvert -s V -l virtualsize
complete -c lvconvert -s y -l yes
complete -c lvconvert -s Z -l zero

