# lvcreate
# Autogenerated from man page /usr/share/man/man8/lvcreate.8.gz
complete -c lvcreate -s a -l activate
complete -c lvcreate -l addtag
complete -c lvcreate -l alloc
complete -c lvcreate -s A -l autobackup
complete -c lvcreate -s H -l cache
complete -c lvcreate -l cachedevice
complete -c lvcreate -l cachemetadataformat
complete -c lvcreate -l cachemode
complete -c lvcreate -l cachepolicy
complete -c lvcreate -l cachepool
complete -c lvcreate -l cachesettings
complete -c lvcreate -l cachesize
complete -c lvcreate -l cachevol
complete -c lvcreate -s c -l chunksize
complete -c lvcreate -l commandprofile
complete -c lvcreate -l compression
complete -c lvcreate -l config
complete -c lvcreate -s C -l contiguous
complete -c lvcreate -s d -l debug
complete -c lvcreate -l deduplication
complete -c lvcreate -l devices
complete -c lvcreate -l devicesfile
complete -c lvcreate -l discards
complete -c lvcreate -l driverloaded
complete -c lvcreate -l errorwhenfull
complete -c lvcreate -s l -l extents
complete -c lvcreate -s h -l help
complete -c lvcreate -s K -l ignoreactivationskip
complete -c lvcreate -l ignoremonitoring
complete -c lvcreate -l journal
complete -c lvcreate -l lockopt
complete -c lvcreate -l longhelp
complete -c lvcreate -s j -l major
complete -c lvcreate -l maxrecoveryrate
complete -c lvcreate -l metadataprofile
complete -c lvcreate -l minor
complete -c lvcreate -l minrecoveryrate
complete -c lvcreate -l mirrorlog
complete -c lvcreate -s m -l mirrors
complete -c lvcreate -l monitor
complete -c lvcreate -s n -l name
complete -c lvcreate -l nohints
complete -c lvcreate -l nolocking
complete -c lvcreate -l nosync
complete -c lvcreate -l noudevsync
complete -c lvcreate -s p -l permission
complete -c lvcreate -s M -l persistent
complete -c lvcreate -l poolmetadatasize
complete -c lvcreate -l poolmetadataspare
complete -c lvcreate -l profile
complete -c lvcreate -s q -l quiet
complete -c lvcreate -l raidintegrity
complete -c lvcreate -l raidintegrityblocksize
complete -c lvcreate -l raidintegritymode
complete -c lvcreate -s r -l readahead
complete -c lvcreate -s R -l regionsize
complete -c lvcreate -l reportformat
complete -c lvcreate -s k -l setactivationskip
complete -c lvcreate -l setautoactivation
complete -c lvcreate -s L -l size
complete -c lvcreate -s s -l snapshot
complete -c lvcreate -s i -l stripes
complete -c lvcreate -s I -l stripesize
complete -c lvcreate -s t -l test
complete -c lvcreate -s T -l thin
complete -c lvcreate -l thinpool
complete -c lvcreate -l type
complete -c lvcreate -l vdo
complete -c lvcreate -l vdopool
complete -c lvcreate -s v -l verbose
complete -c lvcreate -l version
complete -c lvcreate -s V -l virtualsize
complete -c lvcreate -s W -l wipesignatures
complete -c lvcreate -s y -l yes
complete -c lvcreate -s Z -l zero

