# lvdisplay
# Autogenerated from man page /usr/share/man/man8/lvdisplay.8.gz
complete -c lvdisplay -l aligned
complete -c lvdisplay -s a -l all
complete -c lvdisplay -l binary
complete -c lvdisplay -s c -l colon
complete -c lvdisplay -s C -l columns
complete -c lvdisplay -l commandprofile
complete -c lvdisplay -l config
complete -c lvdisplay -l configreport
complete -c lvdisplay -s d -l debug
complete -c lvdisplay -l devices
complete -c lvdisplay -l devicesfile
complete -c lvdisplay -l driverloaded
complete -c lvdisplay -l foreign
complete -c lvdisplay -s h -l help
complete -c lvdisplay -s H -l history
complete -c lvdisplay -l ignorelockingfailure
complete -c lvdisplay -l journal
complete -c lvdisplay -l lockopt
complete -c lvdisplay -l logonly
complete -c lvdisplay -l longhelp
complete -c lvdisplay -s m -l maps
complete -c lvdisplay -l noheadings
complete -c lvdisplay -l nohints
complete -c lvdisplay -l nolocking
complete -c lvdisplay -l nosuffix
complete -c lvdisplay -s o -l options
complete -c lvdisplay -o o+field1 -o o-field3 -o 'o#field5' -d 'These lists are evaluated from left to right'
complete -c lvdisplay -l profile
complete -c lvdisplay -s q -l quiet
complete -c lvdisplay -l readonly
complete -c lvdisplay -l segments
complete -c lvdisplay -s S -l select
complete -c lvdisplay -l separator
complete -c lvdisplay -l shared
complete -c lvdisplay -s O -l sort
complete -c lvdisplay -s t -l test
complete -c lvdisplay -l unbuffered
complete -c lvdisplay -l units
complete -c lvdisplay -s v -l verbose
complete -c lvdisplay -l version
complete -c lvdisplay -s y -l yes

