# lvextend
# Autogenerated from man page /usr/share/man/man8/lvextend.8.gz
complete -c lvextend -l alloc
complete -c lvextend -s A -l autobackup
complete -c lvextend -l commandprofile
complete -c lvextend -l config
complete -c lvextend -s d -l debug
complete -c lvextend -l devices
complete -c lvextend -l devicesfile
complete -c lvextend -l driverloaded
complete -c lvextend -s l -l extents
complete -c lvextend -s f -l force
complete -c lvextend -s h -l help
complete -c lvextend -l journal
complete -c lvextend -l lockopt
complete -c lvextend -l longhelp
complete -c lvextend -s m -l mirrors
complete -c lvextend -s n -l nofsck
complete -c lvextend -l nohints
complete -c lvextend -l nolocking
complete -c lvextend -l nosync
complete -c lvextend -l noudevsync
complete -c lvextend -l poolmetadatasize
complete -c lvextend -l profile
complete -c lvextend -s q -l quiet
complete -c lvextend -l reportformat
complete -c lvextend -s r -l resizefs
complete -c lvextend -s L -l size
complete -c lvextend -s i -l stripes
complete -c lvextend -s I -l stripesize
complete -c lvextend -s t -l test
complete -c lvextend -l type
complete -c lvextend -l usepolicies
complete -c lvextend -s v -l verbose
complete -c lvextend -l version
complete -c lvextend -s y -l yes

