# lvm-fullreport
# Autogenerated from man page /usr/share/man/man8/lvm-fullreport.8.gz
complete -c lvm-fullreport -l aligned
complete -c lvm-fullreport -s a -l all
complete -c lvm-fullreport -l binary
complete -c lvm-fullreport -l commandprofile
complete -c lvm-fullreport -l config
complete -c lvm-fullreport -l configreport
complete -c lvm-fullreport -s d -l debug
complete -c lvm-fullreport -l devices
complete -c lvm-fullreport -l devicesfile
complete -c lvm-fullreport -l driverloaded
complete -c lvm-fullreport -l foreign
complete -c lvm-fullreport -s h -l help
complete -c lvm-fullreport -l ignorelockingfailure
complete -c lvm-fullreport -l journal
complete -c lvm-fullreport -l lockopt
complete -c lvm-fullreport -l logonly
complete -c lvm-fullreport -l longhelp
complete -c lvm-fullreport -l nameprefixes
complete -c lvm-fullreport -l noheadings
complete -c lvm-fullreport -l nohints
complete -c lvm-fullreport -l nolocking
complete -c lvm-fullreport -l nosuffix
complete -c lvm-fullreport -s o -l options
complete -c lvm-fullreport -o o+field1 -o o-field3 -o 'o#field5' -d 'These lists are evaluated from left to right'
complete -c lvm-fullreport -l profile
complete -c lvm-fullreport -s q -l quiet
complete -c lvm-fullreport -l readonly
complete -c lvm-fullreport -l reportformat
complete -c lvm-fullreport -l rows
complete -c lvm-fullreport -s S -l select
complete -c lvm-fullreport -l separator
complete -c lvm-fullreport -l shared
complete -c lvm-fullreport -s O -l sort
complete -c lvm-fullreport -s t -l test
complete -c lvm-fullreport -l unbuffered
complete -c lvm-fullreport -l units
complete -c lvm-fullreport -l unquoted
complete -c lvm-fullreport -s v -l verbose
complete -c lvm-fullreport -l version
complete -c lvm-fullreport -s y -l yes

