# lvmconfig
# Autogenerated from man page /usr/share/man/man8/lvmconfig.8.gz
complete -c lvmconfig -l atversion
complete -c lvmconfig -l commandprofile
complete -c lvmconfig -l config
complete -c lvmconfig -s d -l debug
complete -c lvmconfig -l devices
complete -c lvmconfig -l devicesfile
complete -c lvmconfig -l driverloaded
complete -c lvmconfig -s f -l file
complete -c lvmconfig -s h -l help
complete -c lvmconfig -l ignoreadvanced
complete -c lvmconfig -l ignorelocal
complete -c lvmconfig -l ignoreunsupported
complete -c lvmconfig -l journal
complete -c lvmconfig -s l -l list
complete -c lvmconfig -l lockopt
complete -c lvmconfig -l longhelp
complete -c lvmconfig -l mergedconfig
complete -c lvmconfig -l metadataprofile
complete -c lvmconfig -l nohints
complete -c lvmconfig -l nolocking
complete -c lvmconfig -l profile
complete -c lvmconfig -s q -l quiet
complete -c lvmconfig -l showdeprecated
complete -c lvmconfig -l showunsupported
complete -c lvmconfig -l sinceversion
complete -c lvmconfig -s t -l test
complete -c lvmconfig -l typeconfig
complete -c lvmconfig -l unconfigured
complete -c lvmconfig -l validate
complete -c lvmconfig -s v -l verbose
complete -c lvmconfig -l version
complete -c lvmconfig -l withcomments
complete -c lvmconfig -l withgeneralpreamble
complete -c lvmconfig -l withlocalpreamble
complete -c lvmconfig -l withspaces
complete -c lvmconfig -l withsummary
complete -c lvmconfig -l withversions
complete -c lvmconfig -s y -l yes

