# lvmdump
# Autogenerated from man page /usr/share/man/man8/lvmdump.8.gz
complete -c lvmdump -s a -d 'Advanced collection'
complete -c lvmdump -s d -d 'Dump into a directory instead of tarball By default, lvmdump will produce a s…'
complete -c lvmdump -s h -d 'Print help message'
complete -c lvmdump -s l -d 'Include lvmetad(8) daemon dump if it is running'
complete -c lvmdump -s m -d 'Gather LVM metadata from the PVs This option generates a 1:1 dump of the meta…'
complete -c lvmdump -s p -d 'Include lvmpolld(8) daemon dump if it is running'
complete -c lvmdump -s s -d 'Gather system info and context'
complete -c lvmdump -s u -d 'Gather udev info and context: /etc/udev/udev'

