# lvmdevices
# Autogenerated from man page /usr/share/man/man8/lvmdevices.8.gz
complete -c lvmdevices -l addev -l deviceidtype -d 'device it will be used, otherwise the device will be added using the type tha…'
complete -c lvmdevices -l adddev
complete -c lvmdevices -l addpvid
complete -c lvmdevices -l check
complete -c lvmdevices -l commandprofile
complete -c lvmdevices -l config
complete -c lvmdevices -s d -l debug
complete -c lvmdevices -l deldev
complete -c lvmdevices -l delpvid
complete -c lvmdevices -l devices
complete -c lvmdevices -l devicesfile
complete -c lvmdevices -l driverloaded
complete -c lvmdevices -s h -l help
complete -c lvmdevices -l journal
complete -c lvmdevices -l lockopt
complete -c lvmdevices -l longhelp
complete -c lvmdevices -l nohints
complete -c lvmdevices -l nolocking
complete -c lvmdevices -l profile
complete -c lvmdevices -s q -l quiet
complete -c lvmdevices -s t -l test
complete -c lvmdevices -l update
complete -c lvmdevices -s v -l verbose
complete -c lvmdevices -l version
complete -c lvmdevices -s y -l yes

