# lvmlockctl
# Autogenerated from man page /usr/share/man/man8/lvmlockctl.8.gz
complete -c lvmlockctl -s h -l help -d 'Show this help information'
complete -c lvmlockctl -s q -l quit -d 'Tell lvmlockd to quit'
complete -c lvmlockctl -s i -l info -d 'Print lock state information from lvmlockd'
complete -c lvmlockctl -s d -l dump -d 'Print log buffer from lvmlockd'
complete -c lvmlockctl -s w -l wait0 -d 'Wait option for other commands'
complete -c lvmlockctl -s f -l force0 -d 'Force option for other commands'
complete -c lvmlockctl -s k -l kill -d 'Kill access to the VG when sanlock cannot renew lease'
complete -c lvmlockctl -s r -l drop -d 'Clear locks for the VG when it is unused after kill (-k)'
complete -c lvmlockctl -s E -l gl-enable -d 'Tell lvmlockd to enable the global lock in a sanlock VG'
complete -c lvmlockctl -s D -l gl-disable -d 'Tell lvmlockd to disable the global lock in a sanlock VG'
complete -c lvmlockctl -l wait -d 'Wait option for other commands'
complete -c lvmlockctl -l force -d 'Force option for other commands'
complete -c lvmlockctl -s S -l stop-lockspaces -d 'Stop all lockspaces'

