# lvresize
# Autogenerated from man page /usr/share/man/man8/lvresize.8.gz
complete -c lvresize -l alloc
complete -c lvresize -s A -l autobackup
complete -c lvresize -l commandprofile
complete -c lvresize -l config
complete -c lvresize -s d -l debug
complete -c lvresize -l devices
complete -c lvresize -l devicesfile
complete -c lvresize -l driverloaded
complete -c lvresize -s l -l extents -o ']Number'
complete -c lvresize -s f -l force
complete -c lvresize -s h -l help
complete -c lvresize -l journal
complete -c lvresize -l lockopt
complete -c lvresize -l longhelp
complete -c lvresize -s n -l nofsck
complete -c lvresize -l nohints
complete -c lvresize -l nolocking
complete -c lvresize -l nosync
complete -c lvresize -l noudevsync
complete -c lvresize -l poolmetadatasize
complete -c lvresize -l profile
complete -c lvresize -s q -l quiet
complete -c lvresize -l reportformat
complete -c lvresize -s r -l resizefs
complete -c lvresize -s L -l size -o ']Size[m'
complete -c lvresize -s i -l stripes
complete -c lvresize -s I -l stripesize
complete -c lvresize -s t -l test
complete -c lvresize -l type
complete -c lvresize -s v -l verbose
complete -c lvresize -l version
complete -c lvresize -s y -l yes

