# lvremove
# Autogenerated from man page /usr/share/man/man8/lvremove.8.gz
complete -c lvremove -s A -l autobackup
complete -c lvremove -l commandprofile
complete -c lvremove -l config
complete -c lvremove -s d -l debug
complete -c lvremove -l devices
complete -c lvremove -l devicesfile
complete -c lvremove -l driverloaded
complete -c lvremove -s f -l force
complete -c lvremove -s h -l help
complete -c lvremove -l journal
complete -c lvremove -l lockopt
complete -c lvremove -l longhelp
complete -c lvremove -l nohints
complete -c lvremove -l nohistory
complete -c lvremove -l nolocking
complete -c lvremove -l noudevsync
complete -c lvremove -l profile
complete -c lvremove -s q -l quiet
complete -c lvremove -l reportformat
complete -c lvremove -s S -l select
complete -c lvremove -s t -l test
complete -c lvremove -s v -l verbose
complete -c lvremove -l version
complete -c lvremove -s y -l yes

