# lvreduce
# Autogenerated from man page /usr/share/man/man8/lvreduce.8.gz
complete -c lvreduce -s A -l autobackup
complete -c lvreduce -l commandprofile
complete -c lvreduce -l config
complete -c lvreduce -s d -l debug
complete -c lvreduce -l devices
complete -c lvreduce -l devicesfile
complete -c lvreduce -l driverloaded
complete -c lvreduce -s l -l extents
complete -c lvreduce -s f -l force
complete -c lvreduce -s h -l help
complete -c lvreduce -l journal
complete -c lvreduce -l lockopt
complete -c lvreduce -l longhelp
complete -c lvreduce -s n -l nofsck
complete -c lvreduce -l nohints
complete -c lvreduce -l nolocking
complete -c lvreduce -l noudevsync
complete -c lvreduce -l profile
complete -c lvreduce -s q -l quiet
complete -c lvreduce -l reportformat
complete -c lvreduce -s r -l resizefs
complete -c lvreduce -s L -l size
complete -c lvreduce -s t -l test
complete -c lvreduce -s v -l verbose
complete -c lvreduce -l version
complete -c lvreduce -s y -l yes

