# lvrename
# Autogenerated from man page /usr/share/man/man8/lvrename.8.gz
complete -c lvrename -s A -l autobackup
complete -c lvrename -l commandprofile
complete -c lvrename -l config
complete -c lvrename -s d -l debug
complete -c lvrename -l devices
complete -c lvrename -l devicesfile
complete -c lvrename -l driverloaded
complete -c lvrename -s h -l help
complete -c lvrename -l journal
complete -c lvrename -l lockopt
complete -c lvrename -l longhelp
complete -c lvrename -l nohints
complete -c lvrename -l nolocking
complete -c lvrename -l noudevsync
complete -c lvrename -l profile
complete -c lvrename -s q -l quiet
complete -c lvrename -l reportformat
complete -c lvrename -s t -l test
complete -c lvrename -s v -l verbose
complete -c lvrename -l version
complete -c lvrename -s y -l yes

