# lvs
# Autogenerated from man page /usr/share/man/man8/lvs.8.gz
complete -c lvs -l aligned
complete -c lvs -s a -l all
complete -c lvs -l binary
complete -c lvs -l commandprofile
complete -c lvs -l config
complete -c lvs -l configreport
complete -c lvs -s d -l debug
complete -c lvs -l devices
complete -c lvs -l devicesfile
complete -c lvs -l driverloaded
complete -c lvs -l foreign
complete -c lvs -s h -l help
complete -c lvs -s H -l history
complete -c lvs -l ignorelockingfailure
complete -c lvs -l journal
complete -c lvs -l lockopt
complete -c lvs -l logonly
complete -c lvs -l longhelp
complete -c lvs -l nameprefixes
complete -c lvs -l noheadings
complete -c lvs -l nohints
complete -c lvs -l nolocking
complete -c lvs -l nosuffix
complete -c lvs -s o -l options
complete -c lvs -o o+field1 -o o-field3 -o 'o#field5' -d 'These lists are evaluated from left to right'
complete -c lvs -l profile
complete -c lvs -s q -l quiet
complete -c lvs -l readonly
complete -c lvs -l reportformat
complete -c lvs -l rows
complete -c lvs -l segments
complete -c lvs -s S -l select
complete -c lvs -l separator
complete -c lvs -l shared
complete -c lvs -s O -l sort
complete -c lvs -s t -l test
complete -c lvs -l unbuffered
complete -c lvs -l units
complete -c lvs -l unquoted
complete -c lvs -s v -l verbose
complete -c lvs -l version
complete -c lvs -s y -l yes

