# lvscan
# Autogenerated from man page /usr/share/man/man8/lvscan.8.gz
complete -c lvscan -s a -l all
complete -c lvscan -s b -l blockdevice
complete -c lvscan -l commandprofile
complete -c lvscan -l config
complete -c lvscan -s d -l debug
complete -c lvscan -l devices
complete -c lvscan -l devicesfile
complete -c lvscan -l driverloaded
complete -c lvscan -s h -l help
complete -c lvscan -l ignorelockingfailure
complete -c lvscan -l journal
complete -c lvscan -l lockopt
complete -c lvscan -l longhelp
complete -c lvscan -l nohints
complete -c lvscan -l nolocking
complete -c lvscan -l profile
complete -c lvscan -s q -l quiet
complete -c lvscan -l readonly
complete -c lvscan -l reportformat
complete -c lvscan -s t -l test
complete -c lvscan -s v -l verbose
complete -c lvscan -l version
complete -c lvscan -s y -l yes

