# MagickCore-config
# Autogenerated from man page /usr/share/man/man1/MagickCore-config.1.gz
complete -c MagickCore-config -l cppflags -d 'Print the compiler flags that are needed to find the ImageMagick 1 C include …'
complete -c MagickCore-config -l prefix -d 'Print the directory under which target specific binaries and executables are …'
complete -c MagickCore-config -l ldflags -d 'Print the linker flags that are needed to link with the ImageMagick 1 library'
complete -c MagickCore-config -l version -d 'Print the version of the ImageMagick 1 distribution to standard output'
complete -c MagickCore-config -l coder-path -d 'Print the path where the ImageMagick 1 coder modules are installed'
complete -c MagickCore-config -l filter-path -d 'Print the path where the ImageMagick 1 filter modules are installed'

