# MagickWand-config
# Autogenerated from man page /usr/share/man/man1/MagickWand-config.1.gz
complete -c MagickWand-config -l cflags -d 'Print the compiler flags that were used to compile   libWand '
complete -c MagickWand-config -l cppflags -d 'Print the preprocessor flags that are needed to find the  Wand C include file…'
complete -c MagickWand-config -l exec-prefix -d 'Print the directory under which target specific binaries and executables are …'
complete -c MagickWand-config -l ldflags -d 'Print the linker flags that are needed to link with the  Wand library'
complete -c MagickWand-config -l libs -d 'Print the linker flags that are needed to link a program with  libWand '
complete -c MagickWand-config -l version -d 'Print the version of the Wand distribution to standard output'

