# mate-desktop-item-edit
# Autogenerated from man page /usr/share/man/man1/mate-desktop-item-edit.1.gz
complete -c mate-desktop-item-edit -l create-new -d 'Create a new file in the given directory'
complete -c mate-desktop-item-edit -l display -d 'X display to use'
complete -c mate-desktop-item-edit -s '?' -s h -l help -d 'Print standard command line options'

