# mate-panel
# Autogenerated from man page /usr/share/man/man1/mate-panel.1.gz
complete -c mate-panel -l replace -d 'Replace a currently running instance of mate-panel'
complete -c mate-panel -l reset -d 'Reset the panel configuration to the default setting'
complete -c mate-panel -l run-dialog -d 'Open the "Run Application" dialog, also accessible by pressing ALT+F2'
complete -c mate-panel -l display -d 'X display to use'
complete -c mate-panel -s '?' -s h -l help -d 'Print standard command line options'

