# mbim-network
# Autogenerated from man page /usr/share/man/man1/mbim-network.1.gz
complete -c mbim-network -l profile -d 'Use the profile in the specified path'
complete -c mbim-network -l help -s h -d 'Show help options'
complete -c mbim-network -l version -d 'Show version . PP Notes:'

