# mdatopbm
# Autogenerated from man page /usr/share/man/man1/mdatopbm.1.gz
complete -c mdatopbm -s a -d 'Generate Plain PBM output instead of Raw PBM'
complete -c mdatopbm -s d -d 'Double the height of the output file, to compensate for the aspect ratio used…'
complete -c mdatopbm -s i -d 'Invert the colors used'

