# metaflac
# Autogenerated from man page /usr/share/man/man1/metaflac.1.gz
complete -c metaflac -l preserve-modtime -d 'Preserve the original modification time in spite of edits'
complete -c metaflac -l with-filename -d 'Prefix each output line with the FLAC file name (the default if more than one…'
complete -c metaflac -l no-filename -d 'Do not prefix each output line with the FLAC file name (the default if only o…'
complete -c metaflac -l no-utf8-convert -d 'Do not convert tags from UTF-8 to local charset, or vice versa'

