# mingle
# Autogenerated from man page /usr/share/man/man1/mingle.1.gz
complete -c mingle -s m -d 'indicates which method to use for bundling'
complete -c mingle -s a -d 'specifies the maximum turning angle, in degrees, as a non-negative real'
complete -c mingle -s c -d 'specifies which compatability measure to use'
complete -c mingle -s i -d 'gives the maximum number of iterative divisions of edges allowd in force-dire…'
complete -c mingle -s k -d 'gives the number of neighbors to be used in forming a nearest neighbor graph'
complete -c mingle -s K -d 'is a positive real value giving the force constant used in force-directed bun…'
complete -c mingle -s o -d 'puts output in file.  Default output is stdout'
complete -c mingle -s p -d 'Except for the force-directed method, bundling minimizes $ink * (k - cos(turn…'
complete -c mingle -s r -d 'is a non-negative integer giving the maximum recursion level used in the aggl…'
complete -c mingle -s T -d 'specifies the output format'
complete -c mingle -s v -d 'determines the verbose level used for tracing the algorithm'
complete -c mingle -s '?' -d 'Print usage and exit'

