# mm2gv
# Autogenerated from man page /usr/share/man/man1/mm2gv.1.gz
complete -c mm2gv -s c -d 'This flag causes mm2gv to assign colors to the edges'
complete -c mm2gv -s l -d 'If set, mm2gv attaches a label to the graph indicating the base name of the i…'
complete -c mm2gv -s u -d 'If specified, the graph is assumed to be undirected'
complete -c mm2gv -s v -d 'This flag causes mm2gv to store the matrix values as the "len" attribute of t…'
complete -c mm2gv -s U -d 'Specifies how square matrices are handled'
complete -c mm2gv -s o -d 'Prints output to the file outfile.  If not given, mm2gv uses stdout'

