# nautilus
# Autogenerated from man page /usr/share/man/man1/nautilus.1.gz
complete -c nautilus -s c -l check -d 'Perform a quick set of self-check tests'
complete -c nautilus -l version -d 'Show the version of the program'
complete -c nautilus -s w -l new-window -d 'Always open a new window for browsing specified URIs'
complete -c nautilus -s q -l quit -d 'Quit Nautilus'
complete -c nautilus -s s -l select -d 'Select specified URI in parent folder'
complete -c nautilus -s h -l help -d 'Show a summary of options'

