# ndctl-list
# Autogenerated from man page /usr/share/man/man1/ndctl-list.1.gz
complete -c ndctl-list -s r -l region
complete -c ndctl-list -s b -l bus
complete -c ndctl-list -s d -l dimm
complete -c ndctl-list -s n -l namespace
complete -c ndctl-list -s t -l type
complete -c ndctl-list -s m -l mode
complete -c ndctl-list -s U -l numa-node
complete -c ndctl-list -s B -l buses
complete -c ndctl-list -s D -l dimms
complete -c ndctl-list -s H -l health
complete -c ndctl-list -s F -l firmware
complete -c ndctl-list -s X -l device-dax
complete -c ndctl-list -s R -l regions
complete -c ndctl-list -s N -l namespaces
complete -c ndctl-list -s i -l idle
complete -c ndctl-list -s c -l configured
complete -c ndctl-list -s C -l capabilities
complete -c ndctl-list -s M -l media-errors
complete -c ndctl-list -s v -l verbose
complete -c ndctl-list -o vv -d 'Everything -v provides, plus automatically enable --dimms,'
complete -c ndctl-list -o vvv -d 'Everything -vv provides, plus --health, --capabilities,'
complete -c ndctl-list -s u -l human

