# ndctl-clear-errors
# Autogenerated from man page /usr/share/man/man1/ndctl-clear-errors.1.gz
complete -c ndctl-clear-errors -s s -l scrub
complete -c ndctl-clear-errors -s v -l verbose
complete -c ndctl-clear-errors -s r -l region
complete -c ndctl-clear-errors -s b -l bus

