# ndctl-monitor
# Autogenerated from man page /usr/share/man/man1/ndctl-monitor.1.gz
complete -c ndctl-monitor -s b -l bus
complete -c ndctl-monitor -s d -l dimm
complete -c ndctl-monitor -s r -l region
complete -c ndctl-monitor -s n -l namespace
complete -c ndctl-monitor -s l -l log
complete -c ndctl-monitor -s c -l config-file
complete -c ndctl-monitor -l daemon
complete -c ndctl-monitor -s D -l dimm-event
complete -c ndctl-monitor -s p -l poll
complete -c ndctl-monitor -s u -l human
complete -c ndctl-monitor -s v -l verbose

