# ndctl-destroy-namespace
# Autogenerated from man page /usr/share/man/man1/ndctl-destroy-namespace.1.gz
complete -c ndctl-destroy-namespace -s r -l region
complete -c ndctl-destroy-namespace -s b -l bus
complete -c ndctl-destroy-namespace -s v -l verbose
complete -c ndctl-destroy-namespace -s f -l force

