# ndctl-write-labels
# Autogenerated from man page /usr/share/man/man1/ndctl-write-labels.1.gz
complete -c ndctl-write-labels -s s -l size
complete -c ndctl-write-labels -s O -l offset
complete -c ndctl-write-labels -s b -l bus
complete -c ndctl-write-labels -s v
complete -c ndctl-write-labels -s i -l input

