# ndctl-check-namespace
# Autogenerated from man page /usr/share/man/man1/ndctl-check-namespace.1.gz
complete -c ndctl-check-namespace -s R -l repair
complete -c ndctl-check-namespace -s L -l rewrite-log
complete -c ndctl-check-namespace -s f -l force
complete -c ndctl-check-namespace -s v -l verbose
complete -c ndctl-check-namespace -s r -l region
complete -c ndctl-check-namespace -s b -l bus

