# ndctl-enable-namespace
# Autogenerated from man page /usr/share/man/man1/ndctl-enable-namespace.1.gz
complete -c ndctl-enable-namespace -s r -l region
complete -c ndctl-enable-namespace -s b -l bus
complete -c ndctl-enable-namespace -s v -l verbose

