# ndctl-write-infoblock
# Autogenerated from man page /usr/share/man/man1/ndctl-write-infoblock.1.gz
complete -c ndctl-write-infoblock -l bus -l region
complete -c ndctl-write-infoblock -s c -l stdout
complete -c ndctl-write-infoblock -s o -l output
complete -c ndctl-write-infoblock -s m -l mode
complete -c ndctl-write-infoblock -s s -l size
complete -c ndctl-write-infoblock -s a -l align
complete -c ndctl-write-infoblock -s u -l uuid
complete -c ndctl-write-infoblock -s M -l map
complete -c ndctl-write-infoblock -s p -l parent-uuid
complete -c ndctl-write-infoblock -s O -l offset
complete -c ndctl-write-infoblock -s r

