# ndctl-init-labels
# Autogenerated from man page /usr/share/man/man1/ndctl-init-labels.1.gz
complete -c ndctl-init-labels -s s -l size
complete -c ndctl-init-labels -s O -l offset
complete -c ndctl-init-labels -s b -l bus
complete -c ndctl-init-labels -s v
complete -c ndctl-init-labels -s f -l force
complete -c ndctl-init-labels -s V -l label-version

