# ndctl-zero-labels
# Autogenerated from man page /usr/share/man/man1/ndctl-zero-labels.1.gz
complete -c ndctl-zero-labels -s s -l size
complete -c ndctl-zero-labels -s O -l offset
complete -c ndctl-zero-labels -s b -l bus
complete -c ndctl-zero-labels -s v

