# ndctl-read-infoblock
# Autogenerated from man page /usr/share/man/man1/ndctl-read-infoblock.1.gz
complete -c ndctl-read-infoblock -l bus -l region
complete -c ndctl-read-infoblock -s V -l verify
complete -c ndctl-read-infoblock -s o -l output
complete -c ndctl-read-infoblock -s j -l json
complete -c ndctl-read-infoblock -s u -l human
complete -c ndctl-read-infoblock -s r

