# ndctl-setup-passphrase
# Autogenerated from man page /usr/share/man/man1/ndctl-setup-passphrase.1.gz
complete -c ndctl-setup-passphrase -s b -l bus
complete -c ndctl-setup-passphrase -s k -l key_handle
complete -c ndctl-setup-passphrase -s m -l master-passphrase
complete -c ndctl-setup-passphrase -s v -l verbose

