# ndctl-read-labels
# Autogenerated from man page /usr/share/man/man1/ndctl-read-labels.1.gz
complete -c ndctl-read-labels -s s -l size
complete -c ndctl-read-labels -s O -l offset
complete -c ndctl-read-labels -s b -l bus
complete -c ndctl-read-labels -s v
complete -c ndctl-read-labels -s I -l index
complete -c ndctl-read-labels -s o -l output
complete -c ndctl-read-labels -s j -l json
complete -c ndctl-read-labels -s u -l human

