# ndctl-update-firmware
# Autogenerated from man page /usr/share/man/man1/ndctl-update-firmware.1.gz
complete -c ndctl-update-firmware -s b -l bus
complete -c ndctl-update-firmware -s f -l firmware
complete -c ndctl-update-firmware -s i -l force
complete -c ndctl-update-firmware -s A -l arm
complete -c ndctl-update-firmware -s D -l disarm
complete -c ndctl-update-firmware -l no-disarm
complete -c ndctl-update-firmware -s v -l verbose

