# ndctl-inject-smart
# Autogenerated from man page /usr/share/man/man1/ndctl-inject-smart.1.gz
complete -c ndctl-inject-smart -s b -l bus
complete -c ndctl-inject-smart -s m -l media-temperature
complete -c ndctl-inject-smart -s M -l media-temperature-threshold
complete -c ndctl-inject-smart -l media-temperature-alarm
complete -c ndctl-inject-smart -l media-temperature-uninject
complete -c ndctl-inject-smart -s c -l ctrl-temperature
complete -c ndctl-inject-smart -s C -l ctrl-temperature-threshold
complete -c ndctl-inject-smart -l ctrl-temperature-alarm
complete -c ndctl-inject-smart -l ctrl-temperature-uninject
complete -c ndctl-inject-smart -s s -l spares
complete -c ndctl-inject-smart -s S -l spares-threshold
complete -c ndctl-inject-smart -l spares-alarm
complete -c ndctl-inject-smart -l spares-uninject
complete -c ndctl-inject-smart -s f -l fatal
complete -c ndctl-inject-smart -l fatal-uninject
complete -c ndctl-inject-smart -s U -l unsafe-shutdown
complete -c ndctl-inject-smart -l unsafe-shutdown-uninject
complete -c ndctl-inject-smart -s N -l uninject-all
complete -c ndctl-inject-smart -s v -l verbose
complete -c ndctl-inject-smart -s u -l human

