# ndctl-check-labels
# Autogenerated from man page /usr/share/man/man1/ndctl-check-labels.1.gz
complete -c ndctl-check-labels -s s -l size
complete -c ndctl-check-labels -s O -l offset
complete -c ndctl-check-labels -s b -l bus
complete -c ndctl-check-labels -s v

