# ndctl-activate-firmware
# Autogenerated from man page /usr/share/man/man1/ndctl-activate-firmware.1.gz
complete -c ndctl-activate-firmware -s n -l dry-run
complete -c ndctl-activate-firmware -l idle -l force -d 'activation.  The overrides are undone before the command completes'
complete -c ndctl-activate-firmware -s I
complete -c ndctl-activate-firmware -s f
complete -c ndctl-activate-firmware -s v -l verbose

