# neon-config
# Autogenerated from man page /usr/share/man/man1/neon-config.1.gz
complete -c neon-config -l cflags -d 'Print the flags which should be passed to the C compiler when compiling objec…'
complete -c neon-config -l libs -d 'Print the flags which should be passed to the linker when linking an applicat…'
complete -c neon-config -l la-file -d 'Print the location of the libtool library script, libneon'
complete -c neon-config -l version -d 'Print the version of the library'
complete -c neon-config -l prefix -d 'If dir is given; relocate output of --cflags and --libs as if neon was instal…'
complete -c neon-config -l support -d 'The script exits with success if feature is supported by the library'
complete -c neon-config -l help -d 'Print help message; includes list of known features and whether they are supp…'

