# nseq
# Autogenerated from man page /usr/share/man/man1/nseq.1ssl.gz
complete -c nseq -o help -d 'Print out a usage message'
complete -c nseq -o in -d 'This specifies the input filename to read or standard input if this option is…'
complete -c nseq -o out -d 'Specifies the output filename or standard output by default'

