# nvidia-cuda-mps-control
# Autogenerated from man page /usr/share/man/man1/nvidia-cuda-mps-control.1.gz
complete -c nvidia-cuda-mps-control -o uid -d 'Start a new MPS server for the specified user (UID)'

