# nvidia-modprobe
# Autogenerated from man page /usr/share/man/man1/nvidia-modprobe.1.gz
complete -c nvidia-modprobe -s v -l version -d 'Print the utility version and exit'
complete -c nvidia-modprobe -s h -l help -d 'Print usage information for the command line options and exit'
complete -c nvidia-modprobe -s c -l create-nvidia-device-file -d 'Create the NVIDIA device file with the given minor number; this option can be…'
complete -c nvidia-modprobe -l module-instance -d 'option is specified on systems with multiple NVIDIA kernel modules, nvidia-mo…'
complete -c nvidia-modprobe -s i -d 'Load the required NVIDIA kernel module that corresponds to the specified  MOD…'
complete -c nvidia-modprobe -s u -l unified-memory -d 'Load the NVIDIA Unified Memory kernel module or create device files for it, i…'

