# onsgmls
# Autogenerated from man page /usr/share/man/man1/onsgmls.1.gz
complete -c onsgmls -o alinktype -l activate
complete -c onsgmls -o Aarchitecture -l architecture
complete -c onsgmls -o bbctf -l bctf -o bencoding -l encoding
complete -c onsgmls -s B -l batch_mode
complete -c onsgmls -s s
complete -c onsgmls -o tfilename -d 'is also specified, then the specified filename will be prefixed to the sysid …'
complete -c onsgmls -o csysid -l catalog
complete -c onsgmls -s c -d 'options are allowed'
complete -c onsgmls -s C -l catalogs
complete -c onsgmls -o Ddirectory -l directory
complete -c onsgmls -s D -d 'options are allowed'
complete -c onsgmls -s e -l open-entities
complete -c onsgmls -o Emax_errors -l max-errors
complete -c onsgmls -o ffile -l error-file
complete -c onsgmls -s g -l open-elements
complete -c onsgmls -s h -l help
complete -c onsgmls -o iname -l include
complete -c onsgmls -s n -l error-numbers
complete -c onsgmls -o ooutput_option -l option
complete -c onsgmls -s o -d 'options are allowed'
complete -c onsgmls -s p -l only-prolog
complete -c onsgmls -s R -l restricted
complete -c onsgmls -l no-output
complete -c onsgmls -o tfile -l rast-file
complete -c onsgmls -s v -l version
complete -c onsgmls -o wtype -l warning
complete -c onsgmls -s w -d 'options are allowed.  The following values of type enable warnings:'
complete -c onsgmls -o wall
complete -c onsgmls -o wno-duplicate -d 'will enable all warnings except those about duplicate entity declarations'
complete -c onsgmls -o wvalid -d 'has the effect of changing the SGML declaration to specify VALIDITY TYPE and …'
complete -c onsgmls -o wno-valid -d 'are specified, then the VALIDITY and IMPLYDEF specified in the SGML declarati…'
complete -c onsgmls -s x -l references
complete -c onsgmls -s d
complete -c onsgmls -o wduplicate
complete -c onsgmls -s l
complete -c onsgmls -o oline
complete -c onsgmls -o msysid
complete -c onsgmls -s r
complete -c onsgmls -o wdefault
complete -c onsgmls -s u
complete -c onsgmls -o wundef

