# openssl-rsa
# Autogenerated from man page /usr/share/man/man1/openssl-rsa.1ssl.gz
complete -c openssl-rsa -o help -d 'Print out a usage message'
complete -c openssl-rsa -o inform -d 'This specifies the input format'
complete -c openssl-rsa -o outform -d 'This specifies the output format, the options have the same meaning and defau…'
complete -c openssl-rsa -o in -d 'This specifies the input filename to read a key from or standard input if thi…'
complete -c openssl-rsa -o passin -d 'The input file password source'
complete -c openssl-rsa -o out -d 'This specifies the output filename to write a key to or standard output if th…'
complete -c openssl-rsa -o passout -d 'The output file password source'
complete -c openssl-rsa -o aes128 -o aes192 -o aes256 -o aria128 -o aria192 -o aria256 -o camellia128 -o camellia192 -o camellia256 -o des -o des3 -o idea -d 'These options encrypt the private key with the specified cipher before output…'
complete -c openssl-rsa -o text -d 'Prints out the various public or private key components in plain text in addi…'
complete -c openssl-rsa -o noout -d 'This option prevents output of the encoded version of the key'
complete -c openssl-rsa -o modulus -d 'This option prints out the value of the modulus of the key'
complete -c openssl-rsa -o check -d 'This option checks the consistency of an \\s-1RSA\\s0 private key'
complete -c openssl-rsa -o pubin -d 'By default a private key is read from the input file: with this option a publ…'
complete -c openssl-rsa -o pubout -d 'By default a private key is output: with this option a public key will be out…'
complete -c openssl-rsa -o RSAPublicKey_in -o RSAPublicKey_out -d 'Like -pubin and -pubout except RSAPublicKey format is used instead'

