# openssl-gendsa
# Autogenerated from man page /usr/share/man/man1/openssl-gendsa.1ssl.gz
complete -c openssl-gendsa -o help -d 'Print out a usage message'
complete -c openssl-gendsa -o out -d 'Output the key to the specified file'
complete -c openssl-gendsa -o aes128 -o aes192 -o aes256 -o aria128 -o aria192 -o aria256 -o camellia128 -o camellia192 -o camellia256 -o des -o des3 -o idea -d 'These options encrypt the private key with specified cipher before outputting…'
complete -c openssl-gendsa -o rand -d 'A file or files containing random data used to seed the random number generat…'
complete -c openssl-gendsa -o writerand -d 'Writes random data to the specified file upon exit'
complete -c openssl-gendsa -o engine -d 'Specifying an engine (by its unique id string) will cause gendsa to attempt t…'

