# openssl-pkcs7
# Autogenerated from man page /usr/share/man/man1/openssl-pkcs7.1ssl.gz
complete -c openssl-pkcs7 -o help -d 'Print out a usage message'
complete -c openssl-pkcs7 -o inform -d 'This specifies the input format'
complete -c openssl-pkcs7 -o outform -d 'This specifies the output format, the options have the same meaning and defau…'
complete -c openssl-pkcs7 -o in -d 'This specifies the input filename to read from or standard input if this opti…'
complete -c openssl-pkcs7 -o out -d 'Specifies the output filename to write to or standard output by default'
complete -c openssl-pkcs7 -o print_certs -d 'Prints out any certificates or CRLs contained in the file'
complete -c openssl-pkcs7 -o text -d 'Prints out certificates details in full rather than just subject and issuer n…'
complete -c openssl-pkcs7 -o noout -d 'Don\'t output the encoded version of the PKCS#7 structure (or certificates is …'

