# openssl-pkey
# Autogenerated from man page /usr/share/man/man1/openssl-pkey.1ssl.gz
complete -c openssl-pkey -o help -d 'Print out a usage message'
complete -c openssl-pkey -o inform -d 'This specifies the input format \\s-1DER\\s0 or \\s-1PEM'
complete -c openssl-pkey -o outform -d 'This specifies the output format, the options have the same meaning and defau…'
complete -c openssl-pkey -o in -d 'This specifies the input filename to read a key from or standard input if thi…'
complete -c openssl-pkey -o passin -d 'The input file password source'
complete -c openssl-pkey -o out -d 'This specifies the output filename to write a key to or standard output if th…'
complete -c openssl-pkey -o passout -d 'The output file password source'
complete -c openssl-pkey -o traditional -d 'Normally a private key is written using standard format: this is PKCS#8 form …'
complete -c openssl-pkey -o text -d 'Prints out the various public or private key components in plain text in addi…'
complete -c openssl-pkey -o text_pub -d 'Print out only public key components even if a private key is being processed'
complete -c openssl-pkey -o noout -d 'Do not output the encoded version of the key'
complete -c openssl-pkey -o pubin -d 'By default a private key is read from the input file: with this option a publ…'
complete -c openssl-pkey -o pubout -d 'By default a private key is output: with this option a public key will be out…'
complete -c openssl-pkey -o engine -d 'Specifying an engine (by its unique id string) will cause pkey to attempt to …'
complete -c openssl-pkey -o check -d 'This option checks the consistency of a key pair for both public and private …'

