# openssl-dhparam
# Autogenerated from man page /usr/share/man/man1/openssl-dhparam.1ssl.gz
complete -c openssl-dhparam -o help -d 'Print out a usage message'
complete -c openssl-dhparam -o inform -d 'This specifies the input format'
complete -c openssl-dhparam -o outform -d 'This specifies the output format, the options have the same meaning and defau…'
complete -c openssl-dhparam -o in -d 'This specifies the input filename to read parameters from or standard input i…'
complete -c openssl-dhparam -o out -d 'This specifies the output filename parameters to'
complete -c openssl-dhparam -o dsaparam -d 'If this option is used, \\s-1DSA\\s0 rather than \\s-1DH\\s0 parameters are read …'
complete -c openssl-dhparam -o check -d 'Performs numerous checks to see if the supplied parameters are valid and disp…'
complete -c openssl-dhparam -s 2 -s 5 -d 'The generator to use, either 2 or 5'
complete -c openssl-dhparam -o rand -d 'A file or files containing random data used to seed the random number generat…'
complete -c openssl-dhparam -o writerand -d 'Writes random data to the specified file upon exit'
complete -c openssl-dhparam -o noout -d 'This option inhibits the output of the encoded version of the parameters'
complete -c openssl-dhparam -o text -d 'This option prints out the \\s-1DH\\s0 parameters in human readable form'
complete -c openssl-dhparam -s C -d 'This option converts the parameters into C code'

