# openssl-crl
# Autogenerated from man page /usr/share/man/man1/openssl-crl.1ssl.gz
complete -c openssl-crl -o help -d 'Print out a usage message'
complete -c openssl-crl -o inform -d 'This specifies the input format'
complete -c openssl-crl -o outform -d 'This specifies the output format, the options have the same meaning and defau…'
complete -c openssl-crl -o in -d 'This specifies the input filename to read from or standard input if this opti…'
complete -c openssl-crl -o out -d 'Specifies the output filename to write to or standard output by default'
complete -c openssl-crl -o text -d 'Print out the \\s-1CRL\\s0 in text form'
complete -c openssl-crl -o nameopt -d 'Option which determines how the subject or issuer names are displayed'
complete -c openssl-crl -o noout -d 'Don\'t output the encoded version of the \\s-1CRL. \\s0'
complete -c openssl-crl -o hash -d 'Output a hash of the issuer name'
complete -c openssl-crl -o hash_old -d 'Outputs the \\*(L"hash\\*(R" of the \\s-1CRL\\s0 issuer name using the older algo…'
complete -c openssl-crl -o issuer -d 'Output the issuer name'
complete -c openssl-crl -o lastupdate -d 'Output the lastUpdate field'
complete -c openssl-crl -o nextupdate -d 'Output the nextUpdate field'
complete -c openssl-crl -o CAfile -d 'Verify the signature on a \\s-1CRL\\s0 by looking up the issuing certificate in…'

