# osage
# Autogenerated from man page /usr/share/man/man1/osage.1.gz
complete -c osage -o Tps
complete -c osage -o Tsvg -o Tsvgz
complete -c osage -o Tfig
complete -c osage -o Tmif
complete -c osage -o Thpgl -o Tpcl
complete -c osage -o Tpng -o Tgif
complete -c osage -o Timap -d 'that has a non-null "href" attribute. ),'
complete -c osage -o Tcmapx -d 'Additional less common or more special-purpose output formats can be found at…'
complete -c osage -s G
complete -c osage -s N
complete -c osage -s E -d 'Example: -Gsize="7,8" -Nshape=box -Efontsize=8'
complete -c osage -o lfile -d 'Usually these define custom shapes or styles'
complete -c osage -o Tlang
complete -c osage -s O -s T
complete -c osage -o ofile
complete -c osage -s x
complete -c osage -o Lg
complete -c osage -o LO
complete -c osage -o Lni
complete -c osage -o LUi
complete -c osage -o LCv
complete -c osage -o LTv
complete -c osage -s v
complete -c osage -s V
complete -c osage -s '?' -d EXAMPLES

