# osgmlnorm
# Autogenerated from man page /usr/share/man/man1/osgmlnorm.1.gz
complete -c osgmlnorm -o aname -l activate
complete -c osgmlnorm -o Aarchitecture -l architecture
complete -c osgmlnorm -o bbctf -l bctf
complete -c osgmlnorm -o csysid -l catalog
complete -c osgmlnorm -s C -l catalogs
complete -c osgmlnorm -s d -l dtd
complete -c osgmlnorm -o Ddirectory -l directory
complete -c osgmlnorm -s e -l open-entities
complete -c osgmlnorm -l error-numbers
complete -c osgmlnorm -s h -l help
complete -c osgmlnorm -o iname -l include
complete -c osgmlnorm -s m -l marked-sections
complete -c osgmlnorm -s n -l comments
complete -c osgmlnorm -s r -l raw
complete -c osgmlnorm -s R -l restricted
complete -c osgmlnorm -s v -l version
complete -c osgmlnorm -o wtype

