# ospam
# Autogenerated from man page /usr/share/man/man1/ospam.1.gz
complete -c ospam -s m -d 'options.  The'
complete -c ospam -s p -d 'option can be used to include the SGML declaration and prolog in the output'
complete -c ospam -s o -d 'option can be used to output other entities.  The'
complete -c ospam -s x -d 'option can be used to expand entity references'
complete -c ospam -o aname -l activate
complete -c ospam -o Aarchitecture -l architecture
complete -c ospam -o bbctf -l bctf
complete -c ospam -o csysid -l catalog
complete -c ospam -s C -l catalogs
complete -c ospam -o Ddirectory -l directory
complete -c ospam -s e -l open-entities
complete -c ospam -o Emax_errors -l max-errors
complete -c ospam -o ffile -l error-file
complete -c ospam -s h -l hoist-omitted-tags
complete -c ospam -o momittag -d or
complete -c ospam -l help
complete -c ospam -o iname -l include
complete -c ospam -s l -l lowercase
complete -c ospam -o mmarkup_option -l markup-option
complete -c ospam -s n -l error-numbers
complete -c ospam -o oname -l output-entity
complete -c ospam -l output-prolog
complete -c ospam -s r -l raw
complete -c ospam -s R -l restricted
complete -c ospam -s v -l version
complete -c ospam -o wtype -l warning
complete -c ospam -l expand-references

