# ospent
# Autogenerated from man page /usr/share/man/man1/ospent.1.gz
complete -c ospent -o bbctf -l bctf
complete -c ospent -o csysid -l catalog
complete -c ospent -s C -l catalogs
complete -c ospent -o Ddirectory -l directory
complete -c ospent -o ffile -l error-file
complete -c ospent -s h -l help
complete -c ospent -s n -l non-sgml
complete -c ospent -s r
complete -c ospent -l raw
complete -c ospent -s R -l restricted
complete -c ospent -s v -l version

