# ostree-summary
# Autogenerated from man page /usr/share/man/man1/ostree-summary.1.gz
complete -c ostree-summary -l update -s u -d 'Update the summary file'
complete -c ostree-summary -l add-metadata -s m -d 'Specify an additional metadata field to add to the summary'
complete -c ostree-summary -l view -s v -d 'View the contents of the summary file in a human readable format'
complete -c ostree-summary -l raw -d 'View the raw bytes of the summary file'
complete -c ostree-summary -l gpg-sign -d 'GPG Key ID to sign the summary with'
complete -c ostree-summary -l gpg-homedir -d 'GPG Homedir to use when looking for keyrings'
complete -c ostree-summary -l sign-type -d 'Use particular signature engine'
complete -c ostree-summary -l sign

