# ostree-checkout
# Autogenerated from man page /usr/share/man/man1/ostree-checkout.1.gz
complete -c ostree-checkout -l user-mode -s U -d 'Do not change file ownership or initialize extended attributes'
complete -c ostree-checkout -l subpath -d 'Checkout sub-directory PATH'
complete -c ostree-checkout -l union -d 'Keep existing directories and unchanged files, overwrite existing files'
complete -c ostree-checkout -l union-add -d 'Keep existing directories and files'
complete -c ostree-checkout -l union-identical -d 'Like --union, but error out if a file would be replaced with a different file'
complete -c ostree-checkout -l whiteouts -d 'Process whiteout files (Docker style)'
complete -c ostree-checkout -l allow-noent -d 'Do nothing if specified path does not exist'
complete -c ostree-checkout -l from-stdin -d 'Process many checkouts from standard input'
complete -c ostree-checkout -l from-file -d 'Process many checkouts from input file'
complete -c ostree-checkout -l fsync -d 'POLICY is a boolean which specifies whether fsync should be used or not'
complete -c ostree-checkout -l require-hardlinks -s H -d 'Do not fall back to full copies if hardlinking fails'
complete -c ostree-checkout -l force-copy-zerosized -s z -d 'This option does nothing; the functionality is now always on by default'
complete -c ostree-checkout -l force-copy -s C -d 'Never hardlink (but may reflink if available)'
complete -c ostree-checkout -l bareuseronly-dirs -s M -d 'Suppress mode bits outside of 0775 for directories (suid, world writable, etc'
complete -c ostree-checkout -l skip-list -d 'Skip checking out the absolute file paths listed in FILE, one per line'
complete -c ostree-checkout -l selinux-policy -d 'Set SELinux labels based on policy in root filesystem PATH (may be /)'

