# ostree-ls
# Autogenerated from man page /usr/share/man/man1/ostree-ls.1.gz
complete -c ostree-ls -l dironly -s d -d 'Do not recurse into directory arguments'
complete -c ostree-ls -l recursive -s R -d 'Print directories recursively'
complete -c ostree-ls -l checksum -s C -d 'Print checksum'
complete -c ostree-ls -l xattrs -s X -d 'Print extended attributes'
complete -c ostree-ls -l nul-filenames-only -d 'Print only filenames, NUL separated'

