# ostree-create-usb
# Autogenerated from man page /usr/share/man/man1/ostree-create-usb.1.gz
complete -c ostree-create-usb -l disable-fsync -d 'Do not invoke fsync()'
complete -c ostree-create-usb -l destination-repo -d 'Create the repository in DEST under MOUNT-PATH, rather than the default locat…'
complete -c ostree-create-usb -l commit -d 'Pull COMMIT instead of whatever REF points to'

