# ostree-init
# Autogenerated from man page /usr/share/man/man1/ostree-init.1.gz
complete -c ostree-init -l mode -d 'Initialize repository in given mode (bare, bare-user, bare-user-only, archive)'
complete -c ostree-init -l collection-id -d 'Set the collection ID of the repository'

