# ostree-sign
# Autogenerated from man page /usr/share/man/man1/ostree-sign.1.gz
complete -c ostree-sign -l verify -d 'Verify signatures'
complete -c ostree-sign -s s -l sign-type -d 'Use particular signature mechanism'
complete -c ostree-sign -l keys-file -d 'Read key(s) from file filename.  Valid for ed25519 signature type'
complete -c ostree-sign -l keys-dir -d 'Redefine the system path, where to search files and subdirectories with well-…'

