# ostree-show
# Autogenerated from man page /usr/share/man/man1/ostree-show.1.gz
complete -c ostree-show -l print-related -d 'Show the "related" commits'
complete -c ostree-show -l print-variant-type -d 'Memory map OBJECT (in this case a filename) to the GVariant type string'
complete -c ostree-show -l print-metadata-key -d 'Print string value of metadata key'
complete -c ostree-show -l print-detached-metadata-key -d 'Print string value of detached metadata key'
complete -c ostree-show -l print-sizes -d 'Show the commit size metadata'
complete -c ostree-show -l raw -d 'Show raw variant data'
complete -c ostree-show -l gpg-homedir -d 'GPG home directory to use when looking for keyrings (if have GPGME - GNU Priv…'

