# ostree-admin-upgrade
# Autogenerated from man page /usr/share/man/man1/ostree-admin-upgrade.1.gz
complete -c ostree-admin-upgrade -l os -d 'Use a different operating system root than the current one'
complete -c ostree-admin-upgrade -l pull-only -d 'Only perform a pull into the repository; do not create a deployment'
complete -c ostree-admin-upgrade -l deploy-only -d 'Create a new deployment from the latest commit in the tracked origin refspec'
complete -c ostree-admin-upgrade -l stage -d 'Perform deployment finalization at shutdown time'
complete -c ostree-admin-upgrade -l reboot -s r -d 'Reboot after a successful upgrade'
complete -c ostree-admin-upgrade -l allow-downgrade -d 'Permit deployment of chronologically older trees'
complete -c ostree-admin-upgrade -l override-commit -d 'Deploy CHECKSUM instead of the latest tree'

