# ostree-find-remotes
# Autogenerated from man page /usr/share/man/man1/ostree-find-remotes.1.gz
complete -c ostree-find-remotes -l disable-fsync -d 'Do not invoke fsync()'
complete -c ostree-find-remotes -l finders -d 'Use the specified comma separated list of finders rather than the default set'
complete -c ostree-find-remotes -l pull -d 'Pull the most recent commit found for each ref'
complete -c ostree-find-remotes -l mirror -d 'Do a mirror pull (see the documentation for ostree pull --mirror)'

