# ostree-admin
# Autogenerated from man page /usr/share/man/man1/ostree-admin.1.gz
complete -c ostree-admin -l help -s h -d 'Usage help'
complete -c ostree-admin -l sysroot -d 'Creates a new OSTree sysroot at PATH'
complete -c ostree-admin -l print-current-dir -d 'Prints the full path to the deployment directory for the currently active dep…'

