# ostree-pull-local
# Autogenerated from man page /usr/share/man/man1/ostree-pull-local.1.gz
complete -c ostree-pull-local -l remote -d 'Add REMOTE to refspec'
complete -c ostree-pull-local -l disable-fsync -d 'Do no invoke fsync()'
complete -c ostree-pull-local -l untrusted -d 'Do not trust source, verify checksums and don\\*(Aqt hardlink into source'
complete -c ostree-pull-local -l disable-verify-bindings -d 'Disable verification of commit metadata bindings'

