# ostree-pull
# Autogenerated from man page /usr/share/man/man1/ostree-pull.1.gz
complete -c ostree-pull -l commit-metadata-only -d 'Fetch only the commit metadata'
complete -c ostree-pull -l disable-fsync -d 'Do no invoke fsync()'
complete -c ostree-pull -l localcache-repo -d 'Like git\\*(Aqs clone --reference'
complete -c ostree-pull -l untrusted -d 'Do not trust local sources, verify checksums and don\\*(Aqt hardlink into sour…'
complete -c ostree-pull -l disable-static-deltas -d 'Do not use static deltas'
complete -c ostree-pull -l mirror -d 'Write refs suitable for a mirror, i. e'
complete -c ostree-pull -l subpath -d 'Only pull the provided subpath'
complete -c ostree-pull -l depth -d 'Traverse DEPTH parents (-1=infinite) (default: 0)'
complete -c ostree-pull -l network-retries -d 'Specifies how many times each download should be retried upon error (default:…'
complete -c ostree-pull -l disable-verify-bindings -d 'Disable verification of commit metadata bindings'

