# ostree-trivial-httpd
# Autogenerated from man page /usr/share/man/man1/ostree-trivial-httpd.1.gz
complete -c ostree-trivial-httpd -l daemonize -s d -d 'Fork into background when ready'
complete -c ostree-trivial-httpd -l autoexit -d 'Automatically exit when directory is deleted'
complete -c ostree-trivial-httpd -l port-file -s p -d 'Write port number to PATH (- for standard output)'
complete -c ostree-trivial-httpd -l port -s P -d 'Use the specified TCP port to listen on'
complete -c ostree-trivial-httpd -l force-range-requests -d 'Force range requests by only serving half of files'

