# ostree-refs
# Autogenerated from man page /usr/share/man/man1/ostree-refs.1.gz
complete -c ostree-refs -l list -d 'For historical reasons, refs without this option will strip the specified pre…'
complete -c ostree-refs -l create -d 'Create a ref pointing to the commit EXISTING'
complete -c ostree-refs -l delete -d 'Delete refs which match PREFIX, rather than listing them'
complete -c ostree-refs -l alias -s A -d 'If used with --create, create an alias.  Otherwise just list aliases'
complete -c ostree-refs -l collections -s c -d 'Enable interactions with refs using the combination of their collection IDs a…'
complete -c ostree-refs -l force -d 'When creating NEWREF with --create, allow an existing ref to be updated inste…'

