# ostree-remote
# Autogenerated from man page /usr/share/man/man1/ostree-remote.1.gz
complete -c ostree-remote -l keyring -d nor
complete -c ostree-remote -l stdin -d 'options are given, then keys are imported from the users personal GPG keyring'
complete -c ostree-remote -l set
complete -c ostree-remote -l if-not-exists
complete -c ostree-remote -l force
complete -c ostree-remote -l no-gpg-verify
complete -c ostree-remote -l gpg-import
complete -c ostree-remote -l collection-id
complete -c ostree-remote -s u -l show-urls
complete -c ostree-remote -s k
complete -c ostree-remote -l raw

