# ostree-fsck
# Autogenerated from man page /usr/share/man/man1/ostree-fsck.1.gz
complete -c ostree-fsck -l quiet -s q -d 'Only print error messages'
complete -c ostree-fsck -l delete -d 'Remove corrupted objects'
complete -c ostree-fsck -l add-tombstones -d 'Add tombstone commit for referenced but missing commits'
complete -c ostree-fsck -l verify-bindings -d 'Verify that the commits pointed to by each ref have that ref in the binding s…'
complete -c ostree-fsck -l verify-back-refs -d 'Verify that all the refs listed in a commit\'s ref-bindings point to that comm…'

