# ostree-admin-deploy
# Autogenerated from man page /usr/share/man/man1/ostree-admin-deploy.1.gz
complete -c ostree-admin-deploy -l os -d 'Use a different operating system root than the current one'
complete -c ostree-admin-deploy -l origin-file -d 'Use FILENAME as the origin, which is where OSTree will look for updated versi…'
complete -c ostree-admin-deploy -l retain -d 'Do not delete previous deployment'
complete -c ostree-admin-deploy -l retain-pending -d 'Do not delete pending deployments'
complete -c ostree-admin-deploy -l retain-rollback -d 'Do not delete rollback deployments'
complete -c ostree-admin-deploy -l not-as-default -d 'Append rather than prepend new deployment'
complete -c ostree-admin-deploy -l karg-proc-cmdline -d 'Import current /proc/cmdline'
complete -c ostree-admin-deploy -l karg -d 'Set kernel argument, like root=/dev/sda1; this overrides any earlier argument…'
complete -c ostree-admin-deploy -l karg-append -d 'Append kernel argument; useful with e. g'

