# paccache
# Autogenerated from man page /usr/share/man/man8/paccache.8.gz
complete -c paccache -s a -l arch -d 'Scan for packages for a specific architecture'
complete -c paccache -l min-atime -l min-mtime -d 'Only consider packages for removal with atime respectively mtime older than s…'
complete -c paccache -s c -l cachedir -d 'Specify a different cache directory.  This option can be used more than once'
complete -c paccache -s f -l force -d 'Apply force to mv and rm operations'
complete -c paccache -s h -l help -d 'Display syntax and command line options'
complete -c paccache -s i -l ignore -d 'Specify packages to ignore, comma-separated'
complete -c paccache -s k -l keep -d 'Specify how many versions of each package are kept in the cache directory, de…'
complete -c paccache -l nocolor -d 'Remove color from the output'
complete -c paccache -s q -l quiet -d 'Minimize the output'
complete -c paccache -s u -l uninstalled -d 'Target uninstalled packages'
complete -c paccache -s v -l verbose -d 'Increase verbosity, can be specified up to 3 times'
complete -c paccache -s z -l null -d 'Use null delimiters for candidate names (only with -v and -vv)'
complete -c paccache -s d -l dryrun
complete -c paccache -s m -l move
complete -c paccache -s r -l remove

