# pacdiff
# Autogenerated from man page /usr/share/man/man8/pacdiff.8.gz
complete -c pacdiff -s l -l locate -d 'Scan using locate'
complete -c pacdiff -s f -l find -d 'Scan using find'
complete -c pacdiff -s p -l pacmandb -d 'Scan active config files from Pacman database.  (default)'
complete -c pacdiff -s o -l output -d 'Print files instead of merging them'
complete -c pacdiff -l nocolor -d 'Remove colors from output'

