# pactree
# Autogenerated from man page /usr/share/man/man8/pactree.8.gz
complete -c pactree -s a -l ascii -d 'Use ASCII characters for tree formatting'
complete -c pactree -s b -l dbpath -d 'Specify an alternative database location'
complete -c pactree -s c -l color -d 'Colorize output'
complete -c pactree -s d -l depth -d 'Limits the number of levels of dependency to show'
complete -c pactree -s g -l graph -d 'Generate a Graphviz description'
complete -c pactree -s h -l help -d 'Output syntax and command-line options'
complete -c pactree -s l -l linear -d 'Prints package names at the start of each line, one per line'
complete -c pactree -s r -l reverse -d 'Show packages that depend on the named package'
complete -c pactree -s s -l sync -d 'Read package data from sync databases instead of local database'
complete -c pactree -s u -l unique -d 'List dependent packages once.  Implies --linear'
complete -c pactree -s o -l optional -d 'Additionally prints optional dependencies up to a certain depth, default 1 fo…'
complete -c pactree -l config -d 'Specify an alternate pacman configuration file'
complete -c pactree -l debug -d 'Print log messages produced by libalpm'
complete -c pactree -l gpgdir -d 'Specify an alternate GnuPG directory for verifying database signatures (defau…'

