# pamaddnoise
# Autogenerated from man page /usr/share/man/man1/pamaddnoise.1.gz
complete -c pamaddnoise -o lambda -d 'Used for poisson noise only.   The default value is 0. 05'
complete -c pamaddnoise -o lsigma -d 'Used for laplacian noise only.   The default value is 10. 0'
complete -c pamaddnoise -o mgsigma -d 'Used for multiplicative gaussian noise only.   The default value is 0. 5'
complete -c pamaddnoise -o seed -d 'Used for all noise types'
complete -c pamaddnoise -o sigma1 -d 'Used for gaussian noise only.   The default value is 4. 0'
complete -c pamaddnoise -o sigma2 -d 'Used for gaussian noise only.   The default value is 20. 0'
complete -c pamaddnoise -o tolerance -d 'Used for impulse noise only.   The default value is 0. 10'
complete -c pamaddnoise -o type -d 'Select type of noise by name'

