# pamarith
# Autogenerated from man page /usr/share/man/man1/pamarith.1.gz
complete -c pamarith -o divide
complete -c pamarith -o difference -o minimum -o maximum -o mean -d 'and -compare'
complete -c pamarith -o compare -d '(Before Netpbm 10. 14 (February 2003), there was no exception for'
complete -c pamarith -o 'compare;' -d 'was at least 2, and sometime between 10. 18 and 10'
complete -c pamarith -o nand -o nor -o xor -o shiftleft
complete -c pamarith -o shiftright
complete -c pamarith -o subtract -d 'value in the left input image'
complete -c pamarith -o multiply -d 'tends to produce nonobvious results because of the way pamarith interprets sa…'
complete -c pamarith -o and -o or -d 'consider the input and output images to contain bit strings; they compute bit…'

