# pamac
# Autogenerated from man page /usr/share/man/man8/pamac.8.gz
complete -c pamac -l installed -s i
complete -c pamac -l repos -s r
complete -c pamac -l aur -s a
complete -c pamac -l no-aur
complete -c pamac -l files -s f
complete -c pamac -l quiet -s q
complete -c pamac -l explicitly-installed -s e
complete -c pamac -l orphans -s o
complete -c pamac -l foreign -s m
complete -c pamac -l groups -s g
complete -c pamac -l ignore
complete -c pamac -l overwrite
complete -c pamac -l download-only -s w
complete -c pamac -l dry-run -s d
complete -c pamac -l as-deps
complete -c pamac -l as-explicit
complete -c pamac -l upgrade
complete -c pamac -l no-upgrade
complete -c pamac -l no-confirm
complete -c pamac -l unneeded -s u
complete -c pamac -l no-orphans
complete -c pamac -l no-save -s n
complete -c pamac -l builddir
complete -c pamac -l devel -d 'pamac. conf is used'
complete -c pamac -l no-devel
complete -c pamac -l force-refresh
complete -c pamac -l enable-downgrade
complete -c pamac -l disable-downgrade
complete -c pamac -l recurse
complete -c pamac -l keep -s k
complete -c pamac -l no-keep
complete -c pamac -l no-clone
complete -c pamac -l uninstalled
complete -c pamac -l build-files -s b
complete -c pamac -l verbose -s v

