# pambayer
# Autogenerated from man page /usr/share/man/man1/pambayer.1.gz
complete -c pambayer -o type -d 'This tells which Bayer pattern the input is:'
complete -c pambayer -o nointerpolate -d 'Each output pixel position corresponds to one position in the input Bayer pat…'
complete -c pambayer -o noninterpolate -d 'what the camera saw, on which you might do further processing'

