# pamcut
# Autogenerated from man page /usr/share/man/man1/pamcut.1.gz
complete -c pamcut -o left -d 'The column number of the leftmost column to be in the output'
complete -c pamcut -o right -d 'The column number of the rightmost column to be in the output, numbered the s…'
complete -c pamcut -o top -d 'The row number of the topmost row to be in the output'
complete -c pamcut -o bottom -d 'The row number of the bottom-most row to be in the output, numbered the same …'
complete -c pamcut -o width -d 'The number of columns to be in the output.   Must be positive'
complete -c pamcut -o height -d 'The number of rows to be in the output.   Must be positive'
complete -c pamcut -o pad -d 'If the rectangle you specify is not entirely within the input image, pamcut f…'
complete -c pamcut -o verbose -d 'Print information about the processing to Standard Error'

