# pamcomp
# Autogenerated from man page /usr/share/man/man1/pamcomp.1.gz
complete -c pamcomp -o align -d 'This option selects the basic horizontal position of the overlay image with r…'
complete -c pamcomp -o valign -d 'This option selects the basic vertical position of the overlay image with res…'
complete -c pamcomp -o xoff -d 'This option modifies the horizontal positioning of the overlay image with res…'
complete -c pamcomp -o yoff -d 'This option modifies the vertical positioning of the overlay image with respe…'
complete -c pamcomp -o alpha -d 'This option names a file that contains the alpha mask'
complete -c pamcomp -o invert -d 'This option inverts the sense of the values in the alpha mask, which  effecti…'
complete -c pamcomp -o opacity -d 'This option tells how opaque the overlay image is to be, i. e'
complete -c pamcomp -o mixtransparency -d 'This option controls what pamcomp does where both the underlying and overlay …'
complete -c pamcomp -o linear -d 'This option indicates that the inputs are not true Netpbm images but rather a…'

