# pamdeinterlace
# Autogenerated from man page /usr/share/man/man1/pamdeinterlace.1.gz
complete -c pamdeinterlace -o takeodd -d 'Take the odd-numbered rows from the input and put them in the output'
complete -c pamdeinterlace -o takeeven -d 'Take the even-numbered rows from the input and put them in the output'

