# pamdice
# Autogenerated from man page /usr/share/man/man1/pamdice.1.gz
complete -c pamdice -o outstem -d 'This option determines the names of the output files'
complete -c pamdice -o width -d 'gives the width in pixels of the output images'
complete -c pamdice -o height -d 'gives the height in pixels of the output images'
complete -c pamdice -o hoverlap -d 'gives the horizontal overlap in pixels between output images'
complete -c pamdice -o voverlap -d 'gives the vertical overlap in pixels between output images'
complete -c pamdice -o verbose -d 'Print information about the processing to Standard Error'

