# pamflip
# Autogenerated from man page /usr/share/man/man1/pamflip.1.gz
complete -c pamflip -o lr -d 'Flip left for right'
complete -c pamflip -o tb -d 'Flip top for bottom'
complete -c pamflip -o xy -d 'Transpose horizontal for vertical.   I. e'
complete -c pamflip -o ccw -d 'Rotate counterclockwise 90 degrees'
complete -c pamflip -o r180 -d 'Rotate 180 degrees'
complete -c pamflip -o cw -d 'Rotate counterclockwise 270 degrees (clockwise 90 degrees)'
complete -c pamflip -o null -d 'No change'
complete -c pamflip -o xform -d 'Apply all the transforms listed, in order'
complete -c pamflip -o memsize -d 'mebibytes is the size in mebibytes (aka megabytes) of memory available for pa…'
complete -c pamflip -o pagesize -d 'bytes is the size in bytes of a paging unit -- the amount of memory that gets…'
complete -c pamflip -o verbose -d 'This option causes pamflip to issue messages to Standard Error about its prog…'
complete -c pamflip -o leftright
complete -c pamflip -o topbottom
complete -c pamflip -o transpose
complete -c pamflip -o rotate90
complete -c pamflip -o r90
complete -c pamflip -o rotate180
complete -c pamflip -o rotate270
complete -c pamflip -o r270

