# pamfunc
# Autogenerated from man page /usr/share/man/man1/pamfunc.1.gz
complete -c pamfunc -o multiplier -d 'sp This option makes the transfer function that of multiplying by      realnum'
complete -c pamfunc -o divisor -d 'sp This option makes the transfer function that of dividing by      realnum'
complete -c pamfunc -o adder -d 'sp This option makes the transfer function that of adding      integer/maxval'
complete -c pamfunc -o subtractor -d 'sp This option makes the transfer function that of subtracting      integer/m…'
complete -c pamfunc -o min -d 'sp This option makes the transfer function that of taking the maximum of     …'
complete -c pamfunc -o max -d 'sp This option makes the transfer function that of taking the minimum of     …'
complete -c pamfunc -o andmask -d 'sp This option makes the transfer function that of bitwise anding      with h…'
complete -c pamfunc -o ormask -d 'sp This option makes the transfer function that of bitwise      inclusive ori…'
complete -c pamfunc -o xormask -d 'sp This option makes the transfer function that of bitwise      exclusive ori…'
complete -c pamfunc -o not -d 'sp This option makes the transfer function that of bitwise logical      inver…'
complete -c pamfunc -o shiftleft -d 'sp This option makes the transfer function that of bitwise shifting      left…'
complete -c pamfunc -o shiftright -d 'sp This option makes the transfer function that of bitwise shifting      righ…'
complete -c pamfunc -o changemaxval -d 'sp This option tells pamfunc to use a different maxval in the output image th…'

