# pamgauss
# Autogenerated from man page /usr/share/man/man1/pamgauss.1.gz
complete -c pamgauss -o sigma -d 'This is the sigma parameter of the Gaussian function (if it were a Gaussian p…'
complete -c pamgauss -o maxval -d 'This is the maxval for the output image.   It defaults to 255'
complete -c pamgauss -o tupletype -d 'This is the value of the "tuple_type" attribute of the created PAM image'

