# pamlookup
# Autogenerated from man page /usr/share/man/man1/pamlookup.1.gz
complete -c pamlookup -o lookupfile -d 'lookupfile names the file that contains the PAM or PNM image that is the look…'
complete -c pamlookup -o missingcolor -d 'This option is meaningful only if the lookup image (and therefore the  output…'
complete -c pamlookup -o fit -d 'This option says to shrink or expand the lookup image as necessary to fit the…'

