# pammixinterlace
# Autogenerated from man page /usr/share/man/man1/pammixinterlace.1.gz
complete -c pammixinterlace -o filter -d 'This option chooses between one of the three filtering mechanisms'
complete -c pammixinterlace -o adaptive -d 'This option turns on "adaptive" filtering mode'

