# pamperspective
# Autogenerated from man page /usr/share/man/man1/pamperspective.1.gz
complete -c pamperspective -l ulx -d 'This specifies the horizontal coordinate of the upper left   vertex of the qu…'
complete -c pamperspective -l uly -d 'This specifies the vertical coordinate of the upper left vertex   of the quad…'
complete -c pamperspective -l urx -d 'This specifies the horizontal coordinate of the upper right   vertex of the q…'
complete -c pamperspective -l ury -d 'This specifies the vertical coordinate of the upper right vertex   of the qua…'
complete -c pamperspective -l llx -d 'This specifies the horizontal coordinate of the lower left   vertex of the qu…'
complete -c pamperspective -l lly -d 'This specifies the vertical coordinate of the lower left vertex   of the quad…'
complete -c pamperspective -l lrx -d 'This specifies the horizontal coordinate of the lower right   vertex of the q…'
complete -c pamperspective -l lry -d 'This specifies the vertical coordinate of the lower right vertex   of the qua…'
complete -c pamperspective -l input_unit -d 'The input image consists of pixels, which are, from the point of   view of a …'
complete -c pamperspective -l margin -d 'This specifies an area surrounding the frame that is to be   included in the …'
complete -c pamperspective -l bottom_margin -d 'These are like --margin, but they specify only one of    the 4 sides'
complete -c pamperspective -l frame_include -d 'Valid values for bool are:'
complete -c pamperspective -l include -d 'The visible part is made large enough such that every point   (x1,y1), (x2,y2…'
complete -c pamperspective -l height -d 'These specify the size of the output image in horizontal and   vertical direc…'
complete -c pamperspective -l detail -d 'If you do not specify --width, pamperspective   determines the width of the o…'
complete -c pamperspective -l ratio -d 'Valid values for prop are:'
complete -c pamperspective -l output_system -d 'The output image consists of pixels, which are, from the point   of view of a…'
complete -c pamperspective -l interpolation -d 'Usually (centers of) output pixels do not exactly correspond to   (centers of…'
complete -c pamperspective -l upper_left_x
complete -c pamperspective -l upper_left_y
complete -c pamperspective -l upper_right_x
complete -c pamperspective -l upper_right_y
complete -c pamperspective -l lower_left_x
complete -c pamperspective -l lower_left_y
complete -c pamperspective -l lower_right_x
complete -c pamperspective -l lower_right_y
complete -c pamperspective -l input_system
complete -c pamperspective -l width
complete -c pamperspective -l proportion

