# pamstretch
# Autogenerated from man page /usr/share/man/man1/pamstretch.1.gz
complete -c pamstretch -o xscale -d 'This is the horizontal scale factor'
complete -c pamstretch -o yscale -d 'This is the vertical scale factor'
complete -c pamstretch -o blackedge -d 'interpolate to black at right/bottom edges'
complete -c pamstretch -o dropedge -d 'drop one (source) pixel at right/bottom edges'

