# pamsummcol
# Autogenerated from man page /usr/share/man/man1/pamsummcol.1.gz
complete -c pamsummcol -o sum -d 'sp This option makes the summary function addition'
complete -c pamsummcol -o mean -d 'sp This option makes the summary function arithmetic mean'
complete -c pamsummcol -o min -d 'sp This option makes the summary function arithmetic minimum'
complete -c pamsummcol -o max -d 'sp This option makes the summary function arithmetic maximum'

