# pamslice
# Autogenerated from man page /usr/share/man/man1/pamslice.1.gz
complete -c pamslice -o row -d 'This indicates that the slice is to be horizontal -- i. e'
complete -c pamslice -o column -d 'This indicates that the slice is to be vertical -- i. e'
complete -c pamslice -o plane -d 'This specifies that you are interested in only one plane of the image      an…'
complete -c pamslice -o xmgr -d 'This option causes pamslice to format the output as input for a      xmgr so …'

