# pamscale
# Autogenerated from man page /usr/share/man/man1/pamscale.1.gz
complete -c pamscale -o xscale -o yscale -o xyfit -o xyfill -o reduce -d 'and -pixels control the amount of scaling'
complete -c pamscale -o width -o height -d 'you want the resulting image to be'
complete -c pamscale -o xsize -o ysize
complete -c pamscale -o xysize
complete -c pamscale -o pixels -d 'pamscale scales the image down to that number of pixels'
complete -c pamscale -o filter -d 'out just what the function is and what kind of scaling it does'
complete -c pamscale -o linear

