# pamsumm
# Autogenerated from man page /usr/share/man/man1/pamsumm.1.gz
complete -c pamsumm -o sum -d 'sp This option makes the summary function addition'
complete -c pamsumm -o mean -d 'sp This option makes the summary function arithmetic mean'
complete -c pamsumm -o min -d 'sp This option makes the summary function arithmetic minimum'
complete -c pamsumm -o max -d 'sp This option makes the summary function arithmetic maximum'
complete -c pamsumm -o normalize -d 'sp This option causes each sample to be normalized to a fraction      (in the…'
complete -c pamsumm -o brief -d 'sp This option causes pamsumm to display the answer as a bare      number, ra…'

