# pamtotiff
# Autogenerated from man page /usr/share/man/man1/pamtotiff.1.gz
complete -c pamtotiff -o append -d 'file is empty'
complete -c pamtotiff -o g4 -o flate -o adobeflate -d 'override the default and set the compression scheme used in creating the outp…'
complete -c pamtotiff -o lsb2msb -d 'order used in creating the file'
complete -c pamtotiff -o fill -d 'shall be zero-filled to a byte boundary'
complete -c pamtotiff -o 2d -o g3 -d 'Fill Order'
complete -c pamtotiff -o color -d 'opposed to grayscale, TIFF image if the input is PPM, even if it contains onl…'
complete -c pamtotiff -o truecolor -d 'form of TIFF output if it is producing a color TIFF image'
complete -c pamtotiff -o indexbits -d 'bit widths you allow'
complete -c pamtotiff -o tag -d Output
complete -c pamtotiff -o output -d 'pamtotiff writes to Standard Output'
complete -c pamtotiff -o yresolution -o resolutionunit -d 'default is inches'

