# pamtosvg
# Autogenerated from man page /usr/share/man/man1/pamtosvg.1.gz
complete -c pamtosvg -o background-color -d 'Treat the specified color as the background color and ignore it'
complete -c pamtosvg -o centerline -d 'Trace an object\'s centerline'
complete -c pamtosvg -o corner-always-threshold -d 'Consider any angle at a pixel which falls below angle angle (in decimal float…'
complete -c pamtosvg -o corner-surround -d 'Consider the specified number of pixels on either side of a point when determ…'
complete -c pamtosvg -o corner-threshold -d 'Consider any pixel which forms an angle with its predecessors and successors …'
complete -c pamtosvg -o error-threshold -d 'Subdivide fitted curves that are offset by a number of pixels exceeding the s…'
complete -c pamtosvg -o filter-iterations -d 'Smooth the curve the specified number of times prior to fitting Default is 4'
complete -c pamtosvg -o line-reversion-threshold -d 'When a spline is closer to a straight line than the specified real number wei…'
complete -c pamtosvg -o line-threshold -d 'If a spline does not deviate from the straight line defined by its endpoints …'
complete -c pamtosvg -o log -d 'Create a log of the curve tracing process (suitable for debugging)'
complete -c pamtosvg -o preserve-width -d 'Preserve line width prior to thinning.   Meaningful only with -centerline'
complete -c pamtosvg -o report-progress -d 'Report the progress of the tracing to Standard Error as it happens'
complete -c pamtosvg -o tangent-surround -d 'Consider the specified number of points to either side of a point when comput…'
complete -c pamtosvg -o width-weight-factor -d 'Weight factor for fitting the linewidth'

