# pamtopfm
# Autogenerated from man page /usr/share/man/man1/pamtopfm.1.gz
complete -c pamtopfm -o scale -d 'sp This specifies the scale factor of the PFM image'
complete -c pamtopfm -o endian -d 'sp This specifies the endianness of the PFM image'

