# pamthreshold
# Autogenerated from man page /usr/share/man/man1/pamthreshold.1.gz
complete -c pamthreshold -o simple -d 'This selects simple or global thresholding, i. e'
complete -c pamthreshold -o local -d 'This selects local adaptive thresholding (also known as dynamic thresholding)…'
complete -c pamthreshold -o dual -d 'This selects a dual thresholding algorithm using a global threshold for low c…'
complete -c pamthreshold -o threshold -d 'This sets the thresholding value for simple or local thresholding'
complete -c pamthreshold -o contrast -d 'This sets the threshold to determine if a neighborhood has low contrast or no…'
complete -c pamthreshold -o quiet

