# pamtojpeg2k
# Autogenerated from man page /usr/share/man/man1/pamtojpeg2k.1.gz
complete -c pamtojpeg2k -o compression -d 'ratio is a floating point number that specifies the compression ratio'
complete -c pamtojpeg2k -o verbose -d 'This option causes pamtojpeg2k to issue informational messages about the conv…'
complete -c pamtojpeg2k -o debuglevel -d 'This option controls debug messages from the Jasper library'

