# pamtopnm
# Autogenerated from man page /usr/share/man/man1/pamtopnm.1.gz
complete -c pamtopnm -o assume -d 'When you specify -assume, you tell pamtopnm that you personally vouch for the…'
complete -c pamtopnm -o ass -d 'SEE ALSO pbmtopgm (1) , pamditherbw (1) , pgmtoppm (1) , ppmtopgm (1) , pam (…'

