# patchwork
# Autogenerated from man page /usr/share/man/man1/patchwork.1.gz
complete -c patchwork -o Tps
complete -c patchwork -o Tsvg -o Tsvgz
complete -c patchwork -o Tfig
complete -c patchwork -o Tmif
complete -c patchwork -o Thpgl -o Tpcl
complete -c patchwork -o Tpng -o Tgif
complete -c patchwork -o Timap -d 'that has a non-null "href" attribute. ),'
complete -c patchwork -o Tcmapx -d 'Additional less common or more special-purpose output formats can be found at…'
complete -c patchwork -s G
complete -c patchwork -s N
complete -c patchwork -s E -d 'Example: -Gsize="7,8" -Nshape=box -Efontsize=8'
complete -c patchwork -o lfile -d 'Usually these define custom shapes or styles'
complete -c patchwork -o Tlang
complete -c patchwork -s O -s T
complete -c patchwork -o ofile
complete -c patchwork -s x
complete -c patchwork -o Lg
complete -c patchwork -o LO
complete -c patchwork -o Lni
complete -c patchwork -o LUi
complete -c patchwork -o LCv
complete -c patchwork -o LTv
complete -c patchwork -s v
complete -c patchwork -s V
complete -c patchwork -s '?' -d EXAMPLES

