# pbmclean
# Autogenerated from man page /usr/share/man/man1/pbmclean.1.gz
complete -c pbmclean -o white -d 'Flip pixels of the specified color'
complete -c pbmclean -o minneighbors -d 'This determines how many pixels must be in a cluster in order for pbmclean to…'
complete -c pbmclean -o extended -d 'pbmclean uses extended, as opposed to basic, isolated pixel detection'
complete -c pbmclean -o black
complete -c pbmclean -o minneighbor

