# pbmtog3
# Autogenerated from man page /usr/share/man/man1/pbmtog3.1.gz
complete -c pbmtog3 -o reversebits -d 'This option causes the output to have the bits in every byte reversed so the …'
complete -c pbmtog3 -o nofixedwidth -d 'Most fax machines expect the image to be 1728 columns wide, so pbmtog3 cuts t…'

