# pbmtextps
# Autogenerated from man page /usr/share/man/man1/pbmtextps.1.gz
complete -c pbmtextps -o font -d 'By default, pbmtextps uses TimesRoman'
complete -c pbmtextps -o fontsize -d 'Size of font in points'
complete -c pbmtextps -o resolution -d 'Resolution in dots per inch of distance measurements pertaining to generation…'
complete -c pbmtextps -o stroke -d 'Width of line to use for stroke font'

