# pbmtoppa
# Autogenerated from man page /usr/share/man/man1/pbmtoppa.1.gz
complete -c pbmtoppa -s v -d 'printer version (720, 820, or 1000)'
complete -c pbmtoppa -s x -d 'horizontal offset adjustment in 1/600 inches'
complete -c pbmtoppa -s y -d 'vertical offset adjustment in 1/600 inches'
complete -c pbmtoppa -s t -d 'top margin in 1/600 inches    (default: 150 = 0. 25 inch)'
complete -c pbmtoppa -s l -d 'left margin in 1/600 inches   (default: 150 = 0. 25 inch)'
complete -c pbmtoppa -s r -d 'right margin in 1/600 inches (default: 150 = 0. 25 inch)'
complete -c pbmtoppa -s b -d 'bottom margin in 1/600 inches (default: 150 = 0. 25 inch)'
complete -c pbmtoppa -s s -d 'paper size: us or a4.   Default is us'
complete -c pbmtoppa -s d -d 'Print resolution in dots per inch'
complete -c pbmtoppa -s f -d 'Read parameters from the configuration file named cfgfile.  See  '
complete -c pbmtoppa -l --------------------Cut
complete -c pbmtoppa -l -------------------------------------------------- -d '   Now you can add an HP720C printer just like any other, using printtool'

