# pbmtopk
# Autogenerated from man page /usr/share/man/man1/pbmtopk.1.gz
complete -c pbmtopk -s s -d 'Sets the design size of the font, in TeX\'s points (72. 27pt to the inch)'
complete -c pbmtopk -s p -d 'Sets the first num font parameters for the font'
complete -c pbmtopk -s C -d 'Sets the coding scheme comment in the TFM file'
complete -c pbmtopk -s F -d 'Sets the font family comment in the TFM file'
complete -c pbmtopk -s f -d 'Reads the file optfile, which should contain a lines of the form:  '
complete -c pbmtopk -s c -d 'Sets the character number of the next bitmap encountered to num'
complete -c pbmtopk -s W -d 'Sets the TFM width of the next character to width (in design size multiples)'
complete -c pbmtopk -s H -d 'Sets the TFM height of the next character to height (in design size multiples)'
complete -c pbmtopk -s D -d 'Sets the TFM depth of the next character to depth (in design size multiples)'
complete -c pbmtopk -s I -d 'Sets the italic correction of the next character to ital (in design size mult…'
complete -c pbmtopk -s h -d 'Sets the horizontal escapement of the next character to horiz (in pixels)'
complete -c pbmtopk -s v -d 'Sets the vertical escapement of the next character to vert (in pixels)'
complete -c pbmtopk -s x -d 'Sets the horizontal offset of the next character to xoff (in pixels)'
complete -c pbmtopk -s y -d 'Sets the vertical offset of the next character to yoff (in pixels, from the t…'

