# pbmtoln03
# Autogenerated from man page /usr/share/man/man1/pbmtoln03.1.gz
complete -c pbmtoln03 -s l -d 'Use \'nn\' as value for left margin (default 0)'
complete -c pbmtoln03 -s r -d 'Use \'nn\' as value for right margin (default 2400)'
complete -c pbmtoln03 -s t -d 'Use \'nn\' as value for top margin (default 0)'
complete -c pbmtoln03 -s b -d 'Use \'nn\' as value for bottom margin (default 3400)'
complete -c pbmtoln03 -s f -d 'Use \'nn\' as value for form length (default 3400)'

