# pbmtopsg3
# Autogenerated from man page /usr/share/man/man1/pbmtopsg3.1.gz
complete -c pbmtopsg3 -o title -d 'The Postscript title value.   Default is no title'
complete -c pbmtopsg3 -o dpi -d 'The resolution of the Postscript output.   Default is 72 dpi'

