# pbmtext
# Autogenerated from man page /usr/share/man/man1/pbmtext.1.gz
complete -c pbmtext -o builtin -d '-builtin selects a font among those built into Netpbm'
complete -c pbmtext -o space -d 'Add pixels pixels of space between characters'
complete -c pbmtext -o lspace -d 'Add pixels pixels of space between lines'
complete -c pbmtext -o nomargins -d 'By default, pbmtext adds margins all around the image as described above'
complete -c pbmtext -o width -d 'This specifies how much horizontal space the text is supposed to fit into'
complete -c pbmtext -o font
complete -c pbmtext -o invert

