# pbmtoepson
# Autogenerated from man page /usr/share/man/man1/pbmtoepson.1.gz
complete -c pbmtoepson -o protocol -d 'This determines which Epson printer protocol the output uses'
complete -c pbmtoepson -o dpi -d 'This specifies the horizontal print density in dots per inch'
complete -c pbmtoepson -o nonadjacent -d 'These options determine whether the output uses \'adjacent dot printing\' or no…'
complete -c pbmtoepson -o adjacent

