# pbmtolj
# Autogenerated from man page /usr/share/man/man1/pbmtolj.1.gz
complete -c pbmtolj -o resolution -d 'Specifies the resolution of the output device, in dpi'
complete -c pbmtolj -o float -d 'Suppresses positioning commands'
complete -c pbmtolj -o noreset -d 'Prevents pbmtolj from writing the reset sequences to the beginning and end of…'
complete -c pbmtolj -o packbits -d 'Enables use of TIFF packbits compression'
complete -c pbmtolj -o delta -d 'Enables use of delta-between-rows compression'
complete -c pbmtolj -o compress -d 'Enables use of both TIFF packbits, and delta-between-rows compression'
complete -c pbmtolj -o copies -d 'Specifies the number of copies.  The default is 1'

