# pcdovtoppm
# Autogenerated from man page /usr/share/man/man1/pcdovtoppm.1.gz
complete -c pcdovtoppm -o wwidth -d 'Maximum width of the result image (default: 1152)'
complete -c pcdovtoppm -o ssize -d 'Maximum size of each of the images (default: 192)'
complete -c pcdovtoppm -o aacross -d 'Maximum number of images across (default: 6)'
complete -c pcdovtoppm -o ccolors -d 'Maximum number of colors, or  n  to mean no quantization'
complete -c pcdovtoppm -o ffont -d 'Font to be used for annotation (default: internal font)'
complete -c pcdovtoppm -s b -d 'Black background color (default)'
complete -c pcdovtoppm -s w -d 'White background color'

