# pdfmom
# Autogenerated from man page /usr/share/man/man1/pdfmom.1.gz
complete -c pdfmom -o Tpdf -d 'option (which is the default), pdfmom processes files using groff\'s native PD…'
complete -c pdfmom -o Tps -d 'is given, processing is passed over to pdfroff , which uses groff \'s PostScri…'
complete -c pdfmom -o mpdfmark -o mom -l no-toc
complete -c pdfmom -s m -d 'options when'
complete -c pdfmom -s v -d 'option, pdfmom simply displays its version information and exits'

