# pdfroff
# Autogenerated from man page /usr/share/man/man1/pdfroff.1.gz
complete -c pdfroff -s h -d 'Same as  --help ; see below'
complete -c pdfroff -s i -d 'Process standard input, after all other specified input files'
complete -c pdfroff -s T -d 'Only  -Tps is supported by  pdfroff '
complete -c pdfroff -s v -d 'Same as  --version ; see below'
complete -c pdfroff -l help -d 'Causes  pdfroff to display a summary of the its usage syntax, and supported o…'
complete -c pdfroff -l emit-ps -d 'Suppresses the final output conversion step, causing  pdfroff to emit PostScr…'
complete -c pdfroff -l keep-temporary-files -d 'Suppresses the deletion of temporary files, which normally occurs after  pdfr…'
complete -c pdfroff -l no-pdf-output -d 'May be used with the  \\%--reference-dictionary= name option (described below)…'
complete -c pdfroff -l no-reference-dictionary -d 'May be used to eliminate the overhead of creating a reference dictionary, whe…'
complete -c pdfroff -l no-toc-relocation -d 'May be used to eliminate the extra  groff processing pass, which is required …'
complete -c pdfroff -l no-kill-null-pages -d 'While preparing for simulation of the manual collation step, which is traditi…'
complete -c pdfroff -l pdf-output -d 'Specifies the name to be used for the resultant PDF document; if unspecified,…'
complete -c pdfroff -l reference-dictionary -d 'Specifies the name to be used for the generated reference dictionary file; if…'
complete -c pdfroff -l report-progress -d 'Causes  pdfroff to display an informational message on standard error, at the…'
complete -c pdfroff -l stylesheet -d 'Specifies the name of an R "input file" , to be used as a style sheet for for…'
complete -c pdfroff -l version -d 'see below'

