# pfmtopam
# Autogenerated from man page /usr/share/man/man1/pfmtopam.1.gz
complete -c pfmtopam -o maxval -d 'sp This specifies the maxval for the PAM.   Default is 255'
complete -c pfmtopam -o verbose -d 'sp This causes pfmtopam to display messages describing       the PFM input fi…'

