# pgmcrater
# Autogenerated from man page /usr/share/man/man1/pgmcrater.1.gz
complete -c pgmcrater -o number -d 'Causes n craters to be generated'
complete -c pgmcrater -o height -d 'Sets the height of the generated image to height pixels'
complete -c pgmcrater -o width -d 'Sets the width of the generated image to width pixels'
complete -c pgmcrater -o xsize -d 'Sets the width of the generated image to width pixels'
complete -c pgmcrater -o ysize -d 'Sets the height of the generated image to height pixels'
complete -c pgmcrater -o gamma -d 'The specified factor is used to gamma adjust the image in the same manner as …'
complete -c pgmcrater -o randomseed -d 'This is the seed for the random number generator that generates the pixels'

