# pgmhist
# Autogenerated from man page /usr/share/man/man1/pgmhist.1.gz
complete -c pgmhist -o median -d 'sp This option causes pgmhist to print the median gray value'
complete -c pgmhist -o quartile -d 'sp This option causes pgmhist to print the four quartile gray values'
complete -c pgmhist -o decile -d 'sp This option causes pgmhist to print the ten decile gray values'
complete -c pgmhist -o forensic -d 'sp With this option, pgmhist works on images that contain invalid gray values'
complete -c pgmhist -o machine -d 'sp This option causes pgmhist to print the information in a way easily digest…'

