# pgmnoise
# Autogenerated from man page /usr/share/man/man1/pgmnoise.1.gz
complete -c pgmnoise -o maxval -d 'The maxval of the generated image. sp Default is 255'
complete -c pgmnoise -o randomseed -d 'This is the seed for the random number generator that generates the pixels'

