# pic2graph
# Autogenerated from man page /usr/share/man/man1/pic2graph.1.gz
complete -c pic2graph -o eqn -d 'Use  delimiters as the opening and closing characters that delimit  eqn direc…'
complete -c pic2graph -o format -d 'Write the image in R output-format , which must be understood by R \\%convert …'
complete -c pic2graph -l help -d 'Display a usage message and exit'
complete -c pic2graph -o unsafe -d 'Run  groff in  unsafe mode, enabling the PIC command  sh to execute arbitrary…'
complete -c pic2graph -o trim -d 'option to the smallest possible bounding box that contains all the black pixe…'
complete -c pic2graph -s v
complete -c pic2graph -l version -d 'Display version information and exit.  ENVIRONMENT %GROFF_TMPDIR'

