# pip-config
# Autogenerated from man page /usr/share/man/man1/pip-config.1.gz
complete -c pip-config -l editor -d 'Editor to use to edit the file'
complete -c pip-config -l global -d 'Use the system-wide configuration file only'
complete -c pip-config -l user -d 'Use the user configuration file only'
complete -c pip-config -l site -d 'Use the current environment configuration file only'

