# pip-debug
# Autogenerated from man page /usr/share/man/man1/pip-debug.1.gz
complete -c pip-debug -l platform -d 'Only use wheels compatible with <platform>'
complete -c pip-debug -l python-version -d 'The Python interpreter version to use for wheel and "Requires-Python" compati…'
complete -c pip-debug -l implementation -d 'Only use wheels compatible with Python implementation <implementation>, e. g'
complete -c pip-debug -l abi -d 'Only use wheels compatible with Python abi <abi>, e. g.  \\(aqpypy_41\\(aq'

