# pktopbm
# Autogenerated from man page /usr/share/man/man1/pktopbm.1.gz
complete -c pktopbm -s c -d 'Sets the character number of the next bitmap written to num'
complete -c pktopbm -s x -d 'Sets the width of the image in columns'
complete -c pktopbm -s y -d 'Sets the height of the image in rows'

