# plistutil
# Autogenerated from man page /usr/share/man/man1/plistutil.1.gz
complete -c plistutil -s i -l infile -d 'Input FILE to convert from'
complete -c plistutil -s o -l outfile -d 'Output FILE to convert to'
complete -c plistutil -s f -l format -d 'Force output format, regardless of input type'
complete -c plistutil -s h -l help -d 'Prints usage information'
complete -c plistutil -s d -l debug -d 'Enabled extended debug output'
complete -c plistutil -s v -l version -d 'Print version information EXAMPLES'

