# pnmalias
# Autogenerated from man page /usr/share/man/man1/pnmalias.1.gz
complete -c pnmalias -o bgcolor -d colorb
complete -c pnmalias -o fgcolor -d colorf
complete -c pnmalias -o bonly
complete -c pnmalias -o fonly
complete -c pnmalias -o balias -d 'background pixels'
complete -c pnmalias -o falias -d 'foreground pixels'
complete -c pnmalias -o weight -d 'for the aliasing filter.   w must be a real number in the range 0 < w < 1'

