# pnmconvol
# Autogenerated from man page /usr/share/man/man1/pnmconvol.1.gz
complete -c pnmconvol -o matrix -d 'The value of the convolution matrix.   See '
complete -c pnmconvol -o matrixfile -d 'This specifies that you are supplying the convolution matrix in a file and na…'
complete -c pnmconvol -o normalize -d 'This option says to adjust the weights in your convolution matrix so they all…'
complete -c pnmconvol -o nooffset -d 'This is part of the obsolete PNM image method of specifying the convolution m…'

