# pnmcolormap
# Autogenerated from man page /usr/share/man/man1/pnmcolormap.1.gz
complete -c pnmcolormap -o sort -d 'This option causes the output colormap to be sorted by the red component inte…'
complete -c pnmcolormap -o square -d 'By default, pnmcolormap produces as the color map a PPM image with one row an…'
complete -c pnmcolormap -o verbose -d 'This option causes pnmcolormap to display messages to Standard Error about th…'
complete -c pnmcolormap -o spreadluminosity -d 'These options control the quantization algorithm.   See  '
complete -c pnmcolormap -o center
complete -c pnmcolormap -o meancolor
complete -c pnmcolormap -o meanpixel
complete -c pnmcolormap -o spreadbrightness

