# pnmcrop
# Autogenerated from man page /usr/share/man/man1/pnmcrop.1.gz
complete -c pnmcrop -o white -d 'Take white to be the background color'
complete -c pnmcrop -o black -d 'Take black to be the background color'
complete -c pnmcrop -o sides -d 'Determine the background color from the colors of the four corners of the inp…'
complete -c pnmcrop -o left -d 'Remove any left border'
complete -c pnmcrop -o right -d 'Remove any right border'
complete -c pnmcrop -o top -d 'Remove any top border'
complete -c pnmcrop -o bottom -d 'Remove any bottom border'
complete -c pnmcrop -o margin -d 'Leave pixels pixels of border.   Expand the border to this size if necessary'
complete -c pnmcrop -o borderfile -d 'Use the image in the file named filename instead of the input image to determ…'
complete -c pnmcrop -o verbose -d 'Print on Standard Error information about the processing, including exactly h…'

