# pnmgamma
# Autogenerated from man page /usr/share/man/man1/pnmgamma.1.gz
complete -c pnmgamma -o bt709tolinear -d 'Convert the image from BT. 709 luminance to radiance.   I. e'
complete -c pnmgamma -o lineartobt709 -d 'Convert the image from radiance to BT. 709 luminance.   I. e'
complete -c pnmgamma -o bt709tosrgb -d 'Convert the image from BT. 709 luminance to SRGB luminance.  I. e'
complete -c pnmgamma -o srgbtobt709 -d 'Convert the image from SRGB luminance to BT. 709 luminance.  I. e'
complete -c pnmgamma -o bt709ramp -d 'Same as -lineartobt709, but using the old syntax'
complete -c pnmgamma -o cieramp -d 'This is an obsolete synonym for -bt709ramp'
complete -c pnmgamma -o srgbramp -d 'Convert the image from radiance to SRGB luminance'
complete -c pnmgamma -o ungamma -d 'Apply the inverse of the specified transfer function (i. e'
complete -c pnmgamma -o gamma -d 'This specifies the gamma value to use in the transfer function'
complete -c pnmgamma -o bgamma -d 'These options are just like -gamma, except they specify the value for a parti…'
complete -c pnmgamma -o maxval -d 'This is the maxval of the output image'
complete -c pnmgamma -o rgamma
complete -c pnmgamma -o ggamma

