# pnmindex
# Autogenerated from man page /usr/share/man/man1/pnmindex.1.gz
complete -c pnmindex -o size -d 'The size of each thumbnail'
complete -c pnmindex -o across -d 'The number of thumbnails in each row.   Default is 6'
complete -c pnmindex -o colors -d 'The maximum number of colors allowed in the overall image'
complete -c pnmindex -o black -d 'This controls the color of the padding between the images; normally it\'s whit…'
complete -c pnmindex -o title -d 'Specifies a title top place at the top of the image.  Default is no title'
complete -c pnmindex -o quant -d 'Enables quantization (to the number of colors specified by -colors)'
complete -c pnmindex -o noquant -d 'See -quant'

