# pnmmontage
# Autogenerated from man page /usr/share/man/man1/pnmmontage.1.gz
complete -c pnmmontage -o data -d 'This option causes pnmmontage to write a file that describes in machine-reada…'
complete -c pnmmontage -o header -d 'Tells pnmmontage to write a C header file of the locations of the original im…'
complete -c pnmmontage -o prefix -d 'Tells pnmmontage to use the specified prefix on all of the #defines it genera…'
complete -c pnmmontage -o quality -d 'Before attempting to place the subimages, pnmmontage will calculate a minimum…'
complete -c pnmmontage -s 0 -s 1 -s 9 -d 'These options control the quality at a higher level than -quality; -0 is the …'
complete -c pnmmontage -o 'quality;' -d 'solution found), while -9 is the best quality (perform an exhaustive search o…'
complete -c pnmmontage -s 5 -d NOTES

