# pnmnorm
# Autogenerated from man page /usr/share/man/man1/pnmnorm.1.gz
complete -c pnmnorm -o wpercent -d 'be mapped by using the -bvalue and -wvalue options'
complete -c pnmnorm -o wvalue -d 'the -bvalue/-wvalue takes precedence, and before that, it\'s a syntax error to…'
complete -c pnmnorm -o bpercent -d 'decimal.   Zero is valid and is the same as -bvalue=0 or'
complete -c pnmnorm -o bvalue
complete -c pnmnorm -o maxexpand -d '50%, regardless of your other options'
complete -c pnmnorm -o midvalue -o middle
complete -c pnmnorm -o keephues -d 'below a target intensity while one of its components is saturated'
complete -c pnmnorm -o luminosity -o colorvalue -o saturation -d 'affect the transfer function (which is the same for all three RGB components)…'

