# pnmpad
# Autogenerated from man page /usr/share/man/man1/pnmpad.1.gz
complete -c pnmpad -o verbose -d 'Verbose output'
complete -c pnmpad -o black -d 'Set pad color.   Default is -black'
complete -c pnmpad -o halign -d 'Specify amount of left and right padding in pixels'
complete -c pnmpad -o valign -d 'These options determine the vertical padding'
complete -c pnmpad -o white
complete -c pnmpad -o left
complete -c pnmpad -o right
complete -c pnmpad -o width
complete -c pnmpad -o top
complete -c pnmpad -o bottom
complete -c pnmpad -o height

