# pnmrotate
# Autogenerated from man page /usr/share/man/man1/pnmrotate.1.gz
complete -c pnmrotate -o background -d 'This determines the color of the background on which the rotated image sits'
complete -c pnmrotate -o noantialias -d 'This option forces pnmrotate to simply move pixels around instead  of synthes…'

