# pnmremap
# Autogenerated from man page /usr/share/man/man1/pnmremap.1.gz
complete -c pnmremap -o mapfile -d 'This names the file that contains the palette image'
complete -c pnmremap -o nofs -d 'These options determine whether pnmremap does Floyd-Steinberg dithering'
complete -c pnmremap -o norandom -d 'This option affects a detail of the Floyd-Steinberg dithering process'
complete -c pnmremap -o firstisdefault -d 'This tells pnmremap to map any input color that is not in the palette to the …'
complete -c pnmremap -o missingcolor -d 'This specifies the default color for pnmremap to map to a color in the input …'
complete -c pnmremap -o verbose -d 'Display helpful messages about the mapping process'
complete -c pnmremap -o floyd
complete -c pnmremap -o fs
complete -c pnmremap -o nofloyd

