# pnmstitch
# Autogenerated from man page /usr/share/man/man1/pnmstitch.1.gz
complete -c pnmstitch -o yrightpos -d 'These are constraints on where pnmstitch stitches the images together'
complete -c pnmstitch -o stitcher -d 'LinearSliver} The default is RotateSliver'
complete -c pnmstitch -o filter -d 'No details available'
complete -c pnmstitch -o output -d 'Name of output file'
complete -c pnmstitch -o verbose -d 'This option causes pnmstitch to issue messages to Standard Error about the st…'
complete -c pnmstitch -o width
complete -c pnmstitch -o height
complete -c pnmstitch -o xrightpos

