# pnmsmooth
# Autogenerated from man page /usr/share/man/man1/pnmsmooth.1.gz
complete -c pnmsmooth -o height -d 'These options specify the dimensions of the convolution matrix'
complete -c pnmsmooth -o size -d 'This deprecated option exists in current Netpbm for backward compatibility'
complete -c pnmsmooth -o dump -d 'This options makes pnmsmooth only show you the convolution matrix'
complete -c pnmsmooth -o width
complete -c pnmsmooth -o matrix -d 'invoke pnmconvol and does not produce an output image'

