# pnmtopclxl
# Autogenerated from man page /usr/share/man/man1/pnmtopclxl.1.gz
complete -c pnmtopclxl -o dpi -d 'This option selects the resolution of the image (not the printer!)'
complete -c pnmtopclxl -o xoffs -d 'This option and -yoffs determine the location on the page of the upper left c…'
complete -c pnmtopclxl -o yoffs -d 'See -xoffs'
complete -c pnmtopclxl -o center -d 'This option tells pnmtopclxl to center each image on the page'
complete -c pnmtopclxl -o duplex -d 'This option causes pnmtopclxl to create a printer stream that prints pages on…'
complete -c pnmtopclxl -o format -d 'This option selects the media (e. g'
complete -c pnmtopclxl -o feeder -d 'This options selects the media source (e. g'
complete -c pnmtopclxl -o copies -d 'This option specifies the number of copies that the printer control stream te…'
complete -c pnmtopclxl -o rendergray -d 'This option causes pnmtopclxl to include in the output stream a command to se…'
complete -c pnmtopclxl -o jobsetup -d 'This option causes pnmtopclxl to include arbitrary job setup PJL commands at …'
complete -c pnmtopclxl -o colorok -d 'This option simply tells pnmtopclxl not to warn you if you supply a color inp…'
complete -c pnmtopclxl -o embedded -d 'Without this option, pnmtopclxl generates an entire printer control stream th…'

