# pnmtotiffcmyk
# Autogenerated from man page /usr/share/man/man1/pnmtotiffcmyk.1.gz
complete -c pnmtotiffcmyk -o none -o packbits -o lzw -o predictor
complete -c pnmtotiffcmyk -o msb2lsb -o lsb2msb
complete -c pnmtotiffcmyk -o rowsperstrip
complete -c pnmtotiffcmyk -o lowdotrange -o highdotrange
complete -c pnmtotiffcmyk -o knormal -o kremove -o konly
complete -c pnmtotiffcmyk -o default -o negative
complete -c pnmtotiffcmyk -o theta
complete -c pnmtotiffcmyk -o gamma
complete -c pnmtotiffcmyk -o gammap

