# pnmtopalm
# Autogenerated from man page /usr/share/man/man1/pnmtopalm.1.gz
complete -c pnmtopalm -o verbose -d 'Display the format of the output file'
complete -c pnmtopalm -o depth -d 'Produce a file of depth N, where N must be either 1, 2, 4, 8, or 16'
complete -c pnmtopalm -o maxdepth -d 'Produce a file of minimal depth, but in any case less than N bits wide'
complete -c pnmtopalm -o offset -d 'Set the nextDepthOffset field in the palm file header to indicate the end of …'
complete -c pnmtopalm -o withdummy -d 'This option tells pnmtopalm to put in the stream, after the image, a dummy im…'
complete -c pnmtopalm -o colormap -d 'Build a custom colormap and include it in the output file'
complete -c pnmtopalm -o transparent -d 'Marks one particular color as fully transparent'
complete -c pnmtopalm -o scanline-compression -d 'Specifies that the output Palm bitmap will use the Palm scanline compression …'
complete -c pnmtopalm -o rle-compression -d 'Specifies that the output Palm bitmap will use the Palm RLE compression scheme'
complete -c pnmtopalm -o packbits-compression -d 'Specifies that the output Palm bitmap will use the Palm packbits compression …'
complete -c pnmtopalm -o density -d 'This specifies the Palm Bitmap density'
complete -c pnmtopalm -l datadir

