# pnmtorle
# Autogenerated from man page /usr/share/man/man1/pnmtorle.1.gz
complete -c pnmtorle -s v -d 'This option will cause pnmtorle to operate in verbose mode'
complete -c pnmtorle -s h -d 'This option allows the header of the Netpbm image to be dumped to \'stderr\' wi…'
complete -c pnmtorle -s a -d 'This option causes pnmtorle to include an alpha channel in the output image'
complete -c pnmtorle -s o -d 'If you specify this option, pnmtorle writes the output to this file'

