# pnmtosgi
# Autogenerated from man page /usr/share/man/man1/pnmtosgi.1.gz
complete -c pnmtosgi -o verbatim -d 'Write an uncompressed file'
complete -c pnmtosgi -o rle -d 'Write a compressed (run length encoded) file'
complete -c pnmtosgi -o imagename -d 'Write the string \'name\' into the imagename field of the header'

