# pnmtojbig
# Autogenerated from man page /usr/share/man/man1/pnmtojbig.1.gz
complete -c pnmtojbig -s q -d 'Encode the image in one single resolution layer (sequential mode)'
complete -c pnmtojbig -s x -d 'Specify the maximal horizontal size of the lowest resolution layer'
complete -c pnmtojbig -s y -d 'Specify the maximal vertical size of the lowest resolution layer'
complete -c pnmtojbig -s l -d 'Select the lowest resolution layer that will be written to the BIE'
complete -c pnmtojbig -s h -d 'Select the highest resolution layer that will be written to the BIE'
complete -c pnmtojbig -s b -d 'Use binary values instead of Gray code words in order to encode pixel values …'
complete -c pnmtojbig -s d -d 'Specify the total number of differential resolution layers into which the inp…'
complete -c pnmtojbig -s s -d 'The JBIG algorithm splits each image into a number of horizontal stripes'
complete -c pnmtojbig -s m -d 'Select the maximum horizontal offset of the adaptive template pixel'
complete -c pnmtojbig -s t -d 'Encode only the specified number of most significant bit planes'
complete -c pnmtojbig -s o -d 'JBIG separates an image into several horizontal stripes, resolution layers an…'
complete -c pnmtojbig -s p -d 'This option allows you to activate or deactivate various optional algorithms …'
complete -c pnmtojbig -s c -d 'The adaptive template pixel movement is determined as suggested in annex C of…'
complete -c pnmtojbig -s v -d 'After pnmtojbig creates the BIE, it lists a few technical details of the crea…'

