# ppmbrighten
# Autogenerated from man page /usr/share/man/man1/ppmbrighten.1.gz
complete -c ppmbrighten -o value -d 'This option specifies the amount, as a per centage, by which you want to chan…'
complete -c ppmbrighten -o saturation -d 'This option specifies the amount, as a per centage, by which you want to chan…'
complete -c ppmbrighten -o normalize -d 'This option causes ppmbrighten to linearly remap the Values of the pixels to …'

