# ppmchange
# Autogenerated from man page /usr/share/man/man1/ppmchange.1.gz
complete -c ppmchange -o closeness -d 'closeness is an integer percentage indicating how close to the color you spec…'
complete -c ppmchange -o closeok -d 'This option affects how ppmchange interprets a color you specify in the argum…'
complete -c ppmchange -o remainder -d 'ppmchange changes all pixels which are not of a color for which you specify a…'

