# ppmcolormask
# Autogenerated from man page /usr/share/man/man1/ppmcolormask.1.gz
complete -c ppmcolormask -o color -d 'This mandatory option specifies the colors that are to be masked (where the i…'

