# ppmdither
# Autogenerated from man page /usr/share/man/man1/ppmdither.1.gz
complete -c ppmdither -o dim -d 'The size of the dithering matrix'
complete -c ppmdither -o red -d 'The number of red shades to be used, including black; minimum of 2'
complete -c ppmdither -o green -d 'The number of green shades to be used, including black; minimum of 2'
complete -c ppmdither -o blue -d 'The number of blue shades to be used, including black; minimum of 2'

