# ppmdraw
# Autogenerated from man page /usr/share/man/man1/ppmdraw.1.gz
complete -c ppmdraw -o script -d 'This option gives the script.   See  . UR #script Script . UE '
complete -c ppmdraw -o scriptfile -d 'This option names a file that contains the script.   - means Standard Input'

