# ppmfade
# Autogenerated from man page /usr/share/man/man1/ppmfade.1.gz
complete -c ppmfade -s f -d 'This is the image file (PPM format) to be used at the beginning of the transi…'
complete -c ppmfade -s l -d 'This is the image file (PPM format) to be used at the ending of the transition'
complete -c ppmfade -o mix -d 'The two images are superimposed with the brightness of the first image decrea…'
complete -c ppmfade -o spread -d 'The pixels in the first image will be moved (spread) further and further from…'
complete -c ppmfade -o shift -d 'The pixels in the first image will be shifted further and further horizontall…'
complete -c ppmfade -o relief -d 'The first image is faded to a Laplacian relief filtered version of the first …'
complete -c ppmfade -o oil -d 'The first image is faded to an \'oil transfer\' version of the first image'
complete -c ppmfade -o edge -d 'The first image is faded to an edge detected version of the first image'
complete -c ppmfade -o bentley -d 'The first image is faded to a \'Bentley Effect\' version of the first image'
complete -c ppmfade -o block -d 'The first image is defocused to small blocks'
complete -c ppmfade -o base -d 'This forms part of the output filenames, as described above'

