# ppmforge
# Autogenerated from man page /usr/share/man/man1/ppmforge.1.gz
complete -c ppmforge -o clouds -d 'Generate clouds.   An image of fractal clouds is generated'
complete -c ppmforge -o dimension -d 'Sets the fractal dimension to the specified dimen, which may be any floating …'
complete -c ppmforge -o glaciers -d 'The floating point level setting controls the extent to which terrain elevati…'
complete -c ppmforge -o hour -d 'When generating a planet, ppmforge uses hour as the \'hour angle at the centra…'
complete -c ppmforge -o ice -d 'Sets the extent of the polar ice caps to the given floating point level'
complete -c ppmforge -o inclination -o tilt -d 'The inclination angle of the planet with regard to its primary star is set to…'
complete -c ppmforge -o mesh -d 'A mesh of size by size will be used for the fast Fourier transform (FFT)'
complete -c ppmforge -o night -d 'A starry sky is generated'
complete -c ppmforge -o power -d 'Sets the \'power factor\' used to scale elevations synthesised from the FFT to …'
complete -c ppmforge -o saturation -d 'Controls the degree of color saturation of the stars that surround planet pic…'
complete -c ppmforge -o seed -d 'Sets the seed for the random number generator to the integer num'
complete -c ppmforge -o stars -d 'Specifies the percentage of pixels, in tenths of a percent, which will appear…'
complete -c ppmforge -o xsize -o width -d 'Sets the width of the generated image to width pixels'
complete -c ppmforge -o ysize -o height -d 'Sets the height of the generated image to height pixels'

