# ppmglobe
# Autogenerated from man page /usr/share/man/man1/ppmglobe.1.gz
complete -c ppmglobe -o background -d 'This specifies the color that goes between the strips'
complete -c ppmglobe -o closeok -d 'This means it is OK if the background isn\'t exactly the color you specify'

