# ppmhist
# Autogenerated from man page /usr/share/man/man1/ppmhist.1.gz
complete -c ppmhist -o sort -d 'The -sort option determines the order in which the colors are listed in the o…'
complete -c ppmhist -o hexcolor -d 'Print the color components in hexadecimal.   See  . UR #output output format '
complete -c ppmhist -o float -d 'Print the color components and the luminosity as floating point numbers in th…'
complete -c ppmhist -o map -d 'Generates a PPM file of the colormap for the image, with the color histogram …'
complete -c ppmhist -o nomap -d 'Generates the histogram for human reading.   This is the default'
complete -c ppmhist -o colorname -d 'Add the color name to the output.   This is the name from the  . UR libppm'
complete -c ppmhist -o noheader -d 'Do not print the column headings'
complete -c ppmhist -o forensic -d 'sp With this option, ppmhist works on images that contain invalid sample valu…'

