# ppmlabel
# Autogenerated from man page /usr/share/man/man1/ppmlabel.1.gz
complete -c ppmlabel -o angle -d 'This option sets the angle of the baseline of subsequent text'
complete -c ppmlabel -o background -d 'If the argument is transparent, ppmlabel draws the text over the existing pix…'
complete -c ppmlabel -o color -d 'This option sets the color for subsequent text'
complete -c ppmlabel -o file -d 'This option causes ppmlabel to read lines of text from the file named filenam…'
complete -c ppmlabel -o size -d 'This option sets the height of the tallest characters above the baseline to t…'
complete -c ppmlabel -o text -d 'This option causes ppmlabel to draw the specified text string'
complete -c ppmlabel -s x -d 'This option sets the pixel column at which subsequent text will be left justi…'
complete -c ppmlabel -s y -d 'This option sets the pixel row which will form the baseline of subsequent text'
complete -c ppmlabel -o colour

