# ppmntsc
# Autogenerated from man page /usr/share/man/man1/ppmntsc.1.gz
complete -c ppmntsc -l pal -d 'Use the PAL transform instead of the default NTSC'
complete -c ppmntsc -l verbose -d 'Print a grand total of the number of illegal pixels'
complete -c ppmntsc -l debug -d 'Produce a humongous listing of illegal colors and their legal counterparts'
complete -c ppmntsc -l legalonly -d 'Output only pixels that are already legal'
complete -c ppmntsc -l illegalonly -d 'Output only pixels that are illegal (and output them uncorrected)'
complete -c ppmntsc -l correctedonly -d 'Output only pixels that are corrected versions of illegal pixels'

