# ppmpat
# Autogenerated from man page /usr/share/man/man1/ppmpat.1.gz
complete -c ppmpat -o gingham2 -d 'A gingham check pattern.   Can be tiled'
complete -c ppmpat -o gingham3 -d 'A slightly more complicated gingham.   Can be tiled'
complete -c ppmpat -o madras -d 'A madras plaid.   Can be tiled'
complete -c ppmpat -o tartan -d 'A tartan plaid.   Can be tiled'
complete -c ppmpat -o poles -d 'Color gradients centered on randomly-placed poles'
complete -c ppmpat -o squig -d 'Squiggley tubular pattern.   Can be tiled'
complete -c ppmpat -o camo -d 'Camouflage pattern'
complete -c ppmpat -o anticamo -d 'Anti-camouflage pattern - like -camo, but ultra-bright colors'
complete -c ppmpat -o randomseed -d 'This is the seed for the random number generator that generates the pixels'

