# ppmrough
# Autogenerated from man page /usr/share/man/man1/ppmrough.1.gz
complete -c ppmrough -o left -d 'Specifies the mean distance of the border from the left margin (default: no b…'
complete -c ppmrough -o right -d 'Specifies the mean distance of the border from the right margin (default: no …'
complete -c ppmrough -o top -d 'Specifies the mean distance of the border from the top margin (default: no bo…'
complete -c ppmrough -o bottom -d 'Specifies the mean distance of the border from the bottom margin (default: no…'
complete -c ppmrough -o width -d 'Specifies the width of the image (default: 100)'
complete -c ppmrough -o height -d 'Specifies the height of the image (default: 100)'
complete -c ppmrough -o bg -d 'Background color'
complete -c ppmrough -o fg -d 'Foreground color'
complete -c ppmrough -o var -d 'Specifies the variance of the ragged border (default: 10)'
complete -c ppmrough -o randomseed -d 'Use this option to initialize the pseudo-random number generator (the Standar…'
complete -c ppmrough -o verbose -d 'Run ppmrough in verbose mode.   It reports all parameters on Standard Error'

