# ppmtopj
# Autogenerated from man page /usr/share/man/man1/ppmtopj.1.gz
complete -c ppmtopj -o rle -d 'Run length encode the image.  (This can result in larger images)'
complete -c ppmtopj -o back -d 'Enhance the foreground by indicating if the background is light or dark compa…'
complete -c ppmtopj -o render -d 'Use an internal rendering algorithm (default dither)'
complete -c ppmtopj -o gamma -d 'Gamma correct the image using the integer int as a gamma (default 0)'
complete -c ppmtopj -o center -d 'Center the image to an 8. 5 by 11 page'
complete -c ppmtopj -o xpos -d 'Move by pos pixels in the x direction'
complete -c ppmtopj -o ypos -d 'Move by pos pixels in the y direction'

