# ppmtolj
# Autogenerated from man page /usr/share/man/man1/ppmtolj.1.gz
complete -c ppmtolj -o delta -d 'Apply delta row compression to reduce the size of the pcl file'
complete -c ppmtolj -o gamma -d 'Gamma correct the image using the integer parameter as a gamma (default 0)'
complete -c ppmtolj -o float -d 'Suppress positioning information'
complete -c ppmtolj -o noreset -d 'Don\'t write the reset sequence to the beginning and end of the output'
complete -c ppmtolj -o resolution -d 'Set the required output resolution 75|100|150|300|600'

