# ppmtopcx
# Autogenerated from man page /usr/share/man/man1/ppmtopcx.1.gz
complete -c ppmtopcx -o 24bit -d 'Produce a 24bit truecolor PCX file, even if the image has 256 colors or fewer'
complete -c ppmtopcx -o 8bit -d 'Produce an 8bit (256 colors) PCX file, even if the image has 16 colors or few…'
complete -c ppmtopcx -o packed -d 'Use \'packed pixel\' format for files with 16 colors or fewer: 1, 2, or 4 bits/…'
complete -c ppmtopcx -o stdpalette -d 'Instead of computing a palette from the colors in the image, use a standard, …'
complete -c ppmtopcx -o palette -d 'Instead of computing the palette from the colors in the image, use the palett…'
complete -c ppmtopcx -o planes -d 'Generate a PCX file with planes planes, even though the number of colors in t…'
complete -c ppmtopcx -o ypos -d 'These options set the position of the image in some field (e. g'
complete -c ppmtopcx -o xpos

