# ppmtoilbm
# Autogenerated from man page /usr/share/man/man1/ppmtoilbm.1.gz
complete -c ppmtoilbm -o maxplanes -o mp -d '(default 5, minimum 1, maximum 16) Maximum planes to write in a normal ILBM'
complete -c ppmtoilbm -o fixplanes -o fp -d '(min 1, max 16) If a normal ILBM is written, it will have exactly <n> planes'
complete -c ppmtoilbm -o hambits -o hamplanes -d '(default 6, min 3, max 16) Select number of planes for HAM picture'
complete -c ppmtoilbm -o normal -d 'Turns off -hamif/-24if/-dcif, -hamforce/-24force/-dcforce and -cmaponly'
complete -c ppmtoilbm -o dcif -d 'Write a HAM/24bit/direct color file if the image does not fit into <maxplanes…'
complete -c ppmtoilbm -o dcforce -d 'Write a HAM/24bit/direct color file'
complete -c ppmtoilbm -o dcplanes -d '(default 5, min 1, max 16)'
complete -c ppmtoilbm -o ecs -d 'Shortcut for: -hamplanes 6 -maxplanes 5 . sp This is the default'
complete -c ppmtoilbm -o aga -d 'Shortcut for: -hamplanes 8 -maxplanes 8'
complete -c ppmtoilbm -o ham6 -d 'Shortcut for: -hamplanes 6 -hamforce'
complete -c ppmtoilbm -o ham8 -d 'Shortcut for: -hamplanes 8 -hamforce'
complete -c ppmtoilbm -o compress -d 'This is the default.  Compress the BODY chunk'
complete -c ppmtoilbm -o cmethod -d 'This option does the same thing as -compress'
complete -c ppmtoilbm -o map -d 'Write a normal ILBM using the colors in <ppmfile> as the colormap'
complete -c ppmtoilbm -o cmaponly -d 'Write a colormap file: only BMHD and CMAP chunks, no BODY chunk, nPlanes = 0'
complete -c ppmtoilbm -o savemem -d 'See the -compress option'
complete -c ppmtoilbm -o 24if -d 'with an error'
complete -c ppmtoilbm -o hamif
complete -c ppmtoilbm -o hamforce
complete -c ppmtoilbm -o 24force
complete -c ppmtoilbm -o dcbits

