# ppmtopjxl
# Autogenerated from man page /usr/share/man/man1/ppmtopjxl.1.gz
complete -c ppmtopjxl -o dither -o cluster -o diffuse -d 'options select ordered dithering, clustered ordered dithering, or error diffu…'
complete -c ppmtopjxl -o ysize -d 'interpreted as the number of dots to set the width or height to, but you may …'
complete -c ppmtopjxl -o xsize
complete -c ppmtopjxl -o yshift -d 'right and down.  SEE ALSO ppm (5) AUTHOR'

