# ppmtowinicon
# Autogenerated from man page /usr/share/man/man1/ppmtowinicon.1.gz
complete -c ppmtowinicon -o andpgms -d 'Include transparency information in the icons.  See the  '
complete -c ppmtowinicon -o output -d 'Name of output file'
complete -c ppmtowinicon -o truetransparent -d 'Make transparency in the icon normal instead of the special reverse video eff…'

