# ppmtoxpm
# Autogenerated from man page /usr/share/man/man1/ppmtoxpm.1.gz
complete -c ppmtoxpm -o name -d 'This option specifies the prefix string which is specified in the resulting X…'
complete -c ppmtoxpm -o hexonly -d 'This option says never to put color names in the XPM file, but rather to iden…'
complete -c ppmtoxpm -o rgb -d 'This option names the file in which the color dictionary you want to use resi…'
complete -c ppmtoxpm -o alphamask -d 'This option names a PGM file to use as an alpha (transparency) mask'

