# pstopnm
# Autogenerated from man page /usr/share/man/man1/pstopnm.1.gz
complete -c pstopnm -o forceplain -d 'forces the output file to be in plain (text) format'
complete -c pstopnm -o llx -d 'selects bx as the lower left corner x coordinate (in inches) on the Postscrip…'
complete -c pstopnm -o lly -d 'selects by as the lower left corner y coordinate (in inches) on the Postscrip…'
complete -c pstopnm -o landscape -d 'renders the image in landscape orientation'
complete -c pstopnm -o portrait -d 'renders the image in portrait orientation. sp See -landscape'
complete -c pstopnm -o nocrop -d 'This option causes pstopnm to make the output image exactly the dimensions of…'
complete -c pstopnm -o ppm -d 'selects the format of the output file'
complete -c pstopnm -o stdout -d 'causes output to go to Standard Output instead of to regular files, one per p…'
complete -c pstopnm -o urx -d 'selects tx as the upper right corner x coordinate (in inches) on the Postscri…'
complete -c pstopnm -o ury -d 'selects ty as the upper right corner y coordinate (in inches) on the Postscri…'
complete -c pstopnm -o verbose -d 'prints processing information to stdout'
complete -c pstopnm -o xborder -d 'specifies that the left and right borders added to the subject image are to b…'
complete -c pstopnm -o xmax -d 'specifies that the output image is to be xmax pixels wide'
complete -c pstopnm -o xsize -d 'specifies that the output image is to be xsize pixels wide.  See  '
complete -c pstopnm -o yborder -d 'specifies that the top and bottom borders added to the subject image are to b…'
complete -c pstopnm -o ymax -d 'specifies that the output image is to be ymax pixels high'
complete -c pstopnm -o ysize -d 'specifies that the output image is to be ymax pixels high.  See  '
complete -c pstopnm -o dpi -d 'specifies the output device resolution, in dots per inch, of the Postscript p…'
complete -c pstopnm -o textalphabits -d 'This controls subsample antialiasing of text'
complete -c pstopnm -o setpage
complete -c pstopnm -o pbm
complete -c pstopnm -o pgm

