# pvck
# Autogenerated from man page /usr/share/man/man8/pvck.8.gz
complete -c pvck -l repair
complete -c pvck -l settings
complete -c pvck -l repairtype
complete -c pvck -l commandprofile
complete -c pvck -l config
complete -c pvck -s d -l debug
complete -c pvck -l devices
complete -c pvck -l devicesfile
complete -c pvck -l driverloaded
complete -c pvck -l dump
complete -c pvck -s f -l file
complete -c pvck -s h -l help
complete -c pvck -l journal
complete -c pvck -l labelsector
complete -c pvck -l lockopt
complete -c pvck -l longhelp
complete -c pvck -l nohints
complete -c pvck -l nolocking
complete -c pvck -l profile
complete -c pvck -l metadatacopies
complete -c pvck -s q -l quiet
complete -c pvck -s t -l test
complete -c pvck -s v -l verbose
complete -c pvck -l version
complete -c pvck -s y -l yes

