# pvcreate
# Autogenerated from man page /usr/share/man/man8/pvcreate.8.gz
complete -c pvcreate -l bootloaderareasize
complete -c pvcreate -l commandprofile
complete -c pvcreate -l config
complete -c pvcreate -l dataalignment
complete -c pvcreate -l dataalignmentoffset
complete -c pvcreate -s d -l debug
complete -c pvcreate -l devices
complete -c pvcreate -l devicesfile
complete -c pvcreate -l driverloaded
complete -c pvcreate -s f -l force
complete -c pvcreate -s h -l help
complete -c pvcreate -l journal
complete -c pvcreate -l labelsector
complete -c pvcreate -l lockopt
complete -c pvcreate -l longhelp
complete -c pvcreate -l metadataignore
complete -c pvcreate -l metadatasize
complete -c pvcreate -s M -l metadatatype
complete -c pvcreate -l nohints
complete -c pvcreate -l nolocking
complete -c pvcreate -l norestorefile
complete -c pvcreate -l profile
complete -c pvcreate -l metadatacopies
complete -c pvcreate -s q -l quiet
complete -c pvcreate -l reportformat
complete -c pvcreate -l restorefile
complete -c pvcreate -l setphysicalvolumesize
complete -c pvcreate -s t -l test
complete -c pvcreate -s u -l uuid
complete -c pvcreate -s v -l verbose
complete -c pvcreate -l version
complete -c pvcreate -s y -l yes
complete -c pvcreate -s Z -l zero

