# pvdisplay
# Autogenerated from man page /usr/share/man/man8/pvdisplay.8.gz
complete -c pvdisplay -l aligned
complete -c pvdisplay -s a -l all
complete -c pvdisplay -l binary
complete -c pvdisplay -s c -l colon
complete -c pvdisplay -s C -l columns
complete -c pvdisplay -l commandprofile
complete -c pvdisplay -l config
complete -c pvdisplay -l configreport
complete -c pvdisplay -s d -l debug
complete -c pvdisplay -l devices
complete -c pvdisplay -l devicesfile
complete -c pvdisplay -l driverloaded
complete -c pvdisplay -l foreign
complete -c pvdisplay -s h -l help
complete -c pvdisplay -l ignorelockingfailure
complete -c pvdisplay -l journal
complete -c pvdisplay -l lockopt
complete -c pvdisplay -l logonly
complete -c pvdisplay -l longhelp
complete -c pvdisplay -s m -l maps
complete -c pvdisplay -l noheadings
complete -c pvdisplay -l nohints
complete -c pvdisplay -l nolocking
complete -c pvdisplay -l nosuffix
complete -c pvdisplay -s o -l options
complete -c pvdisplay -o o+field1 -o o-field3 -o 'o#field5' -d 'These lists are evaluated from left to right'
complete -c pvdisplay -l profile
complete -c pvdisplay -s q -l quiet
complete -c pvdisplay -l readonly
complete -c pvdisplay -s S -l select
complete -c pvdisplay -l separator
complete -c pvdisplay -l shared
complete -c pvdisplay -s s -l short
complete -c pvdisplay -s O -l sort
complete -c pvdisplay -s t -l test
complete -c pvdisplay -l unbuffered
complete -c pvdisplay -l units
complete -c pvdisplay -s v -l verbose
complete -c pvdisplay -l version
complete -c pvdisplay -s y -l yes

