# pvmove
# Autogenerated from man page /usr/share/man/man8/pvmove.8.gz
complete -c pvmove -l abort
complete -c pvmove -l alloc
complete -c pvmove -l atomic
complete -c pvmove -s A -l autobackup
complete -c pvmove -s b -l background
complete -c pvmove -l commandprofile
complete -c pvmove -l config
complete -c pvmove -s d -l debug
complete -c pvmove -l devices
complete -c pvmove -l devicesfile
complete -c pvmove -l driverloaded
complete -c pvmove -s h -l help
complete -c pvmove -s i -l interval
complete -c pvmove -l journal
complete -c pvmove -l lockopt
complete -c pvmove -l longhelp
complete -c pvmove -s n -l name
complete -c pvmove -l nohints
complete -c pvmove -l nolocking
complete -c pvmove -l noudevsync
complete -c pvmove -l profile
complete -c pvmove -s q -l quiet
complete -c pvmove -l reportformat
complete -c pvmove -s t -l test
complete -c pvmove -s v -l verbose
complete -c pvmove -l version
complete -c pvmove -s y -l yes

