# pvremove
# Autogenerated from man page /usr/share/man/man8/pvremove.8.gz
complete -c pvremove -l commandprofile
complete -c pvremove -l config
complete -c pvremove -s d -l debug
complete -c pvremove -l devices
complete -c pvremove -l devicesfile
complete -c pvremove -l driverloaded
complete -c pvremove -s f -l force
complete -c pvremove -s h -l help
complete -c pvremove -l journal
complete -c pvremove -l lockopt
complete -c pvremove -l longhelp
complete -c pvremove -l nohints
complete -c pvremove -l nolocking
complete -c pvremove -l profile
complete -c pvremove -s q -l quiet
complete -c pvremove -l reportformat
complete -c pvremove -s t -l test
complete -c pvremove -s v -l verbose
complete -c pvremove -l version
complete -c pvremove -s y -l yes

