# pvresize
# Autogenerated from man page /usr/share/man/man8/pvresize.8.gz
complete -c pvresize -l commandprofile
complete -c pvresize -l config
complete -c pvresize -s d -l debug
complete -c pvresize -l devices
complete -c pvresize -l devicesfile
complete -c pvresize -l driverloaded
complete -c pvresize -s h -l help
complete -c pvresize -l journal
complete -c pvresize -l lockopt
complete -c pvresize -l longhelp
complete -c pvresize -l nohints
complete -c pvresize -l nolocking
complete -c pvresize -l profile
complete -c pvresize -s q -l quiet
complete -c pvresize -l reportformat
complete -c pvresize -l setphysicalvolumesize
complete -c pvresize -s t -l test
complete -c pvresize -s v -l verbose
complete -c pvresize -l version
complete -c pvresize -s y -l yes

