# pvs
# Autogenerated from man page /usr/share/man/man8/pvs.8.gz
complete -c pvs -l aligned
complete -c pvs -s a -l all
complete -c pvs -l binary
complete -c pvs -l commandprofile
complete -c pvs -l config
complete -c pvs -l configreport
complete -c pvs -s d -l debug
complete -c pvs -l devices
complete -c pvs -l devicesfile
complete -c pvs -l driverloaded
complete -c pvs -l foreign
complete -c pvs -s h -l help
complete -c pvs -l ignorelockingfailure
complete -c pvs -l journal
complete -c pvs -l lockopt
complete -c pvs -l logonly
complete -c pvs -l longhelp
complete -c pvs -l nameprefixes
complete -c pvs -l noheadings
complete -c pvs -l nohints
complete -c pvs -l nolocking
complete -c pvs -l nosuffix
complete -c pvs -s o -l options
complete -c pvs -o o+field1 -o o-field3 -o 'o#field5' -d 'These lists are evaluated from left to right'
complete -c pvs -l profile
complete -c pvs -s q -l quiet
complete -c pvs -l readonly
complete -c pvs -l reportformat
complete -c pvs -l rows
complete -c pvs -l segments
complete -c pvs -s S -l select
complete -c pvs -l separator
complete -c pvs -l shared
complete -c pvs -s O -l sort
complete -c pvs -s t -l test
complete -c pvs -l unbuffered
complete -c pvs -l units
complete -c pvs -l unquoted
complete -c pvs -s v -l verbose
complete -c pvs -l version
complete -c pvs -s y -l yes

