# pvscan
# Autogenerated from man page /usr/share/man/man8/pvscan.8.gz
complete -c pvscan -s a -l activate
complete -c pvscan -l autoactivation
complete -c pvscan -l cache
complete -c pvscan -l checkcomplete
complete -c pvscan -l commandprofile
complete -c pvscan -l config
complete -c pvscan -s d -l debug
complete -c pvscan -l devices
complete -c pvscan -l devicesfile
complete -c pvscan -l driverloaded
complete -c pvscan -s e -l exported
complete -c pvscan -s h -l help
complete -c pvscan -l ignorelockingfailure
complete -c pvscan -l journal
complete -c pvscan -l listlvs
complete -c pvscan -l listvg
complete -c pvscan -l lockopt
complete -c pvscan -l longhelp
complete -c pvscan -s j -l major
complete -c pvscan -l minor
complete -c pvscan -l nohints
complete -c pvscan -l nolocking
complete -c pvscan -l noudevsync
complete -c pvscan -s n -l novolumegroup
complete -c pvscan -l profile
complete -c pvscan -s q -l quiet
complete -c pvscan -l reportformat
complete -c pvscan -s s -l short
complete -c pvscan -s t -l test
complete -c pvscan -l udevoutput
complete -c pvscan -s u -l uuid
complete -c pvscan -s v -l verbose
complete -c pvscan -l version
complete -c pvscan -l vgonline
complete -c pvscan -s y -l yes

