# rand
# Autogenerated from man page /usr/share/man/man1/rand.1ssl.gz
complete -c rand -o help -d 'Print out a usage message'
complete -c rand -o out -d 'Write to file instead of standard output'
complete -c rand -o rand -d 'A file or files containing random data used to seed the random number generat…'
complete -c rand -o writerand -d 'Writes random data to the specified file upon exit'
complete -c rand -o base64 -d 'Perform base64 encoding on the output'

