# rapper
# Autogenerated from man page /usr/share/man/man1/rapper.1.gz
complete -c rapper -s h -l help -d 'Show a summary of the options'
complete -c rapper -s i -l input -d 'Set the input  FORMAT to one of \'rdfxml\' (RDF/XML, default), \'ntriples\' (N-Tr…'
complete -c rapper -s I -l input-uri -d 'Set the input/parser base  URI or use value \'-\' for no base'
complete -c rapper -s o -l output -d 'Set the output  FORMAT to \'ntriples\' (N-Triples, default), \'rdfxml\' (RDF/XML)…'
complete -c rapper -s O -l output-uri -d 'Set the output/serializer base  URI or use value \'-\' for no base'
complete -c rapper -s c -l count -d 'Only count the triples and produce no other output'
complete -c rapper -s e -l ignore-errors -d 'Ignore errors, do not emit the messages and try to continue parsing'
complete -c rapper -s f -l feature -d 'Set a parser or serializer feature  FEATURE to a value, or to 1 if  VALUE is …'
complete -c rapper -s g -l guess -d 'Guess the parser to use from the source-URI rather than use the -i FORMAT'
complete -c rapper -s q -l quiet -d 'No extra information messages'
complete -c rapper -s r -l replace-newlines -d 'Replace newlines in multi-line literals with spaces'
complete -c rapper -l show-graphs -d 'Print graph names (URIs) as they are seen in the input'
complete -c rapper -l show-namespaces -d 'Print namespaces as they are seen in the input'
complete -c rapper -s t -l trace -d 'Print URIs retrieved during parsing'
complete -c rapper -s w -l ignore-warnings -d 'Ignore warnings, do not emit the messages'
complete -c rapper -s v -l version -d 'Print the raptor version and exit.  EXAMPLES'

