# rarpd
# Autogenerated from man page /usr/share/man/man8/rarpd.8.gz
complete -c rarpd -s a -d 'Listen on all available interfaces'
complete -c rarpd -s A -d 'Listen not only to RARP but also ARP messages'
complete -c rarpd -s v -d 'Be verbose'
complete -c rarpd -s d -d 'Debug mode.  Do not go to background'
complete -c rarpd -s e -d 'Do not check for the presence of a boot image'
complete -c rarpd -s b -d 'TFTP boot directory.  Default is /etc/tftpboot'
complete -c rarpd -s V -d 'Print version and exit'

