# ratbagctl
# Autogenerated from man page /usr/share/man/man1/ratbagctl.1.gz
complete -c ratbagctl -l version -s V -d 'Show program\'s version number and exit'
complete -c ratbagctl -l verbose -s v -d 'Print debugging output.  Multiple -v options increase the verbosity'
complete -c ratbagctl -l nocommit -d 'Do not immediately write the settings to the mouse'
complete -c ratbagctl -o vvv -d 'will show the protocol output'
complete -c ratbagctl -l help -s h -d 'Print the help.  General Commands'
complete -c ratbagctl -o KEY_A -d 'Release \'a\''

