# ratbagd
# Autogenerated from man page /usr/share/man/man8/ratbagd.8.gz
complete -c ratbagd -l help -d 'Print help and exit'
complete -c ratbagd -l verbose -l verbose -d 'Enable verbose output, optionally including raw messages as sent and received…'
complete -c ratbagd -l quiet -d 'Disable any output but error messages'
complete -c ratbagd -l version -d 'Show the version number'

