# rawtopgm
# Autogenerated from man page /usr/share/man/man1/rawtopgm.1.gz
complete -c rawtopgm -o maxval -d 'N is the maxval for the gray values in the input, and is also the maxval of t…'
complete -c rawtopgm -o bpp -d 'tells the number of bytes that represent each sample in the input'
complete -c rawtopgm -o littleendian -d 'says that the bytes of each input sample are ordered with the least significa…'
complete -c rawtopgm -o headerskip -d 'rawtopgm skips over N bytes at the beginning of the stream and reads the imag…'
complete -c rawtopgm -o rowskip -d 'If there is padding at the ends of the rows, you can skip it with this option'
complete -c rawtopgm -o bt -o bottomfirst -d 'By default, rawtopgm assumes the pixels in the input go top to bottom, left t…'

