# rdfproc
# Autogenerated from man page /usr/share/man/man1/rdfproc.1.gz
complete -c rdfproc -s h -l help -d 'Show a summary of the options'
complete -c rdfproc -s c -l contexts -d 'Use a store with Redland contexts'
complete -c rdfproc -s n -l new -d 'Make a new store, overwriting any existing one'
complete -c rdfproc -s o -l output -d 'Set the output FORMAT for sequences of triples, such as from a search (find c…'
complete -c rdfproc -s p -l password -d 'Read the storage option \'password\' from standard input'
complete -c rdfproc -s q -l quiet -d 'Suppress informational messages (that go to stderr)'
complete -c rdfproc -s r -l results -d 'Set the query results syntax format'
complete -c rdfproc -s s -l storage -d 'Set the Redland storage type (default \'hashes\')'
complete -c rdfproc -s t -l storage-options -d 'Set options for the the Redland storage, default is "hash-type=\'bdb\',dir=\''
complete -c rdfproc -s v -l version -d 'Print the Redland version and exit'
complete -c rdfproc -s V -l verbose -d 'Show informational messages on stderr'

