# rmid-openjdk8
# Autogenerated from man page /usr/share/man/man1/rmid-openjdk8.1.gz
complete -c rmid-openjdk8 -o Coption -d 'br Specifies an option that is passed as a command-line argument to each chil…'
complete -c rmid-openjdk8 -o Joption -d 'br Specifies an option that is passed to the Java interpreter running RMID'
complete -c rmid-openjdk8 -o 'J-Dsun.rmi.activation.execPolicy' -d 'br Specifies the policy that RMID employs to check commands and command-line …'
complete -c rmid-openjdk8 -o log -d 'br Specifies the name of the directory the activation system daemon uses to w…'
complete -c rmid-openjdk8 -o port -d 'br Specifies the port the registry uses'
complete -c rmid-openjdk8 -o stop

