# roqet
# Autogenerated from man page /usr/share/man/man1/roqet.1.gz
complete -c roqet -s e -l exec -d 'Execute the query string in the argument QUERY instead of reading the query f…'
complete -c roqet -s i -l input -d 'Set the input query LANGUAGE to one of the supported languages which includes…'
complete -c roqet -s h -l help
complete -c roqet -s p -l protocol -d 'Call the SPARQL HTTP protocol SERVICE-URI to execute the query instead of exe…'
complete -c roqet -s r -l results -d 'Set the query results output FORMAT For variable bindings, the values of FORM…'
complete -c roqet -s R -l results-input-format -d 'Set the query results input'
complete -c roqet -s t -l results-input -d 'Read query results from FILE OTHER OPTIONS'
complete -c roqet -s c -l count -d 'Only count the triples and produce no other output'
complete -c roqet -s d -l dump-query -d 'Print the parsed query out in a given FORMAT one of \'none\' (default), \'debug\'…'
complete -c roqet -s D -l data -d 'Add RDF data source URI (not a named graph)'
complete -c roqet -s E -l ignore-errors -d 'Do not print error messages and do not exit with a non-0 status'
complete -c roqet -s f -l feature -d 'Set query feature NAME to the VALUE or integer 1 if omitted'
complete -c roqet -s F -l format -d 'Set the data source format name for subsequent data graphs called with -D / -…'
complete -c roqet -s G -l named -d 'Add RDF data source URI (named graph)'
complete -c roqet -s n -l dryrun -d 'Prepare the query but do not execute it'
complete -c roqet -s q -l quiet -d 'No extra information messages'
complete -c roqet -s s -l source -d 'Add RDF data source URI (named graph) URI by adding it to the list of query d…'
complete -c roqet -s v -l version -d 'Print the rasqal library version and exit'
complete -c roqet -s W -l warnings -d 'Set the warning  LEVEL in the range 0 (do not warn about anything) to 100 (sh…'

