# rustdoc
# Autogenerated from man page /usr/share/man/man1/rustdoc.1.gz
complete -c rustdoc -s r -l input-format -d rust
complete -c rustdoc -s w -l output-format -d html
complete -c rustdoc -s o -l output -d 'where to place the output (default: doc/ for html)'
complete -c rustdoc -l passes -d 'space\\[hy]separated list of passes to run (default: \'\')'
complete -c rustdoc -l no-defaults -d 'don\'t run the default passes'
complete -c rustdoc -l plugins -d 'space-separated list of plugins to run (default: \'\')'
complete -c rustdoc -l plugin-path -d 'directory to load plugins from (default: /tmp/rustdoc_ng/plugins)'
complete -c rustdoc -l target -d 'target triple to document'
complete -c rustdoc -l crate-name -d 'specify the name of this crate'
complete -c rustdoc -s L -l library-path -d 'directory to add to crate search path'
complete -c rustdoc -l cfg -d 'pass a --cfg to rustc'
complete -c rustdoc -l extern -d 'pass an --extern to rustc'
complete -c rustdoc -l test -d 'run code examples as tests'
complete -c rustdoc -l test-args -d 'pass arguments to the test runner'
complete -c rustdoc -l html-in-header -d 'file to add to <head>'
complete -c rustdoc -l html-before-content -d 'files to include inline between <body> and the content of a rendered Markdown…'
complete -c rustdoc -l markdown-before-content -d 'files to include inline between <body> and the content of a rendered Markdown…'
complete -c rustdoc -l html-after-content -d 'files to include inline between the content and </body> of a rendered Markdow…'
complete -c rustdoc -l markdown-after-content -d 'files to include inline between the content and </body> of a rendered Markdow…'
complete -c rustdoc -l markdown-css -d 'CSS files to include via <link> in a rendered Markdown file Markdown file or …'
complete -c rustdoc -l markdown-playground-url -d 'URL to send code snippets to'
complete -c rustdoc -l markdown-no-toc -d 'don\'t include table of contents'
complete -c rustdoc -s h -l extend-css -d 'to redefine some css rules with a given file to generate doc with your own th…'
complete -c rustdoc -s V -l version -d 'Print rustdoc\'s version'

