# sccmap
# Autogenerated from man page /usr/share/man/man1/sccmap.1.gz
complete -c sccmap -s d -d 'Preserve degenerate components of only one node'
complete -c sccmap -s s -d 'Do not print the resulting graphs.  Only the statistics are important'
complete -c sccmap -s S -d 'Just print the resulting graphs.  No statistics are printed'
complete -c sccmap -s o -d 'Prints output to the file output.  If not given, sccmap uses stdout'
complete -c sccmap -s v -d 'Generate additional statistics'

