# schemagen-openjdk8
# Autogenerated from man page /usr/share/man/man1/schemagen-openjdk8.1.gz
complete -c schemagen-openjdk8 -s d -d 'br The location where the \\f3schemagen command places processor-generated and…'
complete -c schemagen-openjdk8 -o cp -d 'br The location where the \\f3schemagen command places user-specified files'
complete -c schemagen-openjdk8 -o classpath -d 'br The location where the \\f3schemagen command places user-specified files'
complete -c schemagen-openjdk8 -o encoding -d 'br Specifies the encoding to use for \\f3apt or \\f3javac command invocations'
complete -c schemagen-openjdk8 -o episode -d 'br Generates an episode file for separate compilation'
complete -c schemagen-openjdk8 -o version -d 'br Displays release information'
complete -c schemagen-openjdk8 -o help

