# serdi
# Autogenerated from man page /usr/share/man/man1/serdi.1.gz
complete -c serdi -s a -d 'Write ASCII output if possible'
complete -c serdi -s b -d 'Fast bulk output for large serialisations'
complete -c serdi -s c -d 'Chop PREFIX from matching blank node IDs'
complete -c serdi -s e -d 'Eat input one character at a time, rather than a page at a time which is the …'
complete -c serdi -s f -d 'Keep full URIs in input (don\'t qualify)'
complete -c serdi -s h -d 'Print the command line options'
complete -c serdi -s i -d 'Read input as SYNTAX'
complete -c serdi -s l -d 'Lax (non-strict) parsing'
complete -c serdi -s o -d 'Write output as SYNTAX'
complete -c serdi -s p -d 'Add PREFIX to blank node IDs'
complete -c serdi -s q -d 'Suppress all output except data'
complete -c serdi -s r -d 'Keep relative URIs within ROOT_URI'
complete -c serdi -s s -d 'Parse INPUT as a string (terminates options)'
complete -c serdi -s v -d 'Display version information and exit'

