# sfdp
# Autogenerated from man page /usr/share/man/man1/sfdp.1.gz
complete -c sfdp -o Tdot
complete -c sfdp -o Txdot
complete -c sfdp -o Tps
complete -c sfdp -o Tpdf
complete -c sfdp -o Tsvg -o Tsvgz
complete -c sfdp -o Tfig
complete -c sfdp -o Tpng
complete -c sfdp -o Tgif
complete -c sfdp -o Tjpg -o Tjpeg
complete -c sfdp -o Tjson
complete -c sfdp -o Timap -d 'that has a non-null href attribute. ),'
complete -c sfdp -o Tcmapx
complete -c sfdp -s G
complete -c sfdp -s N
complete -c sfdp -s E -d 'Example: -Gsize="7,8" -Nshape=box -Efontsize=8'
complete -c sfdp -o lfile -d 'Usually these define custom shapes or styles'
complete -c sfdp -o Tlang
complete -c sfdp -o 'n[1' -d 'If set, neato assumes nodes have already been positioned and all nodes have a…'
complete -c sfdp -o Klayout
complete -c sfdp -s O -s T
complete -c sfdp -s P
complete -c sfdp -s v
complete -c sfdp -s c
complete -c sfdp -o qlevel
complete -c sfdp -o sfscale
complete -c sfdp -s y
complete -c sfdp -o ofile
complete -c sfdp -s x
complete -c sfdp -o Lg
complete -c sfdp -o LO
complete -c sfdp -o Lni
complete -c sfdp -o LUi
complete -c sfdp -o LCv
complete -c sfdp -o LTv
complete -c sfdp -s V
complete -c sfdp -s '?'

