# sgitopnm
# Autogenerated from man page /usr/share/man/man1/sgitopnm.1.gz
complete -c sgitopnm -o verbose -d 'Give some information about the SGI image file'
complete -c sgitopnm -o channel -d 'Extract channel n of the image as a PGM image'

