# sldtoppm
# Autogenerated from man page /usr/share/man/man1/sldtoppm.1.gz
complete -c sldtoppm -o adjust -d 'If the display on which the slide file was created had non-square pixels, whe…'
complete -c sldtoppm -o dir -d 'The input is assumed to be an AutoCAD slide library file'
complete -c sldtoppm -o height -d 'Scales the image in the vector domain so it is size pixels in height'
complete -c sldtoppm -o info -d 'Dump the slide file header on standard error, displaying the original screen …'
complete -c sldtoppm -o lib -d 'Extracts the slide with the given name from the slide library given as input'
complete -c sldtoppm -o Lib -d 'Extracts the slide with the given name from the slide library given as input'
complete -c sldtoppm -o scale -d 'Scales the image by factor s, which may be any floating point value greater t…'
complete -c sldtoppm -o verbose -d 'Dumps the slide file header and lists every vector and polygon  to Standard E…'
complete -c sldtoppm -o width -d 'Scales the image in the vector domain so it is size pixels wide'
complete -c sldtoppm -o xsize -d 'Scales the image in the vector domain so it is size pixels wide'
complete -c sldtoppm -o ysize -d 'Scales the image in the vector domain so it is size pixels in height'

