# sordi
# Autogenerated from man page /usr/share/man/man1/sordi.1.gz
complete -c sordi -s h -d 'Print the command line options'
complete -c sordi -s i -d 'Read input in SYNTAX (`turtle\' or `ntriples\')'
complete -c sordi -s o -d 'Write output in SYNTAX (`turtle\' or `ntriples\')'
complete -c sordi -s s -d 'Parse INPUT as a string (terminates options)'
complete -c sordi -s v -d 'Display version information and exit'

