# speed
# Autogenerated from man page /usr/share/man/man1/speed.1ssl.gz
complete -c speed -o help -d 'Print out a usage message'
complete -c speed -o engine -d 'Specifying an engine (by its unique id string) will cause speed to attempt to…'
complete -c speed -o elapsed -d 'When calculating operations- or bytes-per-second, use wall-clock time instead…'
complete -c speed -o evp -d 'Use the specified cipher or message digest algorithm via the \\s-1EVP\\s0 inter…'
complete -c speed -o decrypt -d 'Time the decryption instead of encryption'
complete -c speed -o rand -d 'A file or files containing random data used to seed the random number generat…'
complete -c speed -o writerand -d 'Writes random data to the specified file upon exit'
complete -c speed -o primes -d 'Generate a num-prime \\s-1RSA\\s0 key and use it to run the benchmarks'
complete -c speed -o seconds -d 'Run benchmarks for num seconds'
complete -c speed -o bytes -d 'Run benchmarks on num-byte buffers'

