# stl2gts
# Autogenerated from man page /usr/share/man/man1/stl2gts.1.gz
complete -c stl2gts -s r -l revert -d 'Revert face normals'
complete -c stl2gts -s n -l nomerge -d 'Do not merge vertices'
complete -c stl2gts -s v -l verbose -d 'Display surface statistics'
complete -c stl2gts -s h -l help -d 'Display the help and exit'

