# systemd-journal-gatewayd
# Autogenerated from man page /usr/share/man/man8/systemd-journal-gatewayd.service.8.gz
complete -c systemd-journal-gatewayd -l cert -d 'Specify the path to a file or AF_UNIX stream socket to read the server certif…'
complete -c systemd-journal-gatewayd -l key -d 'Specify the path to a file or AF_UNIX stream socket to read the secret server…'
complete -c systemd-journal-gatewayd -l trust -d 'Specify the path to a file or AF_UNIX stream socket to read a CA certificate …'
complete -c systemd-journal-gatewayd -l system -l user -d 'Limit served entries to entries from system services and the kernel, or to en…'
complete -c systemd-journal-gatewayd -s m -l merge -d 'Serve entries interleaved from all available journals, including other machin…'
complete -c systemd-journal-gatewayd -s D -l directory -d 'Takes a directory path as argument'
complete -c systemd-journal-gatewayd -l file -d 'Takes a file glob as an argument'
complete -c systemd-journal-gatewayd -s h -l help -d 'Print a short help text and exit'
complete -c systemd-journal-gatewayd -l version -d 'Print a short version string and exit'

