# systemd-journal-remote
# Autogenerated from man page /usr/share/man/man8/systemd-journal-remote.service.8.gz
complete -c systemd-journal-remote -l split-mode -d 'One of none or host.  For the first, only one output journal file is used'
complete -c systemd-journal-remote -l compress -d 'If this is set to "yes" then compress the data in the journal using XZ'
complete -c systemd-journal-remote -l seal -d 'If this is set to "yes" then periodically sign the data in the journal using …'
complete -c systemd-journal-remote -s h -l help -d 'Print a short help text and exit'
complete -c systemd-journal-remote -l version -d 'Print a short version string and exit'
complete -c systemd-journal-remote -l url
complete -c systemd-journal-remote -l getter
complete -c systemd-journal-remote -o HAccept
complete -c systemd-journal-remote -l header -o O- -d 'Passive sources can be specified in the following ways:'
complete -c systemd-journal-remote -l listen-raw
complete -c systemd-journal-remote -l listen-http -l listen-https
complete -c systemd-journal-remote -s n -d or
complete -c systemd-journal-remote -l key
complete -c systemd-journal-remote -l cert
complete -c systemd-journal-remote -l trust
complete -c systemd-journal-remote -l gnutls-log
complete -c systemd-journal-remote -s o -d or
complete -c systemd-journal-remote -l output

