# tfmtodit
# Autogenerated from man page /usr/share/man/man1/tfmtodit.1.gz
complete -c tfmtodit -s v -d 'Print the version number'
complete -c tfmtodit -s s -d 'The font is special'
complete -c tfmtodit -s k -d 'The skewchar of this font is at position R n '
complete -c tfmtodit -s g -d option

