# tgatoppm
# Autogenerated from man page /usr/share/man/man1/tgatoppm.1.gz
complete -c tgatoppm -l alphaout -d 'tgatoppm  creates a PGM image containing the alpha channel values in the inpu…'
complete -c tgatoppm -l headerdump -d 'Causes tgatoppm to dump information from the TGA header to Standard Error'

