# thin_dump
# Autogenerated from man page /usr/share/man/man8/thin_dump.8.gz
complete -c thin_dump -s h -l help -d 'Print help and exit'
complete -c thin_dump -s V -l version -d 'Print version information and exit'
complete -c thin_dump -s f -l format -d 'Choose output format. PP . nf '
complete -c thin_dump -s r -l repair -d 'Repair the metadata whilst dumping it'
complete -c thin_dump -s m -l metadata-snap -d 'Dump metadata snapshot. PP . nf '
complete -c thin_dump -l dev-id -d 'Dump the specified device. PP . nf '
complete -c thin_dump -l transaction-id -d 'Override the transaction id given in the input xml'
complete -c thin_dump -l data-block-size -d 'Override the data block size given in the input xml'
complete -c thin_dump -l nr-data-blocks -d 'Override the nr data blocks given in the input xml'
complete -c thin_dump -l skip-mappings -d 'Do not dump the mappings'
complete -c thin_dump -s o -d 'Specify a file for the output rather than writing to stdout'

