# thin_ls
# Autogenerated from man page /usr/share/man/man8/thin_ls.8.gz
complete -c thin_ls -s h -l help -d 'Print help and exit'
complete -c thin_ls -s V -l version -d 'Print version information and exit'
complete -c thin_ls -s o -l format -d 'Give a comma separated list of fields to be output. PP . nf '
complete -c thin_ls -l no-headers -d 'Don\'t output headers'
complete -c thin_ls -s m -l metadata-snap -d 'Use metadata snapshot'

