# thin_trim
# Autogenerated from man page /usr/share/man/man8/thin_trim.8.gz
complete -c thin_trim -s h -l help -d 'Print help and exit'
complete -c thin_trim -s V -l version -d 'Print version information and exit'

