# thin_metadata_size
# Autogenerated from man page /usr/share/man/man8/thin_metadata_size.8.gz
complete -c thin_metadata_size -s h -l help -d 'Print help and exit'
complete -c thin_metadata_size -s V -l version -d 'Print version information and exit'
complete -c thin_metadata_size -s b -l block-size -d 'Set block size. PP . nf '
complete -c thin_metadata_size -s s -l pool-size -d 'Set pool size. PP . nf '
complete -c thin_metadata_size -s m -l max-thins -d 'Set max thins. PP . nf '
complete -c thin_metadata_size -s u -l unit -d '    Output unit specifier in units of bytes, sectors, kibibytes, kilobytes, '
complete -c thin_metadata_size -s n -l numeric-only -d 'Limit output to just the size number'

