# thin_rmap
# Autogenerated from man page /usr/share/man/man8/thin_rmap.8.gz
complete -c thin_rmap -s h -l help -d 'Print help and exit'
complete -c thin_rmap -s V -l version -d 'Print version information and exit'
complete -c thin_rmap -l region -d 'Specify range of blocks on the data device'

