# tifftopnm
# Autogenerated from man page /usr/share/man/man1/tifftopnm.1.gz
complete -c tifftopnm -o alphaout -d 'tifftopnm creates a PGM file containing the alpha channel values in the input…'
complete -c tifftopnm -o respectfillorder -d 'By default, tifftopnm  ignores the \'fillorder\' tag in the TIFF input, which m…'
complete -c tifftopnm -o byrow -d 'This option can make tifftopnm run faster'
complete -c tifftopnm -o orientraw -d 'A TIFF stream contains raster data which can be arranged in the stream variou…'
complete -c tifftopnm -o verbose -d 'Print extra messages to Standard Error about the conversion'
complete -c tifftopnm -o headerdump -d 'Dump TIFF file information to stderr'

