# tracker-writeback-3
# Autogenerated from man page /usr/share/man/man1/tracker-writeback-3.1.gz
complete -c tracker-writeback-3 -s '?' -l help -d 'Show summary of options'
complete -c tracker-writeback-3 -s V -l version -d 'Returns the version of this binary'
complete -c tracker-writeback-3 -s d -l disable-shutdown -d 'Disable shutting down after 30 seconds of inactivity'

