# tracker3-tag
# Autogenerated from man page /usr/share/man/man1/tracker3-tag.1.gz
complete -c tracker3-tag -s t -l list -d 'List all tags'
complete -c tracker3-tag -s s -l show-files -d 'Show the files associated with each tag'
complete -c tracker3-tag -s a -l add -d 'Add a tag with the name TAG'
complete -c tracker3-tag -s d -l delete -d 'Delete a tag with the name TAG'
complete -c tracker3-tag -s e -l description -d 'This option ONLY applies when using --add and provides a description to go wi…'
complete -c tracker3-tag -s l -l limit -d 'Limit search to N results.  The default is 512'
complete -c tracker3-tag -s o -l offset -d 'Offset the search results by N'
complete -c tracker3-tag -s r -l and-operator -d 'Use AND operator for search terms instead of OR (the default).  For example:'

