# tracker3-reset
# Autogenerated from man page /usr/share/man/man1/tracker3-reset.1.gz
complete -c tracker3-reset -s s -l filesystem -d 'Removes data stored by tracker-miner-fs(1)'
complete -c tracker3-reset -s r -l rss -d 'Removes data stored by tracker-miner-rss(1)'
complete -c tracker3-reset -s f -l file -d 'Resets all indexed information about FILE, works recursively for directories'

