# tracker-miner-fs-3
# Autogenerated from man page /usr/share/man/man1/tracker-miner-fs-3.1.gz
complete -c tracker-miner-fs-3 -s '?' -l help -d 'Show summary of options'
complete -c tracker-miner-fs-3 -s V -l version -d 'Returns the version of this binary'
complete -c tracker-miner-fs-3 -s s -l initial-sleep -d 'Sets the initial sleep time before crawling the file system is started'
complete -c tracker-miner-fs-3 -s n -l no-daemon -d 'Tells the miner to exit once all indexing has finished and the database is up…'
complete -c tracker-miner-fs-3 -s e -l eligible -d 'Checks if FILE is eligible for being mined based on the current configuration…'

