# tracker-miner-rss-3
# Autogenerated from man page /usr/share/man/man1/tracker-miner-rss-3.1.gz
complete -c tracker-miner-rss-3 -s '?' -l help -d 'Show summary of options'
complete -c tracker-miner-rss-3 -s V -l version -d 'Returns the version of this binary'
complete -c tracker-miner-rss-3 -s a -l add-feed -d 'Adds a feed to be indexed.  This must be used with --title option'
complete -c tracker-miner-rss-3 -s t -l title -d 'The title to use when adding a feed (see the --add-feed option)'

