# transform
# Autogenerated from man page /usr/share/man/man1/transform.1.gz
complete -c transform -s r -l rx -d 'Rotate around x-axis . RI ( ANGLE in degrees)'
complete -c transform -s m -l ry -d 'Rotate around y-axis'
complete -c transform -l rz -d 'Rotate around z-axis'
complete -c transform -s s -l scale -d 'Scale by R FACTOR '
complete -c transform -s R -l sx -d 'Scale x-axis by R FACTOR '
complete -c transform -s M -l sy -d 'Scale y-axis by R FACTOR '
complete -c transform -s N -l sz -d 'Scale z-axis by R FACTOR '
complete -c transform -s t -l tx -d 'Translate of  V along x-axis'
complete -c transform -s u -l ty -d 'Translate of  V along y-axis'
complete -c transform -s w -l tz -d 'Translate of  V along z-axis'
complete -c transform -s i -l revert -d 'Turn surface inside out'
complete -c transform -s o -l normalize -d 'Fit the resulting surface in a cube of size 1 centered at the origin'
complete -c transform -s v -l verbose -d 'Print statistics about the surface'
complete -c transform -s h -l help -d 'Display the help and exit'

