# tred
# Autogenerated from man page /usr/share/man/man1/tred.1.gz
complete -c tred -s v -d 'Verbose output to stderr'
complete -c tred -s r -d 'Print information of removed edges to stderr'
complete -c tred -s '?' -d 'Print usage information.  OPERANDS The following operand is supported:'

