# trietool-0
# Autogenerated from man page /usr/share/man/man1/trietool-0.2.1.gz
complete -c trietool-0 -s p -l path -d 'Set trie directory to dir [default=`. \']'
complete -c trietool-0 -s h -l help -d 'Show summary of options'
complete -c trietool-0 -s e -l encoding -d 'Specify character encoding of the list-file contents, such as `UTF-8\''
complete -c trietool-0 -s V -l version -d 'Show version of program'

