# twopi
# Autogenerated from man page /usr/share/man/man1/twopi.1.gz
complete -c twopi -o Tdot
complete -c twopi -o Txdot
complete -c twopi -o Tps
complete -c twopi -o Tpdf
complete -c twopi -o Tsvg -o Tsvgz
complete -c twopi -o Tfig
complete -c twopi -o Tpng
complete -c twopi -o Tgif
complete -c twopi -o Tjpg -o Tjpeg
complete -c twopi -o Tjson
complete -c twopi -o Timap -d 'that has a non-null href attribute. ),'
complete -c twopi -o Tcmapx
complete -c twopi -s G
complete -c twopi -s N
complete -c twopi -s E -d 'Example: -Gsize="7,8" -Nshape=box -Efontsize=8'
complete -c twopi -o lfile -d 'Usually these define custom shapes or styles'
complete -c twopi -o Tlang
complete -c twopi -o 'n[1' -d 'If set, neato assumes nodes have already been positioned and all nodes have a…'
complete -c twopi -o Klayout
complete -c twopi -s O -s T
complete -c twopi -s P
complete -c twopi -s v
complete -c twopi -s c
complete -c twopi -o qlevel
complete -c twopi -o sfscale
complete -c twopi -s y
complete -c twopi -o ofile
complete -c twopi -s x
complete -c twopi -o Lg
complete -c twopi -o LO
complete -c twopi -o Lni
complete -c twopi -o LUi
complete -c twopi -o LCv
complete -c twopi -o LTv
complete -c twopi -s V
complete -c twopi -s '?'

