# unpack200-openjdk8
# Autogenerated from man page /usr/share/man/man1/unpack200-openjdk8.1.gz
complete -c unpack200-openjdk8 -o Hvalue -l deflate-hint -d 'br Sets the deflation to be \\f3true, \\f3false, or \\f3keep on all entries with…'
complete -c unpack200-openjdk8 -s r -l remove-pack-file -d 'br Removes the input pack file'
complete -c unpack200-openjdk8 -s v -l verbose -d 'br Displays minimal messages'
complete -c unpack200-openjdk8 -s q -l quiet -d 'br Specifies quiet operation with no messages'
complete -c unpack200-openjdk8 -o lfilename -l log-file -d 'br Specifies a log file where output messages are logged'
complete -c unpack200-openjdk8 -s '?' -s h -l help -d 'br Prints help information about the \\f3unpack200 command'
complete -c unpack200-openjdk8 -s V -l version -d 'br Prints version information about the \\f3unpack200 command'
complete -c unpack200-openjdk8 -o Joption

