# updatedb
# Autogenerated from man page /usr/share/man/man8/updatedb.8.gz
complete -c updatedb -s f -l add-prunefs -d 'Add entries in white-space-separated list FS to PRUNEFS'
complete -c updatedb -s n -l add-prunenames -d 'Add entries in white-space-separated list NAMES to PRUNENAMES'
complete -c updatedb -s e -l add-prunepaths -d 'Add entries in white-space-separated list PATHS to PRUNEPATHS'
complete -c updatedb -s U -l database-root -d 'Store only results of scanning the file system subtree rooted at PATH to the …'
complete -c updatedb -l debug-pruning -d 'Write debugging information about pruning decisions to standard error output'
complete -c updatedb -s h -l help -d 'Write a summary of the available options to standard output and exit successf…'
complete -c updatedb -s o -l output -d 'Write the database to  FILE instead of using the default database'
complete -c updatedb -l prune-bind-mounts -d 'Set  PRUNE_BIND_MOUNTS to FLAG, overriding the configuration file'
complete -c updatedb -l prunefs -d 'Set PRUNEFS to FS, overriding the configuration file'
complete -c updatedb -l prunenames -d 'Set PRUNENAMES to NAMES, overriding the configuration file'
complete -c updatedb -l prunepaths -d 'Set PRUNEPATHS to PATHS, overriding the configuration file'
complete -c updatedb -s l -l require-visibility -d 'Set the \\*(lqrequire file visibility before reporting it\\*(rq flag in the gen…'
complete -c updatedb -s v -l verbose -d 'Output path names of files to standard output, as soon as they are found'
complete -c updatedb -s V -l version -d 'Write information about the version and license of locate on standard output …'

