# updpkgsums
# Autogenerated from man page /usr/share/man/man8/updpkgsums.8.gz
complete -c updpkgsums -s V -l version -d 'Display version information and exit'
complete -c updpkgsums -s m -l nocolor -d 'Disable colorized output messages'

