# vala-panel
# Autogenerated from man page /usr/share/man/man1/vala-panel.1.gz
complete -c vala-panel -s c
complete -c vala-panel -l command -d 'Runs specific command on already opened panel'
complete -c vala-panel -s p
complete -c vala-panel -l profile -d 'Runs panel with specified profile'
complete -c vala-panel -s h
complete -c vala-panel -l help -d 'Show summary of options'
complete -c vala-panel -s v
complete -c vala-panel -l version -d 'Show version of program'

