# vapigen
# Autogenerated from man page /usr/share/man/man1/vapigen.1.gz
complete -c vapigen -s h -l help -d 'Show help options . SS "Application Options:"'
complete -c vapigen -l vapidir -d 'Look for package bindings in DIRECTORY'
complete -c vapigen -l girdir -d 'Look for GIR bindings in DIRECTORY'
complete -c vapigen -l metadatadir -d 'Look for GIR . metadata files in DIRECTORY'
complete -c vapigen -l nostdpkg -d 'Do not include standard packages'
complete -c vapigen -l pkg -d 'Include binding for PACKAGE'
complete -c vapigen -l library -d 'Library name'
complete -c vapigen -s d -l directory -d 'Output directory'
complete -c vapigen -l disable-warnings -d 'Disable warnings'
complete -c vapigen -l version -d 'Display version number'
complete -c vapigen -s q -l quiet -d 'Do not print messages to the console'

