# vgcfgbackup
# Autogenerated from man page /usr/share/man/man8/vgcfgbackup.8.gz
complete -c vgcfgbackup -l commandprofile
complete -c vgcfgbackup -l config
complete -c vgcfgbackup -s d -l debug
complete -c vgcfgbackup -l devices
complete -c vgcfgbackup -l devicesfile
complete -c vgcfgbackup -l driverloaded
complete -c vgcfgbackup -s f -l file
complete -c vgcfgbackup -l foreign
complete -c vgcfgbackup -s h -l help
complete -c vgcfgbackup -l ignorelockingfailure
complete -c vgcfgbackup -l journal
complete -c vgcfgbackup -l lockopt
complete -c vgcfgbackup -l longhelp
complete -c vgcfgbackup -l nohints
complete -c vgcfgbackup -l nolocking
complete -c vgcfgbackup -l profile
complete -c vgcfgbackup -s q -l quiet
complete -c vgcfgbackup -l readonly
complete -c vgcfgbackup -l reportformat
complete -c vgcfgbackup -s t -l test
complete -c vgcfgbackup -s v -l verbose
complete -c vgcfgbackup -l version
complete -c vgcfgbackup -s y -l yes

