# vgcfgrestore
# Autogenerated from man page /usr/share/man/man8/vgcfgrestore.8.gz
complete -c vgcfgrestore -l commandprofile
complete -c vgcfgrestore -l config
complete -c vgcfgrestore -s d -l debug
complete -c vgcfgrestore -l devices
complete -c vgcfgrestore -l devicesfile
complete -c vgcfgrestore -l driverloaded
complete -c vgcfgrestore -s f -l file
complete -c vgcfgrestore -l force
complete -c vgcfgrestore -s h -l help
complete -c vgcfgrestore -l journal
complete -c vgcfgrestore -s l -l list
complete -c vgcfgrestore -l lockopt
complete -c vgcfgrestore -l longhelp
complete -c vgcfgrestore -s M -l metadatatype
complete -c vgcfgrestore -l nohints
complete -c vgcfgrestore -l nolocking
complete -c vgcfgrestore -l profile
complete -c vgcfgrestore -s q -l quiet
complete -c vgcfgrestore -s t -l test
complete -c vgcfgrestore -s v -l verbose
complete -c vgcfgrestore -l version
complete -c vgcfgrestore -s y -l yes

