# vgchange
# Autogenerated from man page /usr/share/man/man8/vgchange.8.gz
complete -c vgchange -s a -l activate
complete -c vgchange -l activationmode
complete -c vgchange -l addtag
complete -c vgchange -l alloc
complete -c vgchange -l autoactivation
complete -c vgchange -s A -l autobackup
complete -c vgchange -l commandprofile
complete -c vgchange -l config
complete -c vgchange -s d -l debug
complete -c vgchange -l deltag
complete -c vgchange -l detachprofile
complete -c vgchange -l devices
complete -c vgchange -l devicesfile
complete -c vgchange -l driverloaded
complete -c vgchange -s f -l force
complete -c vgchange -s h -l help
complete -c vgchange -s K -l ignoreactivationskip
complete -c vgchange -l ignorelockingfailure
complete -c vgchange -l ignoremonitoring
complete -c vgchange -l journal
complete -c vgchange -l lockopt
complete -c vgchange -l lockstart
complete -c vgchange -l lockstop
complete -c vgchange -l locktype
complete -c vgchange -s l -l logicalvolume
complete -c vgchange -l longhelp
complete -c vgchange -s p -l maxphysicalvolumes
complete -c vgchange -l metadataprofile
complete -c vgchange -l monitor
complete -c vgchange -l nohints
complete -c vgchange -l nolocking
complete -c vgchange -l noudevsync
complete -c vgchange -s P -l partial
complete -c vgchange -s s -l physicalextentsize
complete -c vgchange -l poll
complete -c vgchange -l profile
complete -c vgchange -l pvmetadatacopies
complete -c vgchange -s q -l quiet
complete -c vgchange -l readonly
complete -c vgchange -l refresh
complete -c vgchange -l reportformat
complete -c vgchange -s x -l resizeable
complete -c vgchange -s S -l select
complete -c vgchange -l setautoactivation
complete -c vgchange -l sysinit
complete -c vgchange -l systemid
complete -c vgchange -s t -l test
complete -c vgchange -s u -l uuid
complete -c vgchange -s v -l verbose
complete -c vgchange -l version
complete -c vgchange -l metadatacopies
complete -c vgchange -s y -l yes

