# vgck
# Autogenerated from man page /usr/share/man/man8/vgck.8.gz
complete -c vgck -l commandprofile
complete -c vgck -l config
complete -c vgck -s d -l debug
complete -c vgck -l devices
complete -c vgck -l devicesfile
complete -c vgck -l driverloaded
complete -c vgck -s h -l help
complete -c vgck -l journal
complete -c vgck -l lockopt
complete -c vgck -l longhelp
complete -c vgck -l nohints
complete -c vgck -l nolocking
complete -c vgck -l profile
complete -c vgck -s q -l quiet
complete -c vgck -l reportformat
complete -c vgck -s t -l test
complete -c vgck -l updatemetadata
complete -c vgck -s v -l verbose
complete -c vgck -l version
complete -c vgck -s y -l yes

