# vgconvert
# Autogenerated from man page /usr/share/man/man8/vgconvert.8.gz
complete -c vgconvert -l bootloaderareasize
complete -c vgconvert -l commandprofile
complete -c vgconvert -l config
complete -c vgconvert -s d -l debug
complete -c vgconvert -l devices
complete -c vgconvert -l devicesfile
complete -c vgconvert -l driverloaded
complete -c vgconvert -s f -l force
complete -c vgconvert -s h -l help
complete -c vgconvert -l journal
complete -c vgconvert -l labelsector
complete -c vgconvert -l lockopt
complete -c vgconvert -l longhelp
complete -c vgconvert -l metadatasize
complete -c vgconvert -s M -l metadatatype
complete -c vgconvert -l nohints
complete -c vgconvert -l nolocking
complete -c vgconvert -l profile
complete -c vgconvert -l pvmetadatacopies
complete -c vgconvert -s q -l quiet
complete -c vgconvert -l reportformat
complete -c vgconvert -s t -l test
complete -c vgconvert -s v -l verbose
complete -c vgconvert -l version
complete -c vgconvert -s y -l yes

