# vgcreate
# Autogenerated from man page /usr/share/man/man8/vgcreate.8.gz
complete -c vgcreate -l addtag
complete -c vgcreate -l alloc
complete -c vgcreate -s A -l autobackup
complete -c vgcreate -s c -l clustered
complete -c vgcreate -l commandprofile
complete -c vgcreate -l config
complete -c vgcreate -l dataalignment
complete -c vgcreate -l dataalignmentoffset
complete -c vgcreate -s d -l debug
complete -c vgcreate -l devices
complete -c vgcreate -l devicesfile
complete -c vgcreate -l driverloaded
complete -c vgcreate -s f -l force
complete -c vgcreate -s h -l help
complete -c vgcreate -l journal
complete -c vgcreate -l labelsector
complete -c vgcreate -l lockopt
complete -c vgcreate -l locktype
complete -c vgcreate -l longhelp
complete -c vgcreate -s l -l maxlogicalvolumes
complete -c vgcreate -s p -l maxphysicalvolumes
complete -c vgcreate -l metadataprofile
complete -c vgcreate -l metadatasize
complete -c vgcreate -s M -l metadatatype
complete -c vgcreate -l nohints
complete -c vgcreate -l nolocking
complete -c vgcreate -s s -l physicalextentsize
complete -c vgcreate -l profile
complete -c vgcreate -l pvmetadatacopies
complete -c vgcreate -s q -l quiet
complete -c vgcreate -l reportformat
complete -c vgcreate -l setautoactivation
complete -c vgcreate -l shared
complete -c vgcreate -l systemid
complete -c vgcreate -s t -l test
complete -c vgcreate -s v -l verbose
complete -c vgcreate -l version
complete -c vgcreate -l metadatacopies
complete -c vgcreate -s y -l yes
complete -c vgcreate -s Z -l zero
complete -c vgcreate -l restorefile -l uuid

