# vgdisplay
# Autogenerated from man page /usr/share/man/man8/vgdisplay.8.gz
complete -c vgdisplay -s A -l activevolumegroups
complete -c vgdisplay -l aligned
complete -c vgdisplay -l binary
complete -c vgdisplay -s c -l colon
complete -c vgdisplay -s C -l columns
complete -c vgdisplay -l commandprofile
complete -c vgdisplay -l config
complete -c vgdisplay -l configreport
complete -c vgdisplay -s d -l debug
complete -c vgdisplay -l devices
complete -c vgdisplay -l devicesfile
complete -c vgdisplay -l driverloaded
complete -c vgdisplay -l foreign
complete -c vgdisplay -s h -l help
complete -c vgdisplay -l ignorelockingfailure
complete -c vgdisplay -l journal
complete -c vgdisplay -l lockopt
complete -c vgdisplay -l logonly
complete -c vgdisplay -l longhelp
complete -c vgdisplay -l noheadings
complete -c vgdisplay -l nohints
complete -c vgdisplay -l nolocking
complete -c vgdisplay -l nosuffix
complete -c vgdisplay -s o -l options
complete -c vgdisplay -o o+field1 -o o-field3 -o 'o#field5' -d 'These lists are evaluated from left to right'
complete -c vgdisplay -l profile
complete -c vgdisplay -s q -l quiet
complete -c vgdisplay -l readonly
complete -c vgdisplay -s S -l select
complete -c vgdisplay -l separator
complete -c vgdisplay -l shared
complete -c vgdisplay -s s -l short
complete -c vgdisplay -s O -l sort
complete -c vgdisplay -s t -l test
complete -c vgdisplay -l unbuffered
complete -c vgdisplay -l units
complete -c vgdisplay -s v -l verbose
complete -c vgdisplay -l version
complete -c vgdisplay -s y -l yes

