# vgexport
# Autogenerated from man page /usr/share/man/man8/vgexport.8.gz
complete -c vgexport -s a -l all
complete -c vgexport -l commandprofile
complete -c vgexport -l config
complete -c vgexport -s d -l debug
complete -c vgexport -l devices
complete -c vgexport -l devicesfile
complete -c vgexport -l driverloaded
complete -c vgexport -s h -l help
complete -c vgexport -l journal
complete -c vgexport -l lockopt
complete -c vgexport -l longhelp
complete -c vgexport -l nohints
complete -c vgexport -l nolocking
complete -c vgexport -l profile
complete -c vgexport -s q -l quiet
complete -c vgexport -l reportformat
complete -c vgexport -s S -l select
complete -c vgexport -s t -l test
complete -c vgexport -s v -l verbose
complete -c vgexport -l version
complete -c vgexport -s y -l yes

