# vgextend
# Autogenerated from man page /usr/share/man/man8/vgextend.8.gz
complete -c vgextend -l labelsector -l metadatasize -l metadataignore
complete -c vgextend -l pvmetadatacopies -l dataalignment -l dataalignmentoffset
complete -c vgextend -s A -l autobackup
complete -c vgextend -l commandprofile
complete -c vgextend -l config
complete -c vgextend -s d -l debug
complete -c vgextend -l devices
complete -c vgextend -l devicesfile
complete -c vgextend -l driverloaded
complete -c vgextend -s f -l force
complete -c vgextend -s h -l help
complete -c vgextend -l journal
complete -c vgextend -l lockopt
complete -c vgextend -l longhelp
complete -c vgextend -s M -l metadatatype
complete -c vgextend -l nohints
complete -c vgextend -l nolocking
complete -c vgextend -l profile
complete -c vgextend -s q -l quiet
complete -c vgextend -l reportformat
complete -c vgextend -l restoremissing
complete -c vgextend -s t -l test
complete -c vgextend -s v -l verbose
complete -c vgextend -l version
complete -c vgextend -s y -l yes
complete -c vgextend -s Z -l zero
complete -c vgextend -l restorefile -l uuid

