# vgimportclone
# Autogenerated from man page /usr/share/man/man8/vgimportclone.8.gz
complete -c vgimportclone -s n -l basevgname
complete -c vgimportclone -l commandprofile
complete -c vgimportclone -l config
complete -c vgimportclone -s d -l debug
complete -c vgimportclone -l devices
complete -c vgimportclone -l devicesfile
complete -c vgimportclone -l driverloaded
complete -c vgimportclone -s h -l help
complete -c vgimportclone -s i -l import
complete -c vgimportclone -l importdevices
complete -c vgimportclone -l journal
complete -c vgimportclone -l lockopt
complete -c vgimportclone -l longhelp
complete -c vgimportclone -l nohints
complete -c vgimportclone -l nolocking
complete -c vgimportclone -l profile
complete -c vgimportclone -s q -l quiet
complete -c vgimportclone -s t -l test
complete -c vgimportclone -s v -l verbose
complete -c vgimportclone -l version
complete -c vgimportclone -s y -l yes

