# vgmerge
# Autogenerated from man page /usr/share/man/man8/vgmerge.8.gz
complete -c vgmerge -s A -l autobackup
complete -c vgmerge -l commandprofile
complete -c vgmerge -l config
complete -c vgmerge -s d -l debug
complete -c vgmerge -l devices
complete -c vgmerge -l devicesfile
complete -c vgmerge -l driverloaded
complete -c vgmerge -s h -l help
complete -c vgmerge -l journal
complete -c vgmerge -s l -l list
complete -c vgmerge -l lockopt
complete -c vgmerge -l longhelp
complete -c vgmerge -l nohints
complete -c vgmerge -l nolocking
complete -c vgmerge -l poolmetadataspare
complete -c vgmerge -l profile
complete -c vgmerge -s q -l quiet
complete -c vgmerge -s t -l test
complete -c vgmerge -s v -l verbose
complete -c vgmerge -l version
complete -c vgmerge -s y -l yes

