# vgmknodes
# Autogenerated from man page /usr/share/man/man8/vgmknodes.8.gz
complete -c vgmknodes -l commandprofile
complete -c vgmknodes -l config
complete -c vgmknodes -s d -l debug
complete -c vgmknodes -l devices
complete -c vgmknodes -l devicesfile
complete -c vgmknodes -l driverloaded
complete -c vgmknodes -s h -l help
complete -c vgmknodes -l ignorelockingfailure
complete -c vgmknodes -l journal
complete -c vgmknodes -l lockopt
complete -c vgmknodes -l longhelp
complete -c vgmknodes -l nohints
complete -c vgmknodes -l nolocking
complete -c vgmknodes -l profile
complete -c vgmknodes -s q -l quiet
complete -c vgmknodes -l refresh
complete -c vgmknodes -l reportformat
complete -c vgmknodes -s t -l test
complete -c vgmknodes -s v -l verbose
complete -c vgmknodes -l version
complete -c vgmknodes -s y -l yes

