# vgremove
# Autogenerated from man page /usr/share/man/man8/vgremove.8.gz
complete -c vgremove -l commandprofile
complete -c vgremove -l config
complete -c vgremove -s d -l debug
complete -c vgremove -l devices
complete -c vgremove -l devicesfile
complete -c vgremove -l driverloaded
complete -c vgremove -s f -l force
complete -c vgremove -s h -l help
complete -c vgremove -l journal
complete -c vgremove -l lockopt
complete -c vgremove -l longhelp
complete -c vgremove -l nohints
complete -c vgremove -l nolocking
complete -c vgremove -l noudevsync
complete -c vgremove -l profile
complete -c vgremove -s q -l quiet
complete -c vgremove -l reportformat
complete -c vgremove -s S -l select
complete -c vgremove -s t -l test
complete -c vgremove -s v -l verbose
complete -c vgremove -l version
complete -c vgremove -s y -l yes

