# vgrename
# Autogenerated from man page /usr/share/man/man8/vgrename.8.gz
complete -c vgrename -s A -l autobackup
complete -c vgrename -l commandprofile
complete -c vgrename -l config
complete -c vgrename -s d -l debug
complete -c vgrename -l devices
complete -c vgrename -l devicesfile
complete -c vgrename -l driverloaded
complete -c vgrename -s f -l force
complete -c vgrename -s h -l help
complete -c vgrename -l journal
complete -c vgrename -l lockopt
complete -c vgrename -l longhelp
complete -c vgrename -l nohints
complete -c vgrename -l nolocking
complete -c vgrename -l profile
complete -c vgrename -s q -l quiet
complete -c vgrename -l reportformat
complete -c vgrename -s t -l test
complete -c vgrename -s v -l verbose
complete -c vgrename -l version
complete -c vgrename -s y -l yes

