# vgs
# Autogenerated from man page /usr/share/man/man8/vgs.8.gz
complete -c vgs -l aligned
complete -c vgs -s a -l all
complete -c vgs -l binary
complete -c vgs -l commandprofile
complete -c vgs -l config
complete -c vgs -l configreport
complete -c vgs -s d -l debug
complete -c vgs -l devices
complete -c vgs -l devicesfile
complete -c vgs -l driverloaded
complete -c vgs -l foreign
complete -c vgs -s h -l help
complete -c vgs -l ignorelockingfailure
complete -c vgs -l journal
complete -c vgs -l lockopt
complete -c vgs -l logonly
complete -c vgs -l longhelp
complete -c vgs -l nameprefixes
complete -c vgs -l noheadings
complete -c vgs -l nohints
complete -c vgs -l nolocking
complete -c vgs -l nosuffix
complete -c vgs -s o -l options
complete -c vgs -o o+field1 -o o-field3 -o 'o#field5' -d 'These lists are evaluated from left to right'
complete -c vgs -l profile
complete -c vgs -s q -l quiet
complete -c vgs -l readonly
complete -c vgs -l reportformat
complete -c vgs -l rows
complete -c vgs -s S -l select
complete -c vgs -l separator
complete -c vgs -l shared
complete -c vgs -s O -l sort
complete -c vgs -s t -l test
complete -c vgs -l unbuffered
complete -c vgs -l units
complete -c vgs -l unquoted
complete -c vgs -s v -l verbose
complete -c vgs -l version
complete -c vgs -s y -l yes

