# vgscan
# Autogenerated from man page /usr/share/man/man8/vgscan.8.gz
complete -c vgscan -l commandprofile
complete -c vgscan -l config
complete -c vgscan -s d -l debug
complete -c vgscan -l devices
complete -c vgscan -l devicesfile
complete -c vgscan -l driverloaded
complete -c vgscan -s h -l help
complete -c vgscan -l ignorelockingfailure
complete -c vgscan -l journal
complete -c vgscan -l lockopt
complete -c vgscan -l longhelp
complete -c vgscan -l mknodes
complete -c vgscan -l nohints
complete -c vgscan -l nolocking
complete -c vgscan -l notifydbus
complete -c vgscan -l profile
complete -c vgscan -s q -l quiet
complete -c vgscan -l reportformat
complete -c vgscan -s t -l test
complete -c vgscan -s v -l verbose
complete -c vgscan -l version
complete -c vgscan -s y -l yes

