# vwebp
# Autogenerated from man page /usr/share/man/man1/vwebp.1.gz
complete -c vwebp -s h -d 'Print usage summary'
complete -c vwebp -o version -d 'Print version number and exit'
complete -c vwebp -o noicc -d 'Don\'t use the ICC profile if present'
complete -c vwebp -o nofancy -d 'Don\'t use the fancy YUV420 upscaler'
complete -c vwebp -o nofilter -d 'Disable in-loop filtering'
complete -c vwebp -o dither -d 'Specify a dithering strength between 0 and 100'
complete -c vwebp -o noalphadither -d 'By default, quantized transparency planes are dithered during decompression, …'
complete -c vwebp -o usebgcolor -d 'Fill transparent areas with the bitstream\'s own background color instead of c…'
complete -c vwebp -o mt -d 'Use multi-threading for decoding, if possible'
complete -c vwebp -o info -d 'Display image information on top of the decoded image'

