# winicontoppm
# Autogenerated from man page /usr/share/man/man1/winicontoppm.1.gz
complete -c winicontoppm -o writeands -d 'For each icon written, also write the \'and\' (transparancy) mask as a separate…'
complete -c winicontoppm -o allicons -d 'Extract all images from the . ico file'
complete -c winicontoppm -o bestqual -d 'Extract only the best quality (largest, then highest bpp) image from the '
complete -c winicontoppm -o multippm -d 'Write all PPMs to a single file'

