# wsimport-openjdk8
# Autogenerated from man page /usr/share/man/man1/wsimport-openjdk8.1.gz
complete -c wsimport-openjdk8 -s d -d 'br Specifies where to place generated output files'
complete -c wsimport-openjdk8 -s b -d 'br Specifies external JAX-WS or JAXB binding files'
complete -c wsimport-openjdk8 -s B -d 'br Passes the \\f3jaxbOption option to the JAXB schema compiler'
complete -c wsimport-openjdk8 -o catalog -d 'br Specifies a catalog file to resolve external entity references'
complete -c wsimport-openjdk8 -o extension -d 'br Allows vendor extensions'
complete -c wsimport-openjdk8 -o help -d 'br Displays a help message for the \\f3wsimport command'
complete -c wsimport-openjdk8 -o httpproxy -d 'br Specifies an HTTP proxy server.  The default is 8080'
complete -c wsimport-openjdk8 -o keep -d 'br Keeps generated files'
complete -c wsimport-openjdk8 -s p -d 'br Specifies a target package name to override the WSDL and schema binding cu…'
complete -c wsimport-openjdk8 -s s -d 'br Specifies where to place generated source files'
complete -c wsimport-openjdk8 -o verbose -d 'br Displays compiler messages'
complete -c wsimport-openjdk8 -o version -d 'br Prints release information'
complete -c wsimport-openjdk8 -o wsdllocation -d 'br Specifies the \\f3@WebServiceClient. wsdlLocation value'
complete -c wsimport-openjdk8 -o target -d 'br Generates code according to the specified JAX-WS specification version'
complete -c wsimport-openjdk8 -o quiet
complete -c wsimport-openjdk8 -o XadditionalHeaders
complete -c wsimport-openjdk8 -o Xauthfile
complete -c wsimport-openjdk8 -o Xdebug
complete -c wsimport-openjdk8 -o Xno-addressing-databinding
complete -c wsimport-openjdk8 -o Xnocompile

