# wvgain
# Autogenerated from man page /usr/share/man/man1/wvgain.1.gz
complete -c wvgain -s a -d 'album mode (all files scanned are considered an album)'
complete -c wvgain -s c -d 'clean ReplayGain values from all files'
complete -c wvgain -s d -d 'display calculated values only (no files are modified)'
complete -c wvgain -s i -d 'ignore . wvc file (forces hybrid lossy)'
complete -c wvgain -s n -d 'new files only (skip files with track info, or album info if album mode speci…'
complete -c wvgain -s q -d 'quiet (keep console output to a minimum)'
complete -c wvgain -s s -d 'show stored values only (no analysis)'
complete -c wvgain -s v -d 'write program version to stdout'
complete -c wvgain -s z -d 'don\\*(Aqt set (n = 0 or omitted) or set (n = 1) console title to indicate pro…'

