# wvtag
# Autogenerated from man page /usr/share/man/man1/wvtag.1.gz
complete -c wvtag -l allow-huge-tags -d 'allow tag data up to 16 MB (embedding > 1 MB is not recommended for portable …'
complete -c wvtag -s c -d 'extract cuesheet only to stdout (equivalent to -x \\(lqcuesheet\\(rq)'
complete -c wvtag -o cc -d 'extract cuesheet to source-name'
complete -c wvtag -l clean -l clear -d 'clean all items from tag (done first)'
complete -c wvtag -s d -d 'delete specified metadata item (text or binary)'
complete -c wvtag -s h -l help -d 'this help display'
complete -c wvtag -l import-id3 -d 'import applicable tag items from ID3v2'
complete -c wvtag -s l -l list -d 'list all tag items (done last)'
complete -c wvtag -l no-utf8-convert -d 'don\\*(Aqt recode passed tags from local encoding to UTF-8, assume they are in…'
complete -c wvtag -s q -d 'quiet (keep console output to a minimum)'
complete -c wvtag -s v -l version -d 'write program version to stdout'
complete -c wvtag -s w -d 'delete specified metadata item (text or binary)'
complete -c wvtag -l write-binary-tag -d 'write the specified binary metadata file to APEv2 tag, normally used for cove…'
complete -c wvtag -s x -d 'extract the specified tag field only to stdout'
complete -c wvtag -o xx -d 'extract the specified tag field to named file in same directory as source fil…'
complete -c wvtag -s y -d 'yes to all warnings (use with caution!)'

