# Xephyr
# Autogenerated from man page /usr/share/man/man1/Xephyr.1.gz
complete -c Xephyr -o screen -d 'sets the screen size'
complete -c Xephyr -o parent -d 'uses existing window  id '
complete -c Xephyr -o host-cursor -d 'set \'cursor acceleration\': The host\'s cursor is reused'
complete -c Xephyr -o resizeable -d 'Allow the Xephyr window to be resized, even if not embedded into a parent win…'
complete -c Xephyr -o no-host-grab -d 'Disable grabbing the keyboard and mouse'

