# xfburn
# Autogenerated from man page /usr/share/man/man1/xfburn.1.gz
complete -c xfburn -l burn-image -d 'to immediately show the burn image dialog'
complete -c xfburn -l data-composition -d 'or the'
complete -c xfburn -l audio-composition -d 'options is specified, then xfburns main window will open up with the selected…'
complete -c xfburn -s '?' -l help
complete -c xfburn -s V -l version
complete -c xfburn -s i
complete -c xfburn -s b -l blank
complete -c xfburn -s d
complete -c xfburn -s a
complete -c xfburn -s t -l transcoder
complete -c xfburn -s m -l main
complete -c xfburn -l display

