# xfce4-screenshooter
# Autogenerated from man page /usr/share/man/man1/xfce4-screenshooter.1.gz
complete -c xfce4-screenshooter -s h -l help -d 'Show help options'
complete -c xfce4-screenshooter -l help-all -d 'Show all help options'
complete -c xfce4-screenshooter -l help-gtk -d 'Show GTK+ Options . SS "Application Options:"'
complete -c xfce4-screenshooter -s c -l clipboard -d 'Copy the screenshot to the clipboard'
complete -c xfce4-screenshooter -s d -l delay -d 'Delay in seconds before taking the screenshot'
complete -c xfce4-screenshooter -s f -l fullscreen -d 'Take a screenshot of the entire screen'
complete -c xfce4-screenshooter -s m -l mouse -d 'Display the mouse on the screenshot'
complete -c xfce4-screenshooter -l no-border -d 'Removes the window border from the screenshot'
complete -c xfce4-screenshooter -s o -l open -d 'Application to open the screenshot'
complete -c xfce4-screenshooter -s r -l region -d 'Select a region to be captured by clicking a point of the screen without rele…'
complete -c xfce4-screenshooter -s s -l save -d 'File path or directory where the screenshot will be saved, accepts png, jpg a…'
complete -c xfce4-screenshooter -s i -l imgur -d 'Host the screenshot on Imgur, a free online image hosting service'
complete -c xfce4-screenshooter -s V -l version -d 'Version information'
complete -c xfce4-screenshooter -s w -l window -d 'Take a screenshot of the active window'
complete -c xfce4-screenshooter -l display -d 'X display to use'

