# xfce4-power-manager
# Autogenerated from man page /usr/share/man/man1/xfce4-power-manager.1.gz
complete -c xfce4-power-manager -l daemon -d 'Starts the power manager in daemon mode'
complete -c xfce4-power-manager -l debug -d 'Have the power manager print debug messages to the console; useful if you hav…'
complete -c xfce4-power-manager -l dump -d 'Have the power manager print the configuration information to the console'
complete -c xfce4-power-manager -l restart -d 'Causes the running power manager to restart'
complete -c xfce4-power-manager -l customize -d 'Shows the configuration dialog'
complete -c xfce4-power-manager -l quit -d 'Causes any running instance of xfce4-power-manager to exit'
complete -c xfce4-power-manager -l version -d 'Show the version information'

