# xfce4-notifyd-config
# Autogenerated from man page /usr/share/man/man1/xfce4-notifyd-config.1.gz
complete -c xfce4-notifyd-config -s '?' -l help -d 'Show help'
complete -c xfce4-notifyd-config -s V -l version -d 'Display version information'
complete -c xfce4-notifyd-config -s s -l socket-id -d 'Settings manager socket'
complete -c xfce4-notifyd-config -l display -d 'X display to use AUTHORS xfce4-notifyd-config was written by Brian Tarricone …'

