# xfce4-sensors
# Autogenerated from man page /usr/share/man/man1/xfce4-sensors.1.gz
complete -c xfce4-sensors -s h -l help -d 'display a short help text'
complete -c xfce4-sensors -s l -l license -d 'print license information'
complete -c xfce4-sensors -s V -l version -d 'print version information AUTHOR Fabian Nowak <timystery@arcor. de>'

