# xfce4-session-logout
# Autogenerated from man page /usr/share/man/man1/xfce4-session-logout.1.gz
complete -c xfce4-session-logout -l logout -d 'Log out without displaying the logout dialog'
complete -c xfce4-session-logout -l halt -d 'Halt without displaing the logout dialog'
complete -c xfce4-session-logout -l reboot -d 'Reboot without displaying the logout dialog'
complete -c xfce4-session-logout -l suspend -d 'Suspend without displaying the logout dialog'
complete -c xfce4-session-logout -l hibernate -d 'Hibernate without displaying the logout dialog'
complete -c xfce4-session-logout -l hybrid-sleep -d 'Hybrid Sleep without displaying the logout dialog'
complete -c xfce4-session-logout -l fast -d 'Do a fast shutdown'
complete -c xfce4-session-logout -l help -d 'Print a help screen and exit'
complete -c xfce4-session-logout -l version -d 'Output version information and exit'

