# xfce4-dict
# Autogenerated from man page /usr/share/man/man1/xfce4-dict.1.gz
complete -c xfce4-dict -s d -l dict -d 'Search the given text using a Dict server(RFC 2229)'
complete -c xfce4-dict -s w -l web -d 'Search the given text using a web-based search engine'
complete -c xfce4-dict -s t -l text-field -d 'Grab the focus on the text field in the panel (has no effect if panel plugin …'
complete -c xfce4-dict -s s -l spell -d 'Check the given text with a spellchecker'
complete -c xfce4-dict -s i -l ignore-plugin -d 'Start stand-alone application even if the panel plugin is loaded'
complete -c xfce4-dict -s c -l clipboard -d 'Grabs the PRIMARY selection content (X selection clipboard), uses it as searc…'
complete -c xfce4-dict -s v -l verbose -d 'Be verbose (print useful status messages)'
complete -c xfce4-dict -s V -l version -d 'Show version information'

