# xfce4-screensaver-command
# Autogenerated from man page /usr/share/man/man1/xfce4-screensaver-command.1.gz
complete -c xfce4-screensaver-command -l exit -d 'Causes the screensaver to exit gracefully'
complete -c xfce4-screensaver-command -s q -l query -d 'Query the state of the screensaver'
complete -c xfce4-screensaver-command -s t -l time -d 'Query the length of time the screensaver has been active'
complete -c xfce4-screensaver-command -s l -l lock -d 'Tells the running screensaver process to lock the screen immediately'
complete -c xfce4-screensaver-command -s c -l cycle -d 'If the screensaver is active then switch to another graphics demo'
complete -c xfce4-screensaver-command -s a -l activate -d 'Turn the screensaver on (blank the screen)'
complete -c xfce4-screensaver-command -s d -l deactivate -d 'If the screensaver is active then deactivate it (un-blank the screen)'
complete -c xfce4-screensaver-command -s p -l poke -d 'Poke the running screensaver to simulate user activity'
complete -c xfce4-screensaver-command -s i -l inhibit -d 'Inhibit the screensaver from activating'
complete -c xfce4-screensaver-command -s n -l application-name -d 'The calling application that is inhibiting the screensaver'
complete -c xfce4-screensaver-command -s r -l reason -d 'The reason for inhibiting the screensaver'
complete -c xfce4-screensaver-command -s V -l version -d 'Version of this application AUTHORS'

