# xfce4-session
# Autogenerated from man page /usr/share/man/man1/xfce4-session.1.gz
complete -c xfce4-session -l disable-tcp -d 'Disable binding to TCP ports in the ICE layer'
complete -c xfce4-session -l help -d 'Print a help screen and exit'
complete -c xfce4-session -l version -d 'Output version information and exit'

