# xfce4-screensaver
# Autogenerated from man page /usr/share/man/man1/xfce4-screensaver.1.gz
complete -c xfce4-screensaver -l display -d 'X display to use'
complete -c xfce4-screensaver -l debug -d 'Enable debugging messages for xfce4-screensaver'
complete -c xfce4-screensaver -l version -d 'Output version information and exit'
complete -c xfce4-screensaver -s h -l help -d 'Print standard command line options'
complete -c xfce4-screensaver -l help-all -d 'Print all command line options'

