# xfdesktop
# Autogenerated from man page /usr/share/man/man1/xfdesktop.1.gz
complete -c xfdesktop -s h -l help -d 'Show help options'
complete -c xfdesktop -l help-all -d 'Show all help options'
complete -c xfdesktop -l help-gtk -d 'Show GTK+ Options'
complete -c xfdesktop -l help-sm-client -d 'Show session management options  . SS APPLICATION OPTIONS:'
complete -c xfdesktop -s V -l version -d 'Display version information'
complete -c xfdesktop -s R -l reload -d 'Causes an already-running instance of xfdesktop to reload all its settings an…'
complete -c xfdesktop -s N -l next -d 'Causes an already-running instance of xfdesktop to advance to the next wallpa…'
complete -c xfdesktop -s M -l menu -d 'Causes an already-running instance of xfdesktop to pop up the applications me…'
complete -c xfdesktop -s W -l windowlist -d 'Causes an already-running instance of xfdesktop to pop up the window list men…'
complete -c xfdesktop -s A -l arrange -d 'Automatically arrange all the icons on the desktop'
complete -c xfdesktop -s D -l disable-wm-check -d 'Do not wait for a window manager on startup'
complete -c xfdesktop -s e -l enable-debug -d 'Enable debug messages'
complete -c xfdesktop -s d -l disable-debug -d 'Disable debug messages'
complete -c xfdesktop -s Q -l quit -d 'Cause xfdesktop to quit'
complete -c xfdesktop -l display -d 'X display to use'

