# xfs_mkfile
# Autogenerated from man page /usr/share/man/man8/xfs_mkfile.8.gz
complete -c xfs_mkfile -s v -d 'Verbose.  Report the names and sizes of created files'
complete -c xfs_mkfile -s n -d 'No bytes'
complete -c xfs_mkfile -s p -d Preallocate
complete -c xfs_mkfile -s V -d 'Prints the version number and exits'

