# xfs_bmap
# Autogenerated from man page /usr/share/man/man8/xfs_bmap.8.gz
complete -c xfs_bmap -s a -d 'If this option is specified, information about the file\'s attribute fork is p…'
complete -c xfs_bmap -s e -d 'If this option is used,  xfs_bmap obtains all delayed allocation extents, and…'
complete -c xfs_bmap -s l -d 'If this option is used, then'
complete -c xfs_bmap -s n -d 'If this option is given,  xfs_bmap will display at most  num_extents extents'
complete -c xfs_bmap -s p -d 'If this option is used,  xfs_bmap obtains all unwritten (preallocated) extent…'
complete -c xfs_bmap -s v -d 'Shows verbose information'
complete -c xfs_bmap -s V -d 'Prints the version number and exits.  SEE ALSO xfs_fsr (8), xfs (5)'

