# xfs_spaceman
# Autogenerated from man page /usr/share/man/man8/xfs_spaceman.8.gz
complete -c xfs_spaceman -s c -d 'xfs_spaceman commands may be run interactively (the default) or as arguments …'
complete -c xfs_spaceman -s a -d 'Collect free space information from this allocation group'
complete -c xfs_spaceman -s b -d 'This argument establishes that the histogram bin sizes are successive powers …'
complete -c xfs_spaceman -s e -s h -s m
complete -c xfs_spaceman -s d -d 'Print debugging information such as the raw free space extent information'
complete -c xfs_spaceman -s g -d 'Print the free space block and extent counts for each AG'
complete -c xfs_spaceman -s r -d 'Query the realtime device for free space information'
complete -c xfs_spaceman -s s -d 'Display a summary of the free space information found'
complete -c xfs_spaceman -s f -d 'Report on the health of metadata that affect the entire filesystem'
complete -c xfs_spaceman -s i -d 'Report on the health of a specific inode'
complete -c xfs_spaceman -s q -d 'Report only unhealthy metadata'
complete -c xfs_spaceman -s u -s p -d 'options are given, this command acts on all files'

