# xfs_ncheck
# Autogenerated from man page /usr/share/man/man8/xfs_ncheck.8.gz
complete -c xfs_ncheck -s f -d 'Specifies that the filesystem image to be processed is stored in a regular fi…'
complete -c xfs_ncheck -s l -d 'Specifies the device where the filesystem\'s external log resides'
complete -c xfs_ncheck -s s -d 'Limits the report to special files and files with setuserid mode'
complete -c xfs_ncheck -s i -d 'Limits the report to only those files whose inode numbers follow'
complete -c xfs_ncheck -s V -d 'Prints the version number and exits'

