# xfs_scrub_all
# Autogenerated from man page /usr/share/man/man8/xfs_scrub_all.8.gz
complete -c xfs_scrub_all -s h -d 'Display help'
complete -c xfs_scrub_all -s V -d 'Prints the version number and exits'

