# xfs_logprint
# Autogenerated from man page /usr/share/man/man8/xfs_logprint.8.gz
complete -c xfs_logprint -s b -d 'Extract and print buffer information.  Only used in transactional view'
complete -c xfs_logprint -s c -d 'Attempt to continue when an error is detected'
complete -c xfs_logprint -s C -d 'Copy the log from the filesystem to the file R filename '
complete -c xfs_logprint -s d -d 'Dump the log from front to end, printing where each log record is located on …'
complete -c xfs_logprint -s D -d 'Do not decode anything; just print data'
complete -c xfs_logprint -s e -d 'Exit when an error is found in the log'
complete -c xfs_logprint -s f -d 'Specifies that the filesystem image to be processed is stored in a regular fi…'
complete -c xfs_logprint -s l -d 'External log device.  Only for those filesystems which use an external log'
complete -c xfs_logprint -s i -d 'Extract and print inode information.  Only used in transactional view'
complete -c xfs_logprint -s q -d 'Extract and print quota information.  Only used in transactional view'
complete -c xfs_logprint -s n -d 'Do not try and interpret log data; just interpret log header information'
complete -c xfs_logprint -s o -d 'Also print buffer data in hex'
complete -c xfs_logprint -s s -d 'Override any notion of where to start printing'
complete -c xfs_logprint -s t -d 'Print out the transactional view'
complete -c xfs_logprint -s v -d 'Print "overwrite" data'
complete -c xfs_logprint -s V -d 'Prints the version number and exits.  SEE ALSO mkfs. xfs (8), mount (8)'

