# xfs_scrub
# Autogenerated from man page /usr/share/man/man8/xfs_scrub.8.gz
complete -c xfs_scrub -s a -d 'Abort if more than this many errors are found on the filesystem'
complete -c xfs_scrub -s b -d 'Run in background mode'
complete -c xfs_scrub -s C -d 'This option causes xfs_scrub to write progress information to the specified f…'
complete -c xfs_scrub -s e -d 'Specifies what happens when errors are detected'
complete -c xfs_scrub -s k -d 'Do not call TRIM on the free space'
complete -c xfs_scrub -s m -d 'Search this file for mounted filesystems instead of /etc/mtab'
complete -c xfs_scrub -s n -d 'Only check filesystem metadata.  Do not repair or optimize anything'
complete -c xfs_scrub -s T -d 'Print timing and memory usage information for each phase'
complete -c xfs_scrub -s v -d 'Enable verbose mode, which prints periodic status updates'
complete -c xfs_scrub -s V -d 'Prints the version number and exits'
complete -c xfs_scrub -s x -d 'Read all file data extents to look for disk errors'

