# xfs_freeze
# Autogenerated from man page /usr/share/man/man8/xfs_freeze.8.gz
complete -c xfs_freeze -s f -d 'flag requests the specified XFS filesystem to be frozen from new modifications'
complete -c xfs_freeze -s u -d 'flag is used to un-freeze the filesystem and allow operations to continue'
complete -c xfs_freeze -s V -d 'flag prints the version number and exits'

