# xfs_fsr
# Autogenerated from man page /usr/share/man/man8/xfs_fsr.8.gz
complete -c xfs_fsr -s t -d 'How long to reorganize.  The default is 7200 seconds (2 hours)'
complete -c xfs_fsr -s p -d 'Number of passes before terminating global re-org.  The default is 10 passes'
complete -c xfs_fsr -s f -d 'Use this file instead of  /var/tmp/'
complete -c xfs_fsr -s v -d 'Verbose.  Print cryptic information about each file being reorganized'
complete -c xfs_fsr -s d -d 'Debug.   Print even more cryptic information'
complete -c xfs_fsr -s g -d 'Print to syslog (default if stdout not a tty)'
complete -c xfs_fsr -s m
complete -c xfs_fsr -s V -d 'Prints the version number and exits'

