# xfs_mdrestore
# Autogenerated from man page /usr/share/man/man8/xfs_mdrestore.8.gz
complete -c xfs_mdrestore -s g -d 'Shows restore progress on stdout'
complete -c xfs_mdrestore -s i -d 'Shows metadump information on stdout'
complete -c xfs_mdrestore -s V -d 'Prints the version number and exits'

