# xml2-config
# Autogenerated from man page /usr/share/man/man1/xml2-config.1.gz
complete -c xml2-config -l version -d 'Print the currently installed version of GNOME-XML on the standard output'
complete -c xml2-config -l libs -d 'Print the linker flags that are necessary to link a GNOME-XML program'
complete -c xml2-config -l cflags -d 'Print the compiler flags that are necessary to compile a GNOME-XML program'
complete -c xml2-config -l prefix -d 'If specified, use PREFIX instead of the installation prefix that GNOME-XML wa…'

