# xmlsec1-config
# Autogenerated from man page /usr/share/man/man1/xmlsec1-config.1.gz
complete -c xmlsec1-config -l cflags -d 'print pre-processor and compiler flags'
complete -c xmlsec1-config -l libs -d 'print library linking information'
complete -c xmlsec1-config -l prefix -d 'print the default XMLSEC prefix folder'
complete -c xmlsec1-config -l exec-prefix -d 'print the default XMLSEC executable prefix folder'
complete -c xmlsec1-config -l libdir -d 'print the default XMLSEC libraries folder'
complete -c xmlsec1-config -l crypto -d 'print the default crypto library name'
complete -c xmlsec1-config -l help -d 'display this help and exit'
complete -c xmlsec1-config -l version -d 'output version information'

