# Xnest
# Autogenerated from man page /usr/share/man/man1/Xnest.1.gz
complete -c Xnest -o display -d 'This option specifies the display name of the real server that  Xnest should …'
complete -c Xnest -o sync -d 'This option tells  Xnest to synchronize its window and graphics operations wi…'
complete -c Xnest -o full -d 'This option tells  Xnest to utilize full regeneration of real server objects …'
complete -c Xnest -o class -d 'This option specifies the default visual class of the nested server'
complete -c Xnest -o depth -d 'This option specifies the default visual depth of the nested server'
complete -c Xnest -o sss -d 'This option tells  Xnest to use the software screen saver'
complete -c Xnest -o geometry -d 'This option specifies the geometry parameters for the top-level  Xnest window'
complete -c Xnest -o bw -d 'This option specifies the border width of the top-level  Xnest window'
complete -c Xnest -o name -d 'This option specifies the name of the top-level  Xnest window as R string '
complete -c Xnest -o scrns -d 'This option specifies the number of screens to create in the nested server'
complete -c Xnest -o install -d 'This option tells  Xnest to do its own color map installation by bypassing th…'
complete -c Xnest -o cc -d 'option from the set of standard options except that it will accept a string r…'
complete -c Xnest -o parent -d 'This option tells Xnest to use window_id as the root window instead of creati…'

