# xpmtoppm
# Autogenerated from man page /usr/share/man/man1/xpmtoppm.1.gz
complete -c xpmtoppm -l alphaout -d 'xpmtoppm creates a PBM file containing the transparency mask for the image'
complete -c xpmtoppm -l verbose -d 'xpmtoppm prints information about its processing on Standard Error'

