# xpstojpeg
# Autogenerated from man page /usr/share/man/man1/xpstojpeg.1.gz
complete -c xpstojpeg -s '?' -l help -d 'Show help options'
complete -c xpstojpeg -s d -l document -d 'The document inside the XPS file to convert'
complete -c xpstojpeg -s f -l first -d 'The first page to convert'
complete -c xpstojpeg -s l -l last -d 'The last page to convert'
complete -c xpstojpeg -s o -l odd -d 'Convert only odd pages'
complete -c xpstojpeg -s e -l even -d 'Convert only even pages'
complete -c xpstojpeg -s r -l resolution -d 'Horizontal and vertical resolution in PPI (Pixels Per Inch)'
complete -c xpstojpeg -l rx -d 'Horizontal resolution in PPI (Pixels Per Inch).  The default is 150 PPI'
complete -c xpstojpeg -l ry -d 'Vertical resolution in PPI (Pixels Per Inch).  The default is 150 PPI'
complete -c xpstojpeg -s x -l crop-x -d 'The x-coordinate of the crop area top left corner'
complete -c xpstojpeg -s y -l crop-y -d 'The y-coordinate of the crop area top left corner'
complete -c xpstojpeg -s w -l crop-width -d 'The width of crop area'
complete -c xpstojpeg -s h -l crop-height -d 'The height of crop area'

