# xtotroff
# Autogenerated from man page /usr/share/man/man1/xtotroff.1.gz
complete -c xtotroff -l help -d 'Display a usage message and exit'
complete -c xtotroff -s r -d 'Set the resolution for all font patterns in R font-map '
complete -c xtotroff -s s -d 'Set the point size for all font patterns in R font-map '
complete -c xtotroff -s v
complete -c xtotroff -l version -d 'Display version information and exit'

