# Xvfb
# Autogenerated from man page /usr/share/man/man1/Xvfb.1.gz
complete -c Xvfb -o screen -d 'This option creates screen screennum and sets its width, height, and depth to…'
complete -c Xvfb -o pixdepths -d 'This option specifies a list of pixmap depths that the server should support …'
complete -c Xvfb -o fbdir -d 'This option specifies the directory in which the memory mapped files containi…'
complete -c Xvfb -o shmem -d 'This option specifies that the framebuffer should be put in shared memory'
complete -c Xvfb -o linebias -d 'This option specifies how to adjust the pixelization of thin lines'
complete -c Xvfb -o blackpixel -o whitepixel -d 'These options specify the black and white pixel values the server should use'

