# xvfb-run
# Autogenerated from man page /usr/share/man/man1/xvfb-run.1.gz
complete -c xvfb-run -s a -l auto-servernum -d 'Try to get a free server number, starting at 99, or the argument to  --server…'
complete -c xvfb-run -s e -l error-file -d 'Store output from  xauth and  Xvfb in R file .  The default is R /dev/null '
complete -c xvfb-run -s f -l auth-file -d 'Store X authentication data in R file '
complete -c xvfb-run -s h -l help -d 'Display a usage message and exit'
complete -c xvfb-run -s n -l server-num -d 'Use  servernumber as the server number (but see the  -a, --auto-servernum opt…'
complete -c xvfb-run -s l -l listen-tcp -d 'Enable TCP port listening in the X server'
complete -c xvfb-run -s p -l xauth-protocol -d 'Use  protocolname as the X authority protocol to use.  The default is \\(oq'
complete -c xvfb-run -s s -l server-args -d 'Pass  arguments to the  Xvfb server'
complete -c xvfb-run -s w -l wait -d 'Wait delay seconds after launching Xvfb before attempting to start the specif…'
complete -c xvfb-run -o faces -d 'argument) inside the Xvfb X server, configured with a root window of 1024 by …'

