# Xwayland
# Autogenerated from man page /usr/share/man/man1/Xwayland.1.gz
complete -c Xwayland -o eglstream -d 'Use EGLStream backend for NVidia GPUs'
complete -c Xwayland -o initfd -d 'Add the given fd as a listen socket for initialization of X clients'
complete -c Xwayland -o listen -d 'deprecated, use -listenfd instead'
complete -c Xwayland -o listenfd -d 'Add given fd as a listen socket'
complete -c Xwayland -o noTouchPointerEmulation -d 'Disable touch pointer emulation'
complete -c Xwayland -o rootless -d 'Run Xwayland rootless, so that X clients integrate seamlessly with Wayland cl…'
complete -c Xwayland -o shm -d 'Force the shared memory backend instead of glamor (if available) for passing …'
complete -c Xwayland -o verbose -d 'Sets the verbosity level for information printed on stderr'
complete -c Xwayland -o version -d 'Show the server version and exit'
complete -c Xwayland -o wm -d 'This option is used by the Wayland server to pass Xwayland the socket where t…'

