# yuvsplittoppm
# Autogenerated from man page /usr/share/man/man1/yuvsplittoppm.1.gz
complete -c yuvsplittoppm -o ccir601 -d 'Assumes that the YUV triplets are scaled into the smaller range of the CCIR 6…'

