# zeisstopnm
# Autogenerated from man page /usr/share/man/man1/zeisstopnm.1.gz
complete -c zeisstopnm -o pgm -d 'Force the output to be in PGM format'
complete -c zeisstopnm -o ppm -d 'Force the output to be in PPM format'

